/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.energyloss.tabledefinition.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 能耗数据修改表实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
public class YJWJEnergyUpdateModel extends DomainModel {

	private static final long serialVersionUID = 1L;
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "YJWJ_energy_update";
	
	/** 主键 */
	public final static String ID = "id";	
	/** 设备id */
	public final static String EQ_ID = "eq_id";	
	/** 能耗修改数 */
	public final static String ENERGY_UPDATE = "energy_update";	
	/** 修改人 */
	public final static String USERNAME = "username";	

	public YJWJEnergyUpdateModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case ID:
			return "id";
		case EQ_ID:
			return "eq_id";
		case ENERGY_UPDATE:
			return "energy_update";
		case USERNAME:
			return "username";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getId() {
		return getAttribute(ID);
	}

	/**
	 * 设置主键
	 * @param id
	 */
	public void setId(String id) {
		setAttribute(ID, id);
	}

	/**
	 * 获取设备id
	 * @return
	 */
	public String getEq_id() {
		return getAttribute(EQ_ID);
	}

	/**
	 * 设置设备id
	 * @param eq_id
	 */
	public void setEq_id(String eq_id) {
		setAttribute(EQ_ID, eq_id);
	}

	/**
	 * 获取能耗修改数
	 * @return
	 */
	public String getEnergy_update() {
		return getAttribute(ENERGY_UPDATE);
	}

	/**
	 * 设置能耗修改数
	 * @param energy_update
	 */
	public void setEnergy_update(String energy_update) {
		setAttribute(ENERGY_UPDATE, energy_update);
	}

	/**
	 * 获取修改人
	 * @return
	 */
	public String getUsername() {
		return getAttribute(USERNAME);
	}

	/**
	 * 设置修改人
	 * @param username
	 */
	public void setUsername(String username) {
		setAttribute(USERNAME, username);
	}

}
