/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.areapersonnel.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 片区维修人员实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskAreaPersonnelModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_area_personnel";
	
	/** 主键ID */
	public final static String PK_PERSONNEL_ID = "pk_personnel_id";	
	/** 用户ID */
	public final static String USER_ID = "user_id";	
	/** 用户名称 */
	public final static String USER_NAME = "user_name";	
	/** 专业1 */
	public final static String MAJOR_ONE = "major_one";	
	/** 专业2 */
	public final static String MAJOR_TWO = "major_two";	
	/** 专业3 */
	public final static String MAJOR_THREE = "major_three";	
	/** 专业4 */
	public final static String MAJOR_FOUR = "major_four";	
	/** 专业5 */
	public final static String MAJOR_FIVE = "major_five";	
	/** 是否适应所有专业 */
	public final static String WHETHER_APPLY_ALL = "whether_apply_all";	
	/** 操作证书 */
	public final static String CERTIFICATE = "certificate";	
	/** 备注 */
	public final static String REMARKS = "remarks";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人ID */
	public final static String CREATE_USER_ID = "create_user_id";	
	/** 修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 最后修改人ID */
	public final static String UPDATE_USER_ID = "update_user_id";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYWorkTaskAreaPersonnelModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_PERSONNEL_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_PERSONNEL_ID:
			return "pk_personnel_id_";
		case USER_ID:
			return "user_id";
		case USER_NAME:
			return "user_name";
		case MAJOR_ONE:
			return "major_one";
		case MAJOR_TWO:
			return "major_two";
		case MAJOR_THREE:
			return "major_three";
		case MAJOR_FOUR:
			return "major_four";
		case MAJOR_FIVE:
			return "major_five";
		case WHETHER_APPLY_ALL:
			return "whether_apply_all";
		case CERTIFICATE:
			return "certificate";
		case REMARKS:
			return "remarks";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER_ID:
			return "create_user_id";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER_ID:
			return "update_user_id";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_personnel_id() {
		return getAttribute(PK_PERSONNEL_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_personnel_id
	 */
	public void setPk_personnel_id(String pk_personnel_id) {
		setAttribute(PK_PERSONNEL_ID, pk_personnel_id);
	}

	/**
	 * 获取用户ID
	 * @return
	 */
	public String getUser_id() {
		return getAttribute(USER_ID);
	}

	/**
	 * 设置用户ID
	 * @param user_id
	 */
	public void setUser_id(String user_id) {
		setAttribute(USER_ID, user_id);
	}

	/**
	 * 获取用户名称
	 * @return
	 */
	public String getUser_name() {
		return getAttribute(USER_NAME);
	}

	/**
	 * 设置用户名称
	 * @param user_name
	 */
	public void setUser_name(String user_name) {
		setAttribute(USER_NAME, user_name);
	}

	/**
	 * 获取专业1
	 * @return
	 */
	public String getMajor_one() {
		return getAttribute(MAJOR_ONE);
	}

	/**
	 * 设置专业1
	 * @param major_one
	 */
	public void setMajor_one(String major_one) {
		setAttribute(MAJOR_ONE, major_one);
	}

	/**
	 * 获取专业2
	 * @return
	 */
	public String getMajor_two() {
		return getAttribute(MAJOR_TWO);
	}

	/**
	 * 设置专业2
	 * @param major_two
	 */
	public void setMajor_two(String major_two) {
		setAttribute(MAJOR_TWO, major_two);
	}

	/**
	 * 获取专业3
	 * @return
	 */
	public String getMajor_three() {
		return getAttribute(MAJOR_THREE);
	}

	/**
	 * 设置专业3
	 * @param major_three
	 */
	public void setMajor_three(String major_three) {
		setAttribute(MAJOR_THREE, major_three);
	}

	/**
	 * 获取专业4
	 * @return
	 */
	public String getMajor_four() {
		return getAttribute(MAJOR_FOUR);
	}

	/**
	 * 设置专业4
	 * @param major_four
	 */
	public void setMajor_four(String major_four) {
		setAttribute(MAJOR_FOUR, major_four);
	}

	/**
	 * 获取专业5
	 * @return
	 */
	public String getMajor_five() {
		return getAttribute(MAJOR_FIVE);
	}

	/**
	 * 设置专业5
	 * @param major_five
	 */
	public void setMajor_five(String major_five) {
		setAttribute(MAJOR_FIVE, major_five);
	}

	/**
	 * 获取是否适应所有专业
	 * @return
	 */
	public Integer getWhether_apply_all() {
		return getAttribute(WHETHER_APPLY_ALL);
	}

	/**
	 * 设置是否适应所有专业
	 * @param whether_apply_all
	 */
	public void setWhether_apply_all(Integer whether_apply_all) {
		setAttribute(WHETHER_APPLY_ALL, whether_apply_all);
	}

	/**
	 * 获取操作证书
	 * @return
	 */
	public String getCertificate() {
		return getAttribute(CERTIFICATE);
	}

	/**
	 * 设置操作证书
	 * @param certificate
	 */
	public void setCertificate(String certificate) {
		setAttribute(CERTIFICATE, certificate);
	}

	/**
	 * 获取备注
	 * @return
	 */
	public String getRemarks() {
		return getAttribute(REMARKS);
	}

	/**
	 * 设置备注
	 * @param remarks
	 */
	public void setRemarks(String remarks) {
		setAttribute(REMARKS, remarks);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人ID
	 * @return
	 */
	public String getCreate_user_id() {
		return getAttribute(CREATE_USER_ID);
	}

	/**
	 * 设置创建人ID
	 * @param create_user_id
	 */
	public void setCreate_user_id(String create_user_id) {
		setAttribute(CREATE_USER_ID, create_user_id);
	}

	/**
	 * 获取修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取最后修改人ID
	 * @return
	 */
	public String getUpdate_user_id() {
		return getAttribute(UPDATE_USER_ID);
	}

	/**
	 * 设置最后修改人ID
	 * @param update_user_id
	 */
	public void setUpdate_user_id(String update_user_id) {
		setAttribute(UPDATE_USER_ID, update_user_id);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
