/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.quality.proinspect.inspect.standard.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 标准与岗位中间表实体类
 * 
 * @author dms
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class StandardStationModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_quality_standard_station";
	
	/** 核查标准主键 */
	public final static String PK_STANDARD = "pk_standard";	
	/** 岗位主键 */
	public final static String PK_STATION = "pk_station";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 最后一次生成生成任务日期 */
	public final static String LAST_GENERATE_DATE = "last_generate_date";	
	/** 最后生成任务的完成期限 */
	public final static String LAST_DEADLINE_DATE = "last_deadline_date";	
	/** 标准加入岗位时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	

	public StandardStationModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_STANDARD;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_STANDARD:
			return "pk_standard";
		case PK_STATION:
			return "pk_station";
		case PK_CROP:
			return "pk_crop";
		case LAST_GENERATE_DATE:
			return "last_generate_date";
		case LAST_DEADLINE_DATE:
			return "last_deadline_date";
		case CREATE_TIME:
			return "create_time";
		case UPDATE_TIME:
			return "update_time";
		}
		return null;
	}

	/**
	 * 获取核查标准主键
	 * @return
	 */
	public String getPk_standard() {
		return getAttribute(PK_STANDARD);
	}

	/**
	 * 设置核查标准主键
	 * @param pk_standard
	 */
	public void setPk_standard(String pk_standard) {
		setAttribute(PK_STANDARD, pk_standard);
	}

	/**
	 * 获取岗位主键
	 * @return
	 */
	public String getPk_station() {
		return getAttribute(PK_STATION);
	}

	/**
	 * 设置岗位主键
	 * @param pk_station
	 */
	public void setPk_station(String pk_station) {
		setAttribute(PK_STATION, pk_station);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取最后一次生成生成任务日期
	 * @return
	 */
	public String getLast_generate_date() {
		return getAttribute(LAST_GENERATE_DATE);
	}

	/**
	 * 设置最后一次生成生成任务日期
	 * @param last_generate_date
	 */
	public void setLast_generate_date(String last_generate_date) {
		setAttribute(LAST_GENERATE_DATE, last_generate_date);
	}

	/**
	 * 获取最后生成任务的完成期限
	 * @return
	 */
	public String getLast_deadline_date() {
		return getAttribute(LAST_DEADLINE_DATE);
	}

	/**
	 * 设置最后生成任务的完成期限
	 * @param last_deadline_date
	 */
	public void setLast_deadline_date(String last_deadline_date) {
		setAttribute(LAST_DEADLINE_DATE, last_deadline_date);
	}

	/**
	 * 获取标准加入岗位时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置标准加入岗位时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

}
