/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.energyloss.data.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 水表电表抄表实体类
 * 
 * @author zhi.zhang
 * @version since Shareworx platform 2.0
 */
public class YjwyEnergyDataModel extends DomainModel {

	private static final long serialVersionUID = 1L;
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_energy_data";
	
	/** ID  */
	public final static String ENERGY_DATA_ID = "energy_data_id";	
	/** 抄表值 */
	public final static String DATA = "data";	
	/** 水表、电表的值 */
	public final static String EQ_ID = "eq_id";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 地区，没有用到，占个位置 */
	public final static String AREA_NAME = "area_name";	
	/** 项目，没有用到，只是占位置 */
	public final static String PROJECT_NAME = "project_name";	
	/** 项目ID */
	public final static String PK_PROJECT = "pk_project";	

	public YjwyEnergyDataModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return ENERGY_DATA_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case ENERGY_DATA_ID:
			return "energy_data_id";
		case DATA:
			return "data";
		case EQ_ID:
			return "eq_id";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER:
			return "create_user";
		case PK_CROP:
			return "pk_crop";
		case AREA_NAME:
			return "area_name_";
		case PROJECT_NAME:
			return "project_name_";
		case PK_PROJECT:
			return "pk_project";
		}
		return null;
	}

	/**
	 * 获取ID 
	 * @return
	 */
	public String getEnergy_data_id() {
		return getAttribute(ENERGY_DATA_ID);
	}

	/**
	 * 设置ID 
	 * @param energy_data_id
	 */
	public void setEnergy_data_id(String energy_data_id) {
		setAttribute(ENERGY_DATA_ID, energy_data_id);
	}

	/**
	 * 获取抄表值
	 * @return
	 */
	public String getData() {
		return getAttribute(DATA);
	}

	/**
	 * 设置抄表值
	 * @param data
	 */
	public void setData(String data) {
		setAttribute(DATA, data);
	}

	/**
	 * 获取水表、电表的值
	 * @return
	 */
	public String getEq_id() {
		return getAttribute(EQ_ID);
	}

	/**
	 * 设置水表、电表的值
	 * @param eq_id
	 */
	public void setEq_id(String eq_id) {
		setAttribute(EQ_ID, eq_id);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取地区，没有用到，占个位置
	 * @return
	 */
	public String getArea_name() {
		return getAttribute(AREA_NAME);
	}

	/**
	 * 设置地区，没有用到，占个位置
	 * @param area_name
	 */
	public void setArea_name(String area_name) {
		setAttribute(AREA_NAME, area_name);
	}

	/**
	 * 获取项目，没有用到，只是占位置
	 * @return
	 */
	public String getProject_name() {
		return getAttribute(PROJECT_NAME);
	}

	/**
	 * 设置项目，没有用到，只是占位置
	 * @param project_name
	 */
	public void setProject_name(String project_name) {
		setAttribute(PROJECT_NAME, project_name);
	}

	/**
	 * 获取项目ID
	 * @return
	 */
	public String getPk_project() {
		return getAttribute(PK_PROJECT);
	}

	/**
	 * 设置项目ID
	 * @param pk_project
	 */
	public void setPk_project(String pk_project) {
		setAttribute(PK_PROJECT, pk_project);
	}

}
