/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.fmdata.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 房间位置信息实体类
 * 
 * @author lihui
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYRoomModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_fmdata_room";
	
	/** 房间编号（集团唯一位置编号） */
	public final static String RM_ID = "rm_id";	
	/** 位置编码（项目） */
	public final static String FM_CODE = "fm_code";	
	/** 位置描述 */
	public final static String NAME = "name";	
	/** 位置惯用名 */
	public final static String ALIAS = "alias";	
	/** 位置描述（房间长描述） */
	public final static String LONG_DESCRIPTION = "long_description";	
	/** 备注 */
	public final static String REMARK = "remark";	
	/** 项目编号 */
	public final static String SITE_ID = "site_id";	
	/** 更新时间 */
	public final static String DMS_UPDATE_TIME = "dms_update_time";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 是否有效 */
	public final static String FLAG = "flag";	
	/** 资源id */
	public final static String FK_RESOURCE_ID = "fk_resource_id";	

	public YJWYRoomModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return RM_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case RM_ID:
			return "rm_id";
		case FM_CODE:
			return "fm_code";
		case NAME:
			return "name";
		case ALIAS:
			return "alias";
		case LONG_DESCRIPTION:
			return "long_description";
		case REMARK:
			return "remark";
		case SITE_ID:
			return "site_id";
		case DMS_UPDATE_TIME:
			return "dms_update_time";
		case PK_CROP:
			return "pk_crop";
		case FLAG:
			return "flag";
		case FK_RESOURCE_ID:
			return "fk_resource_id_";
		}
		return null;
	}

	/**
	 * 获取房间编号（集团唯一位置编号）
	 * @return
	 */
	public String getRm_id() {
		return getAttribute(RM_ID);
	}

	/**
	 * 设置房间编号（集团唯一位置编号）
	 * @param rm_id
	 */
	public void setRm_id(String rm_id) {
		setAttribute(RM_ID, rm_id);
	}

	/**
	 * 获取位置编码（项目）
	 * @return
	 */
	public String getFm_code() {
		return getAttribute(FM_CODE);
	}

	/**
	 * 设置位置编码（项目）
	 * @param fm_code
	 */
	public void setFm_code(String fm_code) {
		setAttribute(FM_CODE, fm_code);
	}

	/**
	 * 获取位置描述
	 * @return
	 */
	public String getName() {
		return getAttribute(NAME);
	}

	/**
	 * 设置位置描述
	 * @param name
	 */
	public void setName(String name) {
		setAttribute(NAME, name);
	}

	/**
	 * 获取位置惯用名
	 * @return
	 */
	public String getAlias() {
		return getAttribute(ALIAS);
	}

	/**
	 * 设置位置惯用名
	 * @param alias
	 */
	public void setAlias(String alias) {
		setAttribute(ALIAS, alias);
	}

	/**
	 * 获取位置描述（房间长描述）
	 * @return
	 */
	public String getLong_description() {
		return getAttribute(LONG_DESCRIPTION);
	}

	/**
	 * 设置位置描述（房间长描述）
	 * @param long_description
	 */
	public void setLong_description(String long_description) {
		setAttribute(LONG_DESCRIPTION, long_description);
	}

	/**
	 * 获取备注
	 * @return
	 */
	public String getRemark() {
		return getAttribute(REMARK);
	}

	/**
	 * 设置备注
	 * @param remark
	 */
	public void setRemark(String remark) {
		setAttribute(REMARK, remark);
	}

	/**
	 * 获取项目编号
	 * @return
	 */
	public String getSite_id() {
		return getAttribute(SITE_ID);
	}

	/**
	 * 设置项目编号
	 * @param site_id
	 */
	public void setSite_id(String site_id) {
		setAttribute(SITE_ID, site_id);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getDms_update_time() {
		return getAttribute(DMS_UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param dms_update_time
	 */
	public void setDms_update_time(String dms_update_time) {
		setAttribute(DMS_UPDATE_TIME, dms_update_time);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取是否有效
	 * @return
	 */
	public Integer getFlag() {
		return getAttribute(FLAG);
	}

	/**
	 * 设置是否有效
	 * @param flag
	 */
	public void setFlag(Integer flag) {
		setAttribute(FLAG, flag);
	}

	/**
	 * 获取资源id
	 * @return
	 */
	public String getFk_resource_id() {
		return getAttribute(FK_RESOURCE_ID);
	}

	/**
	 * 设置资源id
	 * @param fk_resource_id
	 */
	public void setFk_resource_id(String fk_resource_id) {
		setAttribute(FK_RESOURCE_ID, fk_resource_id);
	}

}
