/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.fmdata.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 工艺程序步骤子表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYPmpsModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_fmdata_pmps";
	
	/** 程序id */
	public final static String PMP_ID = "pmp_id";	
	/** 程序步骤id */
	public final static String PMPS_ID = "pmps_id";	
	/** 步骤描述（名称） */
	public final static String INSTRUCTIONS = "instructions";	
	/** 操作类型 */
	public final static String OP_TYPE = "op_type";	
	/** 拍照标识 */
	public final static String PHOTOGRAPH = "photograph";	
	/** 扫码标识 */
	public final static String SCAN = "scan";	
	/** 步骤详情 */
	public final static String DETAIL_INSTRUCTIONS = "detail_instructions";	
	/** 最后更改时间 */
	public final static String DMS_UPDATE_TIME = "dms_update_time";	
	/** 有效标识 */
	public final static String FLAG = "flag";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYPmpsModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PMP_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PMP_ID:
			return "pmp_id";
		case PMPS_ID:
			return "pmps_id";
		case INSTRUCTIONS:
			return "instructions";
		case OP_TYPE:
			return "op_type";
		case PHOTOGRAPH:
			return "photograph";
		case SCAN:
			return "scan";
		case DETAIL_INSTRUCTIONS:
			return "detail_instructions";
		case DMS_UPDATE_TIME:
			return "dms_update_time";
		case FLAG:
			return "flag";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取程序id
	 * @return
	 */
	public Integer getPmp_id() {
		return getAttribute(PMP_ID);
	}

	/**
	 * 设置程序id
	 * @param pmp_id
	 */
	public void setPmp_id(Integer pmp_id) {
		setAttribute(PMP_ID, pmp_id);
	}

	/**
	 * 获取程序步骤id
	 * @return
	 */
	public Integer getPmps_id() {
		return getAttribute(PMPS_ID);
	}

	/**
	 * 设置程序步骤id
	 * @param pmps_id
	 */
	public void setPmps_id(Integer pmps_id) {
		setAttribute(PMPS_ID, pmps_id);
	}

	/**
	 * 获取步骤描述（名称）
	 * @return
	 */
	public String getInstructions() {
		return getAttribute(INSTRUCTIONS);
	}

	/**
	 * 设置步骤描述（名称）
	 * @param instructions
	 */
	public void setInstructions(String instructions) {
		setAttribute(INSTRUCTIONS, instructions);
	}

	/**
	 * 获取操作类型
	 * @return
	 */
	public String getOp_type() {
		return getAttribute(OP_TYPE);
	}

	/**
	 * 设置操作类型
	 * @param op_type
	 */
	public void setOp_type(String op_type) {
		setAttribute(OP_TYPE, op_type);
	}

	/**
	 * 获取拍照标识
	 * @return
	 */
	public String getPhotograph() {
		return getAttribute(PHOTOGRAPH);
	}

	/**
	 * 设置拍照标识
	 * @param photograph
	 */
	public void setPhotograph(String photograph) {
		setAttribute(PHOTOGRAPH, photograph);
	}

	/**
	 * 获取扫码标识
	 * @return
	 */
	public String getScan() {
		return getAttribute(SCAN);
	}

	/**
	 * 设置扫码标识
	 * @param scan
	 */
	public void setScan(String scan) {
		setAttribute(SCAN, scan);
	}

	/**
	 * 获取步骤详情
	 * @return
	 */
	public String getDetail_instructions() {
		return getAttribute(DETAIL_INSTRUCTIONS);
	}

	/**
	 * 设置步骤详情
	 * @param detail_instructions
	 */
	public void setDetail_instructions(String detail_instructions) {
		setAttribute(DETAIL_INSTRUCTIONS, detail_instructions);
	}

	/**
	 * 获取最后更改时间
	 * @return
	 */
	public String getDms_update_time() {
		return getAttribute(DMS_UPDATE_TIME);
	}

	/**
	 * 设置最后更改时间
	 * @param dms_update_time
	 */
	public void setDms_update_time(String dms_update_time) {
		setAttribute(DMS_UPDATE_TIME, dms_update_time);
	}

	/**
	 * 获取有效标识
	 * @return
	 */
	public Integer getFlag() {
		return getAttribute(FLAG);
	}

	/**
	 * 设置有效标识
	 * @param flag
	 */
	public void setFlag(Integer flag) {
		setAttribute(FLAG, flag);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
