/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.problem.record.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 报事记录实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYProblemRecordModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_problem_record";
	
	/** 主键ID */
	public final static String PK_RECORD_ID = "pk_record_id";	
	/** 报事详情ID */
	public final static String FK_DETAILS_ID = "fk_details_id";	
	/** 记录内容 */
	public final static String RECORD_CONTENT = "record_content";	
	/** 记录时间 */
	public final static String RECORD_TIME = "record_time";	
	/** 记录人ID */
	public final static String RECORD_USER_ID = "record_user_id";	
	/** 记录人姓名 */
	public final static String RECORD_USER_NAME = "record_user_name";	
	/** 跟进人ID */
	public final static String DUTY_USER_ID = "duty_user_id";	
	/** 跟进人姓名 */
	public final static String DUTY_USER_NAME = "duty_user_name";	
	/** 操作类型（字典） */
	public final static String OPERATE_TYPE = "operate_type";	
	/** 操作时状态（字典） */
	public final static String OPERATE_STATE = "operate_state";	
	/** 评价内容 */
	public final static String EVALUATE_CONTENT = "evaluate_content";	
	/** 评价类型 */
	public final static String EVALUATE_TYPE = "evaluate_type";	
	/** 服务态度 */
	public final static String ATTITUDE = "attitude";	
	/** 服务及时性 */
	public final static String QUALITY = "quality";	
	/** 服务机能 */
	public final static String EFFECT = "effect";	

	public YJWYProblemRecordModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_RECORD_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_RECORD_ID:
			return "pk_record_id";
		case FK_DETAILS_ID:
			return "fk_details_id";
		case RECORD_CONTENT:
			return "record_content";
		case RECORD_TIME:
			return "record_time";
		case RECORD_USER_ID:
			return "record_user_id";
		case RECORD_USER_NAME:
			return "record_user_name";
		case DUTY_USER_ID:
			return "duty_user_id";
		case DUTY_USER_NAME:
			return "duty_user_name";
		case OPERATE_TYPE:
			return "operate_type";
		case OPERATE_STATE:
			return "operate_state";
		case EVALUATE_CONTENT:
			return "evaluate_content";
		case EVALUATE_TYPE:
			return "evaluate_type";
		case ATTITUDE:
			return "attitude";
		case QUALITY:
			return "quality";
		case EFFECT:
			return "effect";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_record_id() {
		return getAttribute(PK_RECORD_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_record_id
	 */
	public void setPk_record_id(String pk_record_id) {
		setAttribute(PK_RECORD_ID, pk_record_id);
	}

	/**
	 * 获取报事详情ID
	 * @return
	 */
	public String getFk_details_id() {
		return getAttribute(FK_DETAILS_ID);
	}

	/**
	 * 设置报事详情ID
	 * @param fk_details_id
	 */
	public void setFk_details_id(String fk_details_id) {
		setAttribute(FK_DETAILS_ID, fk_details_id);
	}

	/**
	 * 获取记录内容
	 * @return
	 */
	public String getRecord_content() {
		return getAttribute(RECORD_CONTENT);
	}

	/**
	 * 设置记录内容
	 * @param record_content
	 */
	public void setRecord_content(String record_content) {
		setAttribute(RECORD_CONTENT, record_content);
	}

	/**
	 * 获取记录时间
	 * @return
	 */
	public String getRecord_time() {
		return getAttribute(RECORD_TIME);
	}

	/**
	 * 设置记录时间
	 * @param record_time
	 */
	public void setRecord_time(String record_time) {
		setAttribute(RECORD_TIME, record_time);
	}

	/**
	 * 获取记录人ID
	 * @return
	 */
	public String getRecord_user_id() {
		return getAttribute(RECORD_USER_ID);
	}

	/**
	 * 设置记录人ID
	 * @param record_user_id
	 */
	public void setRecord_user_id(String record_user_id) {
		setAttribute(RECORD_USER_ID, record_user_id);
	}

	/**
	 * 获取记录人姓名
	 * @return
	 */
	public String getRecord_user_name() {
		return getAttribute(RECORD_USER_NAME);
	}

	/**
	 * 设置记录人姓名
	 * @param record_user_name
	 */
	public void setRecord_user_name(String record_user_name) {
		setAttribute(RECORD_USER_NAME, record_user_name);
	}

	/**
	 * 获取跟进人ID
	 * @return
	 */
	public String getDuty_user_id() {
		return getAttribute(DUTY_USER_ID);
	}

	/**
	 * 设置跟进人ID
	 * @param duty_user_id
	 */
	public void setDuty_user_id(String duty_user_id) {
		setAttribute(DUTY_USER_ID, duty_user_id);
	}

	/**
	 * 获取跟进人姓名
	 * @return
	 */
	public String getDuty_user_name() {
		return getAttribute(DUTY_USER_NAME);
	}

	/**
	 * 设置跟进人姓名
	 * @param duty_user_name
	 */
	public void setDuty_user_name(String duty_user_name) {
		setAttribute(DUTY_USER_NAME, duty_user_name);
	}

	/**
	 * 获取操作类型（字典）
	 * @return
	 */
	public String getOperate_type() {
		return getAttribute(OPERATE_TYPE);
	}

	/**
	 * 设置操作类型（字典）
	 * @param operate_type
	 */
	public void setOperate_type(String operate_type) {
		setAttribute(OPERATE_TYPE, operate_type);
	}

	/**
	 * 获取操作时状态（字典）
	 * @return
	 */
	public Integer getOperate_state() {
		return getAttribute(OPERATE_STATE);
	}

	/**
	 * 设置操作时状态（字典）
	 * @param operate_state
	 */
	public void setOperate_state(Integer operate_state) {
		setAttribute(OPERATE_STATE, operate_state);
	}

	/**
	 * 获取评价内容
	 * @return
	 */
	public String getEvaluate_content() {
		return getAttribute(EVALUATE_CONTENT);
	}

	/**
	 * 设置评价内容
	 * @param evaluate_content
	 */
	public void setEvaluate_content(String evaluate_content) {
		setAttribute(EVALUATE_CONTENT, evaluate_content);
	}

	/**
	 * 获取评价类型
	 * @return
	 */
	public String getEvaluate_type() {
		return getAttribute(EVALUATE_TYPE);
	}

	/**
	 * 设置评价类型
	 * @param evaluate_type
	 */
	public void setEvaluate_type(String evaluate_type) {
		setAttribute(EVALUATE_TYPE, evaluate_type);
	}

	/**
	 * 获取服务态度
	 * @return
	 */
	public Integer getAttitude() {
		return getAttribute(ATTITUDE);
	}

	/**
	 * 设置服务态度
	 * @param attitude
	 */
	public void setAttitude(Integer attitude) {
		setAttribute(ATTITUDE, attitude);
	}

	/**
	 * 获取服务及时性
	 * @return
	 */
	public Integer getQuality() {
		return getAttribute(QUALITY);
	}

	/**
	 * 设置服务及时性
	 * @param quality
	 */
	public void setQuality(Integer quality) {
		setAttribute(QUALITY, quality);
	}

	/**
	 * 获取服务机能
	 * @return
	 */
	public Integer getEffect() {
		return getAttribute(EFFECT);
	}

	/**
	 * 设置服务机能
	 * @param effect
	 */
	public void setEffect(Integer effect) {
		setAttribute(EFFECT, effect);
	}

}
