/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.resources.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 资源属性表实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYResourcesAttributeModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_resource_attribute";
	
	/** 主键 */
	public final static String ID = "id";	
	/** 资源ID */
	public final static String PK_RESOURCES = "pk_resources";	
	/** 交楼时间 */
	public final static String PAY_FLOOR_TIME = "pay_floor_time";	
	/** 建筑面积 */
	public final static String DUILDE_AREA = "duilde_area";	
	/** 绿化面积 */
	public final static String GREEN_AREA = "green_area";	
	/** 花园面积 */
	public final static String GARDEN_AREA = "garden_area";	
	/** 楼顶绿化面积 */
	public final static String TOPFLOOR_GREEN_AREA = "topfloor_green_area";	
	/** 地下车库面积 */
	public final static String UNDERGROUND_GARAGE_AREA = "underground_garage_area";	
	/** 停车房面积 */
	public final static String PRAKING_ROOM_AREA = "praking_room_area";	
	/** 预售许可证日期 */
	public final static String SELL_PERMIT_TIME = "sell_permit_time";	
	/** 地下楼层 */
	public final static String BASEMENT_FLOOR = "basement_floor";	
	/** 总层数 */
	public final static String PLIES_MUNBER = "plies_munber";	
	/** 预约交房日期 */
	public final static String BESPEAK_HOUSE_TIME = "bespeak_house_time";	
	/** 品类 */
	public final static String CATEGORY = "category";	
	/** 辅助楼栋编码 */
	public final static String AUXILIARY_BAN_CODE = "auxiliary_ban_code";	
	/** 项目编码 */
	public final static String PROJECT_CODE = "project_code";	
	/** 分期编码 */
	public final static String STAGES_CODE = "stages_code";	
	/** 楼栋名称 */
	public final static String BAN_NAME = "ban_name";	
	/** 楼栋简称 */
	public final static String BAN_ABBREVIATION = "ban_abbreviation";	
	/** 建筑类型 */
	public final static String BUILDE_TYPE = "builde_type";	
	/** 销售装修类型 */
	public final static String SALE_RENOVATION_TYPE = "sale_renovation_type";	
	/** 楼高 */
	public final static String BUILDE_HIGHT = "builde_hight";	
	/** 地上楼层 */
	public final static String ONGROUND_LOOR = "onground_loor";	
	/** 夹层 */
	public final static String INTERLAYER = "interlayer";	
	/** 预售许可证 */
	public final static String BESPEAK_SELL_PERMIT = "bespeak_sell_permit";	
	/** 单元数 */
	public final static String UNIT_MNUMBER = "unit_mnumber";	
	/** 竣工时间 */
	public final static String COMPLETE_TIME = "complete_time";	
	/** 物业形态 */
	public final static String PROPERTY_SHAPE = "property_shape";	
	/** 室内面积 */
	public final static String INDOOR_AREA = "indoor_area";	
	/** 是否虚拟空间 */
	public final static String IS_VIRTUAL_SPACE = "is_virtual_space";	
	/** 房屋简称 */
	public final static String HOUSE_ABBREVIATION = "house_abbreviation";	
	/** 房屋编码 */
	public final static String HOUSE_CODE = "house_code";	
	/** 属于那个单元（房间） */
	public final static String UNIT = "unit";	
	/** 属于多少楼层（房间） */
	public final static String FLOOR = "floor";	
	/** 露台面积 */
	public final static String TERRACE_AREA = "terrace_area";	
	/** 预售建筑面积 */
	public final static String PRESELL_BUILDE_AREA = "presell_builde_area";	
	/** 预售套内面积 */
	public final static String PRESELL_SETIN_AREA = "presell_setin_area";	
	/** 实测建筑面积 */
	public final static String FACT_BUILDE_AREA = "fact_builde_area";	
	/** 实测套内面积 */
	public final static String FACT_SETIN_AREA = "fact_setin_area";	
	/** 实测公摊面积 */
	public final static String FACT_POOL_AREA = "fact_pool_area";	
	/** 实测地下室面积 */
	public final static String FACT_BASEMENT_AREA = "fact_basement_area";	
	/** 交楼面积 */
	public final static String PAY_FLOOR_AREA = "pay_floor_area";	
	/** 入住日期 */
	public final static String CHECK_DATA = "check_data";	
	/** 入伙计费日期 */
	public final static String OCCUPATION_CHARGING_DATA = "occupation_charging_data";	
	/** 办理装修日期 */
	public final static String HANDLE_DECORATION_DATA = "handle_decoration_data";	
	/** 装修竣工日期 */
	public final static String DECORATION_COMPLETE_DATA = "decoration_complete_data";	
	/** 房屋号 */
	public final static String ROOM_NUMBER = "room_number";	
	/** 房屋面积 */
	public final static String HOUSE_AREA = "house_area";	
	/** 套内面积 */
	public final static String SETIN_AREA = "setin_area";	
	/** 公摊面积 */
	public final static String POOL_AREA = "pool_area";	
	/** 地下室面积 */
	public final static String BASEMENT_AREA = "basement_area";	
	/** 车库面积 */
	public final static String GARAGE_AREA = "garage_area";	
	/** 层高 */
	public final static String FLOOR_HIGHT = "floor_hight";	
	/** 房屋类别 */
	public final static String HOUSE_CATEGORY = "house_category";	
	/** 是否二手房 */
	public final static String IS_SECOND_HAND_HOUSE = "is_second_hand_house";	
	/** 朝向 */
	public final static String ORIENTATION = "orientation";	
	/** 户型 */
	public final static String APARTMENT_LAYOUT = "apartment_layout";	
	/** 产权类型 */
	public final static String PROPERTY_TYPE = "property_type";	
	/** 单元别名 */
	public final static String UNIT_ALIAS = "unit_alias";	
	/** 楼层别名 */
	public final static String FLOOR_ALIAS = "floor_alias";	
	/** 房号别名 */
	public final static String ROOM_NUMBER_ALIAS = "room_number_alias";	
	/** 物业面积 */
	public final static String PROPERTY_AREA = "property_area";	
	/** 销售装修单价 */
	public final static String SALE_BUILDER_PRICE = "sale_builder_price";	
	/** 街道长度 */
	public final static String STREET_LENGTH = "street_length";	
	/** 工位数 */
	public final static String STATION_NUMBER = "station_number";	

	public YJWYResourcesAttributeModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case ID:
			return "id_";
		case PK_RESOURCES:
			return "pk_resources_";
		case PAY_FLOOR_TIME:
			return "pay_floor_time";
		case DUILDE_AREA:
			return "duilde_area_";
		case GREEN_AREA:
			return "green_area_";
		case GARDEN_AREA:
			return "garden_area_";
		case TOPFLOOR_GREEN_AREA:
			return "topfloor_green_area_";
		case UNDERGROUND_GARAGE_AREA:
			return "underground_garage_area_";
		case PRAKING_ROOM_AREA:
			return "praking_room_area_";
		case SELL_PERMIT_TIME:
			return "sell_permit_time_";
		case BASEMENT_FLOOR:
			return "basement_floor_";
		case PLIES_MUNBER:
			return "plies_munber_";
		case BESPEAK_HOUSE_TIME:
			return "bespeak_house_time_";
		case CATEGORY:
			return "category_";
		case AUXILIARY_BAN_CODE:
			return "auxiliary_ban_code_";
		case PROJECT_CODE:
			return "project_code_";
		case STAGES_CODE:
			return "stages_code_";
		case BAN_NAME:
			return "ban_name_";
		case BAN_ABBREVIATION:
			return "ban_abbreviation_";
		case BUILDE_TYPE:
			return "builde_type_";
		case SALE_RENOVATION_TYPE:
			return "sale_renovation_type_";
		case BUILDE_HIGHT:
			return "builde_hight_";
		case ONGROUND_LOOR:
			return "onground_loor_";
		case INTERLAYER:
			return "interlayer_";
		case BESPEAK_SELL_PERMIT:
			return "bespeak_sell_permit_";
		case UNIT_MNUMBER:
			return "unit_mnumber_";
		case COMPLETE_TIME:
			return "complete_time_";
		case PROPERTY_SHAPE:
			return "property_shape_";
		case INDOOR_AREA:
			return "indoor_area_";
		case IS_VIRTUAL_SPACE:
			return "is_virtual_space_";
		case HOUSE_ABBREVIATION:
			return "house_abbreviation_";
		case HOUSE_CODE:
			return "house_code_";
		case UNIT:
			return "unit_";
		case FLOOR:
			return "floor_";
		case TERRACE_AREA:
			return "terrace_area_";
		case PRESELL_BUILDE_AREA:
			return "presell_builde_area_";
		case PRESELL_SETIN_AREA:
			return "presell_setin_area_";
		case FACT_BUILDE_AREA:
			return "fact_builde_area_";
		case FACT_SETIN_AREA:
			return "fact_setin_area_";
		case FACT_POOL_AREA:
			return "fact_pool_area_";
		case FACT_BASEMENT_AREA:
			return "fact_basement_area_";
		case PAY_FLOOR_AREA:
			return "pay_floor_area_";
		case CHECK_DATA:
			return "check_data_";
		case OCCUPATION_CHARGING_DATA:
			return "occupation_charging_data_";
		case HANDLE_DECORATION_DATA:
			return "handle_decoration_data_";
		case DECORATION_COMPLETE_DATA:
			return "decoration_complete_data_";
		case ROOM_NUMBER:
			return "room_number_";
		case HOUSE_AREA:
			return "house_area_";
		case SETIN_AREA:
			return "setin_area_";
		case POOL_AREA:
			return "pool_area_";
		case BASEMENT_AREA:
			return "basement_area_";
		case GARAGE_AREA:
			return "garage_area_";
		case FLOOR_HIGHT:
			return "floor_hight_";
		case HOUSE_CATEGORY:
			return "house_category_";
		case IS_SECOND_HAND_HOUSE:
			return "is_second_hand_house_";
		case ORIENTATION:
			return "orientation_";
		case APARTMENT_LAYOUT:
			return "apartment_layout_";
		case PROPERTY_TYPE:
			return "property_type_";
		case UNIT_ALIAS:
			return "unit_alias_";
		case FLOOR_ALIAS:
			return "floor_alias_";
		case ROOM_NUMBER_ALIAS:
			return "room_number_alias_";
		case PROPERTY_AREA:
			return "property_area_";
		case SALE_BUILDER_PRICE:
			return "sale_builder_price_";
		case STREET_LENGTH:
			return "street_length_";
		case STATION_NUMBER:
			return "station_number_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getId() {
		return getAttribute(ID);
	}

	/**
	 * 设置主键
	 * @param id
	 */
	public void setId(String id) {
		setAttribute(ID, id);
	}

	/**
	 * 获取资源ID
	 * @return
	 */
	public String getPk_resources() {
		return getAttribute(PK_RESOURCES);
	}

	/**
	 * 设置资源ID
	 * @param pk_resources
	 */
	public void setPk_resources(String pk_resources) {
		setAttribute(PK_RESOURCES, pk_resources);
	}

	/**
	 * 获取交楼时间
	 * @return
	 */
	public String getPay_floor_time() {
		return getAttribute(PAY_FLOOR_TIME);
	}

	/**
	 * 设置交楼时间
	 * @param pay_floor_time
	 */
	public void setPay_floor_time(String pay_floor_time) {
		setAttribute(PAY_FLOOR_TIME, pay_floor_time);
	}

	/**
	 * 获取建筑面积
	 * @return
	 */
	public String getDuilde_area() {
		return getAttribute(DUILDE_AREA);
	}

	/**
	 * 设置建筑面积
	 * @param duilde_area
	 */
	public void setDuilde_area(String duilde_area) {
		setAttribute(DUILDE_AREA, duilde_area);
	}

	/**
	 * 获取绿化面积
	 * @return
	 */
	public String getGreen_area() {
		return getAttribute(GREEN_AREA);
	}

	/**
	 * 设置绿化面积
	 * @param green_area
	 */
	public void setGreen_area(String green_area) {
		setAttribute(GREEN_AREA, green_area);
	}

	/**
	 * 获取花园面积
	 * @return
	 */
	public String getGarden_area() {
		return getAttribute(GARDEN_AREA);
	}

	/**
	 * 设置花园面积
	 * @param garden_area
	 */
	public void setGarden_area(String garden_area) {
		setAttribute(GARDEN_AREA, garden_area);
	}

	/**
	 * 获取楼顶绿化面积
	 * @return
	 */
	public String getTopfloor_green_area() {
		return getAttribute(TOPFLOOR_GREEN_AREA);
	}

	/**
	 * 设置楼顶绿化面积
	 * @param topfloor_green_area
	 */
	public void setTopfloor_green_area(String topfloor_green_area) {
		setAttribute(TOPFLOOR_GREEN_AREA, topfloor_green_area);
	}

	/**
	 * 获取地下车库面积
	 * @return
	 */
	public String getUnderground_garage_area() {
		return getAttribute(UNDERGROUND_GARAGE_AREA);
	}

	/**
	 * 设置地下车库面积
	 * @param underground_garage_area
	 */
	public void setUnderground_garage_area(String underground_garage_area) {
		setAttribute(UNDERGROUND_GARAGE_AREA, underground_garage_area);
	}

	/**
	 * 获取停车房面积
	 * @return
	 */
	public String getPraking_room_area() {
		return getAttribute(PRAKING_ROOM_AREA);
	}

	/**
	 * 设置停车房面积
	 * @param praking_room_area
	 */
	public void setPraking_room_area(String praking_room_area) {
		setAttribute(PRAKING_ROOM_AREA, praking_room_area);
	}

	/**
	 * 获取预售许可证日期
	 * @return
	 */
	public String getSell_permit_time() {
		return getAttribute(SELL_PERMIT_TIME);
	}

	/**
	 * 设置预售许可证日期
	 * @param sell_permit_time
	 */
	public void setSell_permit_time(String sell_permit_time) {
		setAttribute(SELL_PERMIT_TIME, sell_permit_time);
	}

	/**
	 * 获取地下楼层
	 * @return
	 */
	public String getBasement_floor() {
		return getAttribute(BASEMENT_FLOOR);
	}

	/**
	 * 设置地下楼层
	 * @param basement_floor
	 */
	public void setBasement_floor(String basement_floor) {
		setAttribute(BASEMENT_FLOOR, basement_floor);
	}

	/**
	 * 获取总层数
	 * @return
	 */
	public String getPlies_munber() {
		return getAttribute(PLIES_MUNBER);
	}

	/**
	 * 设置总层数
	 * @param plies_munber
	 */
	public void setPlies_munber(String plies_munber) {
		setAttribute(PLIES_MUNBER, plies_munber);
	}

	/**
	 * 获取预约交房日期
	 * @return
	 */
	public String getBespeak_house_time() {
		return getAttribute(BESPEAK_HOUSE_TIME);
	}

	/**
	 * 设置预约交房日期
	 * @param bespeak_house_time
	 */
	public void setBespeak_house_time(String bespeak_house_time) {
		setAttribute(BESPEAK_HOUSE_TIME, bespeak_house_time);
	}

	/**
	 * 获取品类
	 * @return
	 */
	public String getCategory() {
		return getAttribute(CATEGORY);
	}

	/**
	 * 设置品类
	 * @param category
	 */
	public void setCategory(String category) {
		setAttribute(CATEGORY, category);
	}

	/**
	 * 获取辅助楼栋编码
	 * @return
	 */
	public String getAuxiliary_ban_code() {
		return getAttribute(AUXILIARY_BAN_CODE);
	}

	/**
	 * 设置辅助楼栋编码
	 * @param auxiliary_ban_code
	 */
	public void setAuxiliary_ban_code(String auxiliary_ban_code) {
		setAttribute(AUXILIARY_BAN_CODE, auxiliary_ban_code);
	}

	/**
	 * 获取项目编码
	 * @return
	 */
	public String getProject_code() {
		return getAttribute(PROJECT_CODE);
	}

	/**
	 * 设置项目编码
	 * @param project_code
	 */
	public void setProject_code(String project_code) {
		setAttribute(PROJECT_CODE, project_code);
	}

	/**
	 * 获取分期编码
	 * @return
	 */
	public String getStages_code() {
		return getAttribute(STAGES_CODE);
	}

	/**
	 * 设置分期编码
	 * @param stages_code
	 */
	public void setStages_code(String stages_code) {
		setAttribute(STAGES_CODE, stages_code);
	}

	/**
	 * 获取楼栋名称
	 * @return
	 */
	public String getBan_name() {
		return getAttribute(BAN_NAME);
	}

	/**
	 * 设置楼栋名称
	 * @param ban_name
	 */
	public void setBan_name(String ban_name) {
		setAttribute(BAN_NAME, ban_name);
	}

	/**
	 * 获取楼栋简称
	 * @return
	 */
	public String getBan_abbreviation() {
		return getAttribute(BAN_ABBREVIATION);
	}

	/**
	 * 设置楼栋简称
	 * @param ban_abbreviation
	 */
	public void setBan_abbreviation(String ban_abbreviation) {
		setAttribute(BAN_ABBREVIATION, ban_abbreviation);
	}

	/**
	 * 获取建筑类型
	 * @return
	 */
	public String getBuilde_type() {
		return getAttribute(BUILDE_TYPE);
	}

	/**
	 * 设置建筑类型
	 * @param builde_type
	 */
	public void setBuilde_type(String builde_type) {
		setAttribute(BUILDE_TYPE, builde_type);
	}

	/**
	 * 获取销售装修类型
	 * @return
	 */
	public String getSale_renovation_type() {
		return getAttribute(SALE_RENOVATION_TYPE);
	}

	/**
	 * 设置销售装修类型
	 * @param sale_renovation_type
	 */
	public void setSale_renovation_type(String sale_renovation_type) {
		setAttribute(SALE_RENOVATION_TYPE, sale_renovation_type);
	}

	/**
	 * 获取楼高
	 * @return
	 */
	public String getBuilde_hight() {
		return getAttribute(BUILDE_HIGHT);
	}

	/**
	 * 设置楼高
	 * @param builde_hight
	 */
	public void setBuilde_hight(String builde_hight) {
		setAttribute(BUILDE_HIGHT, builde_hight);
	}

	/**
	 * 获取地上楼层
	 * @return
	 */
	public String getOnground_loor() {
		return getAttribute(ONGROUND_LOOR);
	}

	/**
	 * 设置地上楼层
	 * @param onground_loor
	 */
	public void setOnground_loor(String onground_loor) {
		setAttribute(ONGROUND_LOOR, onground_loor);
	}

	/**
	 * 获取夹层
	 * @return
	 */
	public String getInterlayer() {
		return getAttribute(INTERLAYER);
	}

	/**
	 * 设置夹层
	 * @param interlayer
	 */
	public void setInterlayer(String interlayer) {
		setAttribute(INTERLAYER, interlayer);
	}

	/**
	 * 获取预售许可证
	 * @return
	 */
	public String getBespeak_sell_permit() {
		return getAttribute(BESPEAK_SELL_PERMIT);
	}

	/**
	 * 设置预售许可证
	 * @param bespeak_sell_permit
	 */
	public void setBespeak_sell_permit(String bespeak_sell_permit) {
		setAttribute(BESPEAK_SELL_PERMIT, bespeak_sell_permit);
	}

	/**
	 * 获取单元数
	 * @return
	 */
	public String getUnit_mnumber() {
		return getAttribute(UNIT_MNUMBER);
	}

	/**
	 * 设置单元数
	 * @param unit_mnumber
	 */
	public void setUnit_mnumber(String unit_mnumber) {
		setAttribute(UNIT_MNUMBER, unit_mnumber);
	}

	/**
	 * 获取竣工时间
	 * @return
	 */
	public String getComplete_time() {
		return getAttribute(COMPLETE_TIME);
	}

	/**
	 * 设置竣工时间
	 * @param complete_time
	 */
	public void setComplete_time(String complete_time) {
		setAttribute(COMPLETE_TIME, complete_time);
	}

	/**
	 * 获取物业形态
	 * @return
	 */
	public String getProperty_shape() {
		return getAttribute(PROPERTY_SHAPE);
	}

	/**
	 * 设置物业形态
	 * @param property_shape
	 */
	public void setProperty_shape(String property_shape) {
		setAttribute(PROPERTY_SHAPE, property_shape);
	}

	/**
	 * 获取室内面积
	 * @return
	 */
	public String getIndoor_area() {
		return getAttribute(INDOOR_AREA);
	}

	/**
	 * 设置室内面积
	 * @param indoor_area
	 */
	public void setIndoor_area(String indoor_area) {
		setAttribute(INDOOR_AREA, indoor_area);
	}

	/**
	 * 获取是否虚拟空间
	 * @return
	 */
	public String getIs_virtual_space() {
		return getAttribute(IS_VIRTUAL_SPACE);
	}

	/**
	 * 设置是否虚拟空间
	 * @param is_virtual_space
	 */
	public void setIs_virtual_space(String is_virtual_space) {
		setAttribute(IS_VIRTUAL_SPACE, is_virtual_space);
	}

	/**
	 * 获取房屋简称
	 * @return
	 */
	public String getHouse_abbreviation() {
		return getAttribute(HOUSE_ABBREVIATION);
	}

	/**
	 * 设置房屋简称
	 * @param house_abbreviation
	 */
	public void setHouse_abbreviation(String house_abbreviation) {
		setAttribute(HOUSE_ABBREVIATION, house_abbreviation);
	}

	/**
	 * 获取房屋编码
	 * @return
	 */
	public String getHouse_code() {
		return getAttribute(HOUSE_CODE);
	}

	/**
	 * 设置房屋编码
	 * @param house_code
	 */
	public void setHouse_code(String house_code) {
		setAttribute(HOUSE_CODE, house_code);
	}

	/**
	 * 获取属于那个单元（房间）
	 * @return
	 */
	public String getUnit() {
		return getAttribute(UNIT);
	}

	/**
	 * 设置属于那个单元（房间）
	 * @param unit
	 */
	public void setUnit(String unit) {
		setAttribute(UNIT, unit);
	}

	/**
	 * 获取属于多少楼层（房间）
	 * @return
	 */
	public String getFloor() {
		return getAttribute(FLOOR);
	}

	/**
	 * 设置属于多少楼层（房间）
	 * @param floor
	 */
	public void setFloor(String floor) {
		setAttribute(FLOOR, floor);
	}

	/**
	 * 获取露台面积
	 * @return
	 */
	public String getTerrace_area() {
		return getAttribute(TERRACE_AREA);
	}

	/**
	 * 设置露台面积
	 * @param terrace_area
	 */
	public void setTerrace_area(String terrace_area) {
		setAttribute(TERRACE_AREA, terrace_area);
	}

	/**
	 * 获取预售建筑面积
	 * @return
	 */
	public String getPresell_builde_area() {
		return getAttribute(PRESELL_BUILDE_AREA);
	}

	/**
	 * 设置预售建筑面积
	 * @param presell_builde_area
	 */
	public void setPresell_builde_area(String presell_builde_area) {
		setAttribute(PRESELL_BUILDE_AREA, presell_builde_area);
	}

	/**
	 * 获取预售套内面积
	 * @return
	 */
	public String getPresell_setin_area() {
		return getAttribute(PRESELL_SETIN_AREA);
	}

	/**
	 * 设置预售套内面积
	 * @param presell_setin_area
	 */
	public void setPresell_setin_area(String presell_setin_area) {
		setAttribute(PRESELL_SETIN_AREA, presell_setin_area);
	}

	/**
	 * 获取实测建筑面积
	 * @return
	 */
	public String getFact_builde_area() {
		return getAttribute(FACT_BUILDE_AREA);
	}

	/**
	 * 设置实测建筑面积
	 * @param fact_builde_area
	 */
	public void setFact_builde_area(String fact_builde_area) {
		setAttribute(FACT_BUILDE_AREA, fact_builde_area);
	}

	/**
	 * 获取实测套内面积
	 * @return
	 */
	public String getFact_setin_area() {
		return getAttribute(FACT_SETIN_AREA);
	}

	/**
	 * 设置实测套内面积
	 * @param fact_setin_area
	 */
	public void setFact_setin_area(String fact_setin_area) {
		setAttribute(FACT_SETIN_AREA, fact_setin_area);
	}

	/**
	 * 获取实测公摊面积
	 * @return
	 */
	public String getFact_pool_area() {
		return getAttribute(FACT_POOL_AREA);
	}

	/**
	 * 设置实测公摊面积
	 * @param fact_pool_area
	 */
	public void setFact_pool_area(String fact_pool_area) {
		setAttribute(FACT_POOL_AREA, fact_pool_area);
	}

	/**
	 * 获取实测地下室面积
	 * @return
	 */
	public String getFact_basement_area() {
		return getAttribute(FACT_BASEMENT_AREA);
	}

	/**
	 * 设置实测地下室面积
	 * @param fact_basement_area
	 */
	public void setFact_basement_area(String fact_basement_area) {
		setAttribute(FACT_BASEMENT_AREA, fact_basement_area);
	}

	/**
	 * 获取交楼面积
	 * @return
	 */
	public String getPay_floor_area() {
		return getAttribute(PAY_FLOOR_AREA);
	}

	/**
	 * 设置交楼面积
	 * @param pay_floor_area
	 */
	public void setPay_floor_area(String pay_floor_area) {
		setAttribute(PAY_FLOOR_AREA, pay_floor_area);
	}

	/**
	 * 获取入住日期
	 * @return
	 */
	public String getCheck_data() {
		return getAttribute(CHECK_DATA);
	}

	/**
	 * 设置入住日期
	 * @param check_data
	 */
	public void setCheck_data(String check_data) {
		setAttribute(CHECK_DATA, check_data);
	}

	/**
	 * 获取入伙计费日期
	 * @return
	 */
	public String getOccupation_charging_data() {
		return getAttribute(OCCUPATION_CHARGING_DATA);
	}

	/**
	 * 设置入伙计费日期
	 * @param occupation_charging_data
	 */
	public void setOccupation_charging_data(String occupation_charging_data) {
		setAttribute(OCCUPATION_CHARGING_DATA, occupation_charging_data);
	}

	/**
	 * 获取办理装修日期
	 * @return
	 */
	public String getHandle_decoration_data() {
		return getAttribute(HANDLE_DECORATION_DATA);
	}

	/**
	 * 设置办理装修日期
	 * @param handle_decoration_data
	 */
	public void setHandle_decoration_data(String handle_decoration_data) {
		setAttribute(HANDLE_DECORATION_DATA, handle_decoration_data);
	}

	/**
	 * 获取装修竣工日期
	 * @return
	 */
	public String getDecoration_complete_data() {
		return getAttribute(DECORATION_COMPLETE_DATA);
	}

	/**
	 * 设置装修竣工日期
	 * @param decoration_complete_data
	 */
	public void setDecoration_complete_data(String decoration_complete_data) {
		setAttribute(DECORATION_COMPLETE_DATA, decoration_complete_data);
	}

	/**
	 * 获取房屋号
	 * @return
	 */
	public String getRoom_number() {
		return getAttribute(ROOM_NUMBER);
	}

	/**
	 * 设置房屋号
	 * @param room_number
	 */
	public void setRoom_number(String room_number) {
		setAttribute(ROOM_NUMBER, room_number);
	}

	/**
	 * 获取房屋面积
	 * @return
	 */
	public String getHouse_area() {
		return getAttribute(HOUSE_AREA);
	}

	/**
	 * 设置房屋面积
	 * @param house_area
	 */
	public void setHouse_area(String house_area) {
		setAttribute(HOUSE_AREA, house_area);
	}

	/**
	 * 获取套内面积
	 * @return
	 */
	public String getSetin_area() {
		return getAttribute(SETIN_AREA);
	}

	/**
	 * 设置套内面积
	 * @param setin_area
	 */
	public void setSetin_area(String setin_area) {
		setAttribute(SETIN_AREA, setin_area);
	}

	/**
	 * 获取公摊面积
	 * @return
	 */
	public String getPool_area() {
		return getAttribute(POOL_AREA);
	}

	/**
	 * 设置公摊面积
	 * @param pool_area
	 */
	public void setPool_area(String pool_area) {
		setAttribute(POOL_AREA, pool_area);
	}

	/**
	 * 获取地下室面积
	 * @return
	 */
	public String getBasement_area() {
		return getAttribute(BASEMENT_AREA);
	}

	/**
	 * 设置地下室面积
	 * @param basement_area
	 */
	public void setBasement_area(String basement_area) {
		setAttribute(BASEMENT_AREA, basement_area);
	}

	/**
	 * 获取车库面积
	 * @return
	 */
	public String getGarage_area() {
		return getAttribute(GARAGE_AREA);
	}

	/**
	 * 设置车库面积
	 * @param garage_area
	 */
	public void setGarage_area(String garage_area) {
		setAttribute(GARAGE_AREA, garage_area);
	}

	/**
	 * 获取层高
	 * @return
	 */
	public String getFloor_hight() {
		return getAttribute(FLOOR_HIGHT);
	}

	/**
	 * 设置层高
	 * @param floor_hight
	 */
	public void setFloor_hight(String floor_hight) {
		setAttribute(FLOOR_HIGHT, floor_hight);
	}

	/**
	 * 获取房屋类别
	 * @return
	 */
	public String getHouse_category() {
		return getAttribute(HOUSE_CATEGORY);
	}

	/**
	 * 设置房屋类别
	 * @param house_category
	 */
	public void setHouse_category(String house_category) {
		setAttribute(HOUSE_CATEGORY, house_category);
	}

	/**
	 * 获取是否二手房
	 * @return
	 */
	public String getIs_second_hand_house() {
		return getAttribute(IS_SECOND_HAND_HOUSE);
	}

	/**
	 * 设置是否二手房
	 * @param is_second_hand_house
	 */
	public void setIs_second_hand_house(String is_second_hand_house) {
		setAttribute(IS_SECOND_HAND_HOUSE, is_second_hand_house);
	}

	/**
	 * 获取朝向
	 * @return
	 */
	public String getOrientation() {
		return getAttribute(ORIENTATION);
	}

	/**
	 * 设置朝向
	 * @param orientation
	 */
	public void setOrientation(String orientation) {
		setAttribute(ORIENTATION, orientation);
	}

	/**
	 * 获取户型
	 * @return
	 */
	public String getApartment_layout() {
		return getAttribute(APARTMENT_LAYOUT);
	}

	/**
	 * 设置户型
	 * @param apartment_layout
	 */
	public void setApartment_layout(String apartment_layout) {
		setAttribute(APARTMENT_LAYOUT, apartment_layout);
	}

	/**
	 * 获取产权类型
	 * @return
	 */
	public String getProperty_type() {
		return getAttribute(PROPERTY_TYPE);
	}

	/**
	 * 设置产权类型
	 * @param property_type
	 */
	public void setProperty_type(String property_type) {
		setAttribute(PROPERTY_TYPE, property_type);
	}

	/**
	 * 获取单元别名
	 * @return
	 */
	public String getUnit_alias() {
		return getAttribute(UNIT_ALIAS);
	}

	/**
	 * 设置单元别名
	 * @param unit_alias
	 */
	public void setUnit_alias(String unit_alias) {
		setAttribute(UNIT_ALIAS, unit_alias);
	}

	/**
	 * 获取楼层别名
	 * @return
	 */
	public String getFloor_alias() {
		return getAttribute(FLOOR_ALIAS);
	}

	/**
	 * 设置楼层别名
	 * @param floor_alias
	 */
	public void setFloor_alias(String floor_alias) {
		setAttribute(FLOOR_ALIAS, floor_alias);
	}

	/**
	 * 获取房号别名
	 * @return
	 */
	public String getRoom_number_alias() {
		return getAttribute(ROOM_NUMBER_ALIAS);
	}

	/**
	 * 设置房号别名
	 * @param room_number_alias
	 */
	public void setRoom_number_alias(String room_number_alias) {
		setAttribute(ROOM_NUMBER_ALIAS, room_number_alias);
	}

	/**
	 * 获取物业面积
	 * @return
	 */
	public String getProperty_area() {
		return getAttribute(PROPERTY_AREA);
	}

	/**
	 * 设置物业面积
	 * @param property_area
	 */
	public void setProperty_area(String property_area) {
		setAttribute(PROPERTY_AREA, property_area);
	}

	/**
	 * 获取销售装修单价
	 * @return
	 */
	public String getSale_builder_price() {
		return getAttribute(SALE_BUILDER_PRICE);
	}

	/**
	 * 设置销售装修单价
	 * @param sale_builder_price
	 */
	public void setSale_builder_price(String sale_builder_price) {
		setAttribute(SALE_BUILDER_PRICE, sale_builder_price);
	}

	/**
	 * 获取街道长度
	 * @return
	 */
	public String getStreet_length() {
		return getAttribute(STREET_LENGTH);
	}

	/**
	 * 设置街道长度
	 * @param street_length
	 */
	public void setStreet_length(String street_length) {
		setAttribute(STREET_LENGTH, street_length);
	}

	/**
	 * 获取工位数
	 * @return
	 */
	public String getStation_number() {
		return getAttribute(STATION_NUMBER);
	}

	/**
	 * 设置工位数
	 * @param station_number
	 */
	public void setStation_number(String station_number) {
		setAttribute(STATION_NUMBER, station_number);
	}

}
