/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.type.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 资源类型实体类
 *
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class ResourcetypeModel extends DomainModel {

	/**
	 * 元数据名称
	 */
	public final static String META_ID = "resource_type";

	/** 主键 */
	public final static String TYPE_ID = "type_id";
	/** 资源类型名称 */
	public final static String TYPE_NAME = "type_name";
	/** 资源父id */
	public final static String TYPE_PID = "type_pid";
	/** 创建人 */
	public final static String TYPE_UPNAME = "type_upname";
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";
	/** 创建时间 */
	public final static String TYPE_TIME = "type_time";
	/** 资源类型编码 */
	public final static String TYPE_CODE = "type_code";
	/** 新属性 */
	public final static String TYPE_FLAG = "type_flag";

	public ResourcetypeModel() {
		super(META_ID);
	}

	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}

	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return TYPE_ID;
	}

	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
			case TYPE_ID:
				return "type_id_";
			case TYPE_NAME:
				return "type_name_";
			case TYPE_PID:
				return "type_pid_";
			case TYPE_UPNAME:
				return "type_upname_";
			case PK_CROP:
				return "pk_crop_";
			case TYPE_TIME:
				return "type_time_";
			case TYPE_CODE:
				return "type_code_";
			case TYPE_FLAG:
				return "type_flag_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getType_id() {
		return getAttribute(TYPE_ID);
	}

	/**
	 * 设置主键
	 * @param type_id
	 */
	public void setType_id(String type_id) {
		setAttribute(TYPE_ID, type_id);
	}

	/**
	 * 获取资源类型名称
	 * @return
	 */
	public String getType_name() {
		return getAttribute(TYPE_NAME);
	}

	/**
	 * 设置资源类型名称
	 * @param type_name
	 */
	public void setType_name(String type_name) {
		setAttribute(TYPE_NAME, type_name);
	}

	/**
	 * 获取资源父id
	 * @return
	 */
	public String getType_pid() {
		return getAttribute(TYPE_PID);
	}

	/**
	 * 设置资源父id
	 * @param type_pid
	 */
	public void setType_pid(String type_pid) {
		setAttribute(TYPE_PID, type_pid);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getType_upname() {
		return getAttribute(TYPE_UPNAME);
	}

	/**
	 * 设置创建人
	 * @param type_upname
	 */
	public void setType_upname(String type_upname) {
		setAttribute(TYPE_UPNAME, type_upname);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getType_time() {
		return getAttribute(TYPE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param type_time
	 */
	public void setType_time(String type_time) {
		setAttribute(TYPE_TIME, type_time);
	}

	/**
	 * 获取资源类型编码
	 * @return
	 */
	public String getType_code() {
		return getAttribute(TYPE_CODE);
	}

	/**
	 * 设置资源类型编码
	 * @param type_code
	 */
	public void setType_code(String type_code) {
		setAttribute(TYPE_CODE, type_code);
	}

	/**
	 * 获取新属性
	 * @return
	 */
	public Integer getType_flag() {
		return getAttribute(TYPE_FLAG);
	}

	/**
	 * 设置新属性
	 * @param type_flag
	 */
	public void setType_flag(Integer type_flag) {
		setAttribute(TYPE_FLAG, type_flag);
	}

}
