/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.org.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 组织架构实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class DefaultOrgModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_org";
	
	/** 主键 */
	public final static String PK_ORG = "pk_org";	
	/** 所属企业 */
	public final static String PK_CROP = "pk_crop";	
	/** 上级组织 */
	public final static String PK_PARENT = "pk_parent";	
	/** 组织编码 */
	public final static String ORG_CODE = "org_code";	
	/** 组织名称 */
	public final static String ORG_NAME = "org_name";	
	/** 组织类型（0组织，1区域，2项目，3部门） */
	public final static String ORG_TYPE = "org_type";	
	/** 备注 */
	public final static String MEMO = "memo";	
	/** 关联区域 */
	public final static String ORG_AREA = "org_area";	
	/** 关联项目 */
	public final static String ORG_PROJECT = "org_project";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 最后修改人 */
	public final static String LAST_MODIFY_USER = "last_modify_user";	
	/** 最后修改时间 */
	public final static String LAST_MODIFY_TIME = "last_modify_time";	
	/** 最后更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 删除标志，1.删除，0未删除 */
	public final static String DELETE_FLAG = "delete_flag";	
	/** 排序字段 */
	public final static String SORT = "sort";	
	/** 层级结构 */
	public final static String HIERARCHY_IDS = "hierarchy_ids";	

	public DefaultOrgModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_ORG;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_ORG:
			return "pk_org_";
		case PK_CROP:
			return "pk_crop_";
		case PK_PARENT:
			return "pk_parent_";
		case ORG_CODE:
			return "org_code_";
		case ORG_NAME:
			return "org_name_";
		case ORG_TYPE:
			return "org_type_";
		case MEMO:
			return "memo_";
		case ORG_AREA:
			return "org_area_";
		case ORG_PROJECT:
			return "org_project_";
		case CREATE_USER:
			return "create_user_";
		case CREATE_TIME:
			return "create_time_";
		case LAST_MODIFY_USER:
			return "last_modify_user_";
		case LAST_MODIFY_TIME:
			return "last_modify_time_";
		case UPDATE_TIME:
			return "update_time_";
		case DELETE_FLAG:
			return "delete_flag_";
		case SORT:
			return "sort_";
		case HIERARCHY_IDS:
			return "hierarchy_ids_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_org() {
		return getAttribute(PK_ORG);
	}

	/**
	 * 设置主键
	 * @param pk_org
	 */
	public void setPk_org(String pk_org) {
		setAttribute(PK_ORG, pk_org);
	}

	/**
	 * 获取所属企业
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属企业
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取上级组织
	 * @return
	 */
	public String getPk_parent() {
		return getAttribute(PK_PARENT);
	}

	/**
	 * 设置上级组织
	 * @param pk_parent
	 */
	public void setPk_parent(String pk_parent) {
		setAttribute(PK_PARENT, pk_parent);
	}

	/**
	 * 获取组织编码
	 * @return
	 */
	public String getOrg_code() {
		return getAttribute(ORG_CODE);
	}

	/**
	 * 设置组织编码
	 * @param org_code
	 */
	public void setOrg_code(String org_code) {
		setAttribute(ORG_CODE, org_code);
	}

	/**
	 * 获取组织名称
	 * @return
	 */
	public String getOrg_name() {
		return getAttribute(ORG_NAME);
	}

	/**
	 * 设置组织名称
	 * @param org_name
	 */
	public void setOrg_name(String org_name) {
		setAttribute(ORG_NAME, org_name);
	}

	/**
	 * 获取组织类型（0组织，1区域，2项目，3部门）
	 * @return
	 */
	public String getOrg_type() {
		return getAttribute(ORG_TYPE);
	}

	/**
	 * 设置组织类型（0组织，1区域，2项目，3部门）
	 * @param org_type
	 */
	public void setOrg_type(String org_type) {
		setAttribute(ORG_TYPE, org_type);
	}

	/**
	 * 获取备注
	 * @return
	 */
	public String getMemo() {
		return getAttribute(MEMO);
	}

	/**
	 * 设置备注
	 * @param memo
	 */
	public void setMemo(String memo) {
		setAttribute(MEMO, memo);
	}

	/**
	 * 获取关联区域
	 * @return
	 */
	public String getOrg_area() {
		return getAttribute(ORG_AREA);
	}

	/**
	 * 设置关联区域
	 * @param org_area
	 */
	public void setOrg_area(String org_area) {
		setAttribute(ORG_AREA, org_area);
	}

	/**
	 * 获取关联项目
	 * @return
	 */
	public String getOrg_project() {
		return getAttribute(ORG_PROJECT);
	}

	/**
	 * 设置关联项目
	 * @param org_project
	 */
	public void setOrg_project(String org_project) {
		setAttribute(ORG_PROJECT, org_project);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取最后修改人
	 * @return
	 */
	public String getLast_modify_user() {
		return getAttribute(LAST_MODIFY_USER);
	}

	/**
	 * 设置最后修改人
	 * @param last_modify_user
	 */
	public void setLast_modify_user(String last_modify_user) {
		setAttribute(LAST_MODIFY_USER, last_modify_user);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getLast_modify_time() {
		return getAttribute(LAST_MODIFY_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param last_modify_time
	 */
	public void setLast_modify_time(String last_modify_time) {
		setAttribute(LAST_MODIFY_TIME, last_modify_time);
	}

	/**
	 * 获取最后更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置最后更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取删除标志，1.删除，0未删除
	 * @return
	 */
	public String getDelete_flag() {
		return getAttribute(DELETE_FLAG);
	}

	/**
	 * 设置删除标志，1.删除，0未删除
	 * @param delete_flag
	 */
	public void setDelete_flag(String delete_flag) {
		setAttribute(DELETE_FLAG, delete_flag);
	}

	/**
	 * 获取排序字段
	 * @return
	 */
	public String getSort() {
		return getAttribute(SORT);
	}

	/**
	 * 设置排序字段
	 * @param sort
	 */
	public void setSort(String sort) {
		setAttribute(SORT, sort);
	}

	/**
	 * 获取层级结构
	 * @return
	 */
	public String getHierarchy_ids() {
		return getAttribute(HIERARCHY_IDS);
	}

	/**
	 * 设置层级结构
	 * @param hierarchy_ids
	 */
	public void setHierarchy_ids(String hierarchy_ids) {
		setAttribute(HIERARCHY_IDS, hierarchy_ids);
	}

}
