/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.station.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 岗位管理实体类
 * 
 * @author dms
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYStationModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_station";
	
	/** 主键 */
	public final static String PK_STATION = "pk_station";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 岗位编码 */
	public final static String STATION_CODE = "station_code";	
	/** 岗位名称 */
	public final static String STATION_NAME = "station_name";	
	/** 任务级别 */
	public final static String TASK_LEVEL = "task_level";	
	/** 岗位级别 */
	public final static String STATION_LEVEL = "station_level";	
	/** 所属部门 */
	public final static String PK_DEPT = "pk_dept";	
	/** 所属组织 */
	public final static String PK_ORG = "pk_org";	
	/** 岗位描述 */
	public final static String MEMO = "memo";	
	/** 上级岗位 */
	public final static String PK_PARENT = "pk_parent";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 最后修改人 */
	public final static String LAST_MODIFY_USER = "last_modify_user";	
	/** 最后修改时间 */
	public final static String LAST_MODIFY_TIME = "last_modify_time";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 删除标志1.已删除，0未删除 */
	public final static String DELETE_FLAG = "delete_flag";	
	/** 排序字段 */
	public final static String SORT = "sort";	

	public YJWYStationModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_STATION;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_STATION:
			return "pk_station_";
		case PK_CROP:
			return "pk_crop_";
		case STATION_CODE:
			return "station_code_";
		case STATION_NAME:
			return "station_name_";
		case TASK_LEVEL:
			return "task_level_";
		case STATION_LEVEL:
			return "station_level_";
		case PK_DEPT:
			return "pk_dept_";
		case PK_ORG:
			return "pk_org_";
		case MEMO:
			return "memo_";
		case PK_PARENT:
			return "pk_parent_";
		case CREATE_USER:
			return "create_user_";
		case CREATE_TIME:
			return "create_time_";
		case LAST_MODIFY_USER:
			return "last_modify_user_";
		case LAST_MODIFY_TIME:
			return "last_modify_time_";
		case UPDATE_TIME:
			return "update_time_";
		case DELETE_FLAG:
			return "delete_flag_";
		case SORT:
			return "sort_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_station() {
		return getAttribute(PK_STATION);
	}

	/**
	 * 设置主键
	 * @param pk_station
	 */
	public void setPk_station(String pk_station) {
		setAttribute(PK_STATION, pk_station);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取岗位编码
	 * @return
	 */
	public String getStation_code() {
		return getAttribute(STATION_CODE);
	}

	/**
	 * 设置岗位编码
	 * @param station_code
	 */
	public void setStation_code(String station_code) {
		setAttribute(STATION_CODE, station_code);
	}

	/**
	 * 获取岗位名称
	 * @return
	 */
	public String getStation_name() {
		return getAttribute(STATION_NAME);
	}

	/**
	 * 设置岗位名称
	 * @param station_name
	 */
	public void setStation_name(String station_name) {
		setAttribute(STATION_NAME, station_name);
	}

	/**
	 * 获取任务级别
	 * @return
	 */
	public String getTask_level() {
		return getAttribute(TASK_LEVEL);
	}

	/**
	 * 设置任务级别
	 * @param task_level
	 */
	public void setTask_level(String task_level) {
		setAttribute(TASK_LEVEL, task_level);
	}

	/**
	 * 获取岗位级别
	 * @return
	 */
	public String getStation_level() {
		return getAttribute(STATION_LEVEL);
	}

	/**
	 * 设置岗位级别
	 * @param station_level
	 */
	public void setStation_level(String station_level) {
		setAttribute(STATION_LEVEL, station_level);
	}

	/**
	 * 获取所属部门
	 * @return
	 */
	public String getPk_dept() {
		return getAttribute(PK_DEPT);
	}

	/**
	 * 设置所属部门
	 * @param pk_dept
	 */
	public void setPk_dept(String pk_dept) {
		setAttribute(PK_DEPT, pk_dept);
	}

	/**
	 * 获取所属组织
	 * @return
	 */
	public String getPk_org() {
		return getAttribute(PK_ORG);
	}

	/**
	 * 设置所属组织
	 * @param pk_org
	 */
	public void setPk_org(String pk_org) {
		setAttribute(PK_ORG, pk_org);
	}

	/**
	 * 获取岗位描述
	 * @return
	 */
	public String getMemo() {
		return getAttribute(MEMO);
	}

	/**
	 * 设置岗位描述
	 * @param memo
	 */
	public void setMemo(String memo) {
		setAttribute(MEMO, memo);
	}

	/**
	 * 获取上级岗位
	 * @return
	 */
	public String getPk_parent() {
		return getAttribute(PK_PARENT);
	}

	/**
	 * 设置上级岗位
	 * @param pk_parent
	 */
	public void setPk_parent(String pk_parent) {
		setAttribute(PK_PARENT, pk_parent);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取最后修改人
	 * @return
	 */
	public String getLast_modify_user() {
		return getAttribute(LAST_MODIFY_USER);
	}

	/**
	 * 设置最后修改人
	 * @param last_modify_user
	 */
	public void setLast_modify_user(String last_modify_user) {
		setAttribute(LAST_MODIFY_USER, last_modify_user);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getLast_modify_time() {
		return getAttribute(LAST_MODIFY_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param last_modify_time
	 */
	public void setLast_modify_time(String last_modify_time) {
		setAttribute(LAST_MODIFY_TIME, last_modify_time);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取删除标志1.已删除，0未删除
	 * @return
	 */
	public String getDelete_flag() {
		return getAttribute(DELETE_FLAG);
	}

	/**
	 * 设置删除标志1.已删除，0未删除
	 * @param delete_flag
	 */
	public void setDelete_flag(String delete_flag) {
		setAttribute(DELETE_FLAG, delete_flag);
	}

	/**
	 * 获取排序字段
	 * @return
	 */
	public String getSort() {
		return getAttribute(SORT);
	}

	/**
	 * 设置排序字段
	 * @param sort
	 */
	public void setSort(String sort) {
		setAttribute(SORT, sort);
	}

}
