/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.resources.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 属性名称表实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class AttributeNameModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_attribute_name";
	
	/** 主键id */
	public final static String ATTRIBUTE_NAME_ID = "attribute_name_id";	
	/** 属性编码 */
	public final static String ATTRIBUTE_CODE = "attribute_code";	
	/** 属性名称 */
	public final static String ATTRIBUTE_NAME = "attribute_name";	

	public AttributeNameModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return ATTRIBUTE_NAME_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case ATTRIBUTE_NAME_ID:
			return "attribute_name_id_";
		case ATTRIBUTE_CODE:
			return "attribute_code";
		case ATTRIBUTE_NAME:
			return "attribute_name";
		}
		return null;
	}

	/**
	 * 获取主键id
	 * @return
	 */
	public String getAttribute_name_id() {
		return getAttribute(ATTRIBUTE_NAME_ID);
	}

	/**
	 * 设置主键id
	 * @param attribute_name_id
	 */
	public void setAttribute_name_id(String attribute_name_id) {
		setAttribute(ATTRIBUTE_NAME_ID, attribute_name_id);
	}

	/**
	 * 获取属性编码
	 * @return
	 */
	public String getAttribute_code() {
		return getAttribute(ATTRIBUTE_CODE);
	}

	/**
	 * 设置属性编码
	 * @param attribute_code
	 */
	public void setAttribute_code(String attribute_code) {
		setAttribute(ATTRIBUTE_CODE, attribute_code);
	}

	/**
	 * 获取属性名称
	 * @return
	 */
	public String getAttribute_name() {
		return getAttribute(ATTRIBUTE_NAME);
	}

	/**
	 * 设置属性名称
	 * @param attribute_name
	 */
	public void setAttribute_name(String attribute_name) {
		setAttribute(ATTRIBUTE_NAME, attribute_name);
	}

}
