/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.quality.proinspect.inspect.insptask.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 核查与整改任务实体类
 * 
 * @author dms
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class InspectTaskModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_quality_inspecttask";
	
	/** 主键ID */
	public final static String PK_TASK = "pk_task";	
	/** 外键(核查标准) */
	public final static String FK_STANDARD = "fk_standard";	
	/** 外键(项目) */
	public final static String FK_PROJECT = "fk_project";	
	/** 外键(岗位) */
	public final static String FK_JOB = "fk_job";	
	/** 外键(区域) */
	public final static String FK_AREA = "fk_area";	
	/** 外键(部门) */
	public final static String FK_DEPT = "fk_dept";	
	/** 外键(任务所属人) */
	public final static String FK_TASKUSER = "fk_taskuser";	
	/** 任务当前人ID */
	public final static String TASK_CURRENTUSER_PK = "task_currentuser_pk";	
	/** 任务整改人ID */
	public final static String TASK_RECTIFYUSER_PK = "task_rectifyuser_pk";	
	/** 任务开始日期 */
	public final static String TASK_START_TIME = "task_start_time";	
	/** 任务结束时间 */
	public final static String TASK_END_TIME = "task_end_time";	
	/** 任务生成方式（0:达美盛资产云后台系统生成，1：手机终端核查任务） */
	public final static String TASK_GENERATE_MODE = "task_generate_mode";	
	/** 分值 */
	public final static String TASK_SCORE = "task_score";	
	/** 扣分 */
	public final static String TASK_SUBTRACT_SCORE = "task_subtract_score";	
	/** 完成期限(日期) */
	public final static String TASK_DEADLINE_DATE = "task_deadline_date";	
	/** 审阅状态（0不合格；1合格，2未审阅） */
	public final static String CHECK_STATE = "check_state";	
	/** 任务类型（1.核查任务，2.巡逻任务） */
	public final static String TASK_TYPE = "task_type";	
	/** 任务核查结果 */
	public final static String TASK_INSPECTRESULT = "task_inspectresult";	
	/** 任务编码 */
	public final static String TASK_CODE = "task_code";	
	/** 专业 */
	public final static String SPECIALTY = "specialty";	
	/** 任务整改开始时间 */
	public final static String TASK_RECTIFY_STARTTIME = "task_rectify_starttime";	
	/** 任务整改完成时间 */
	public final static String TASK_RECTIFY_FINISHTIME = "task_rectify_finishtime";	
	/** 整改确认时间 */
	public final static String TASK_QUALIFIED_TIME = "task_qualified_time";	
	/** 任务整改是否超期 */
	public final static String TASK_ISCQ = "task_iscq";	
	/** 任务状态(10待办，20待整改，30已办，40正常过期，50休假关闭，60手动关闭) */
	public final static String TASK_STATE = "task_state";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 修改人 */
	public final static String UPDATE_USER = "update_user";	
	/** 修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 是否有效 */
	public final static String IS_VALID = "is_valid";	
	/** 任务频次NAME */
	public final static String TASK_PC_NAME = "task_pc_name";	
	/** 纬度 */
	public final static String RECORD_FINISH_LAT = "record_finish_lat";	
	/** 经度 */
	public final static String RECORD_FINISH_LON = "record_finish_lon";	
	/** 任务执行地点 */
	public final static String TASK_EXECUTE_SITE = "task_execute_site";	
	/** 任务整改截止日期 */
	public final static String TASK_RECTIFY_DEADLINE_TIME = "task_rectify_deadline_time";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 是否签到 */
	public final static String IS_SIGN = "is_sign";	
	/** 审阅内容 */
	public final static String CHECK_CONTENT = "check_content";	
	/** 审阅人 */
	public final static String CHECK_USER_PK = "check_user_pk";	
	/** 审阅时间 */
	public final static String CHECK_TIME = "check_time";	
	/** 是否整改 */
	public final static String IS_RECTIFY = "is_rectify";	

	public InspectTaskModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_TASK;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_TASK:
			return "pk_task";
		case FK_STANDARD:
			return "fk_standard";
		case FK_PROJECT:
			return "fk_project";
		case FK_JOB:
			return "fk_job";
		case FK_AREA:
			return "fk_area";
		case FK_DEPT:
			return "fk_dept";
		case FK_TASKUSER:
			return "fk_taskuser";
		case TASK_CURRENTUSER_PK:
			return "task_currentuser_pk";
		case TASK_RECTIFYUSER_PK:
			return "task_rectifyuser_pk";
		case TASK_START_TIME:
			return "task_start_time";
		case TASK_END_TIME:
			return "task_end_time";
		case TASK_GENERATE_MODE:
			return "task_generate_mode";
		case TASK_SCORE:
			return "task_score";
		case TASK_SUBTRACT_SCORE:
			return "task_subtract_score";
		case TASK_DEADLINE_DATE:
			return "task_deadline_date";
		case CHECK_STATE:
			return "check_state";
		case TASK_TYPE:
			return "task_type";
		case TASK_INSPECTRESULT:
			return "task_inspectresult";
		case TASK_CODE:
			return "task_code";
		case SPECIALTY:
			return "specialty";
		case TASK_RECTIFY_STARTTIME:
			return "task_rectify_starttime";
		case TASK_RECTIFY_FINISHTIME:
			return "task_rectify_finishtime";
		case TASK_QUALIFIED_TIME:
			return "task_qualified_time";
		case TASK_ISCQ:
			return "task_iscq";
		case TASK_STATE:
			return "task_state";
		case CREATE_USER:
			return "create_user";
		case CREATE_TIME:
			return "create_time";
		case UPDATE_USER:
			return "update_user";
		case UPDATE_TIME:
			return "update_time";
		case IS_VALID:
			return "is_valid";
		case TASK_PC_NAME:
			return "task_pc_name";
		case RECORD_FINISH_LAT:
			return "record_finish_lat";
		case RECORD_FINISH_LON:
			return "record_finish_lon";
		case TASK_EXECUTE_SITE:
			return "task_execute_site";
		case TASK_RECTIFY_DEADLINE_TIME:
			return "task_rectify_deadline_time";
		case PK_CROP:
			return "pk_crop";
		case IS_SIGN:
			return "is_sign";
		case CHECK_CONTENT:
			return "check_content";
		case CHECK_USER_PK:
			return "check_user_pk";
		case CHECK_TIME:
			return "check_time";
		case IS_RECTIFY:
			return "is_rectify";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_task() {
		return getAttribute(PK_TASK);
	}

	/**
	 * 设置主键ID
	 * @param pk_task
	 */
	public void setPk_task(String pk_task) {
		setAttribute(PK_TASK, pk_task);
	}

	/**
	 * 获取外键(核查标准)
	 * @return
	 */
	public String getFk_standard() {
		return getAttribute(FK_STANDARD);
	}

	/**
	 * 设置外键(核查标准)
	 * @param fk_standard
	 */
	public void setFk_standard(String fk_standard) {
		setAttribute(FK_STANDARD, fk_standard);
	}

	/**
	 * 获取外键(项目)
	 * @return
	 */
	public String getFk_project() {
		return getAttribute(FK_PROJECT);
	}

	/**
	 * 设置外键(项目)
	 * @param fk_project
	 */
	public void setFk_project(String fk_project) {
		setAttribute(FK_PROJECT, fk_project);
	}

	/**
	 * 获取外键(岗位)
	 * @return
	 */
	public String getFk_job() {
		return getAttribute(FK_JOB);
	}

	/**
	 * 设置外键(岗位)
	 * @param fk_job
	 */
	public void setFk_job(String fk_job) {
		setAttribute(FK_JOB, fk_job);
	}

	/**
	 * 获取外键(区域)
	 * @return
	 */
	public String getFk_area() {
		return getAttribute(FK_AREA);
	}

	/**
	 * 设置外键(区域)
	 * @param fk_area
	 */
	public void setFk_area(String fk_area) {
		setAttribute(FK_AREA, fk_area);
	}

	/**
	 * 获取外键(部门)
	 * @return
	 */
	public String getFk_dept() {
		return getAttribute(FK_DEPT);
	}

	/**
	 * 设置外键(部门)
	 * @param fk_dept
	 */
	public void setFk_dept(String fk_dept) {
		setAttribute(FK_DEPT, fk_dept);
	}

	/**
	 * 获取外键(任务所属人)
	 * @return
	 */
	public String getFk_taskuser() {
		return getAttribute(FK_TASKUSER);
	}

	/**
	 * 设置外键(任务所属人)
	 * @param fk_taskuser
	 */
	public void setFk_taskuser(String fk_taskuser) {
		setAttribute(FK_TASKUSER, fk_taskuser);
	}

	/**
	 * 获取任务当前人ID
	 * @return
	 */
	public String getTask_currentuser_pk() {
		return getAttribute(TASK_CURRENTUSER_PK);
	}

	/**
	 * 设置任务当前人ID
	 * @param task_currentuser_pk
	 */
	public void setTask_currentuser_pk(String task_currentuser_pk) {
		setAttribute(TASK_CURRENTUSER_PK, task_currentuser_pk);
	}

	/**
	 * 获取任务整改人ID
	 * @return
	 */
	public String getTask_rectifyuser_pk() {
		return getAttribute(TASK_RECTIFYUSER_PK);
	}

	/**
	 * 设置任务整改人ID
	 * @param task_rectifyuser_pk
	 */
	public void setTask_rectifyuser_pk(String task_rectifyuser_pk) {
		setAttribute(TASK_RECTIFYUSER_PK, task_rectifyuser_pk);
	}

	/**
	 * 获取任务开始日期
	 * @return
	 */
	public String getTask_start_time() {
		return getAttribute(TASK_START_TIME);
	}

	/**
	 * 设置任务开始日期
	 * @param task_start_time
	 */
	public void setTask_start_time(String task_start_time) {
		setAttribute(TASK_START_TIME, task_start_time);
	}

	/**
	 * 获取任务结束时间
	 * @return
	 */
	public String getTask_end_time() {
		return getAttribute(TASK_END_TIME);
	}

	/**
	 * 设置任务结束时间
	 * @param task_end_time
	 */
	public void setTask_end_time(String task_end_time) {
		setAttribute(TASK_END_TIME, task_end_time);
	}

	/**
	 * 获取任务生成方式（0:达美盛资产云后台系统生成，1：手机终端核查任务）
	 * @return
	 */
	public String getTask_generate_mode() {
		return getAttribute(TASK_GENERATE_MODE);
	}

	/**
	 * 设置任务生成方式（0:达美盛资产云后台系统生成，1：手机终端核查任务）
	 * @param task_generate_mode
	 */
	public void setTask_generate_mode(String task_generate_mode) {
		setAttribute(TASK_GENERATE_MODE, task_generate_mode);
	}

	/**
	 * 获取分值
	 * @return
	 */
	public BigDecimal getTask_score() {
		return getAttribute(TASK_SCORE);
	}

	/**
	 * 设置分值
	 * @param task_score
	 */
	public void setTask_score(BigDecimal task_score) {
		setAttribute(TASK_SCORE, task_score);
	}

	/**
	 * 获取扣分
	 * @return
	 */
	public BigDecimal getTask_subtract_score() {
		return getAttribute(TASK_SUBTRACT_SCORE);
	}

	/**
	 * 设置扣分
	 * @param task_subtract_score
	 */
	public void setTask_subtract_score(BigDecimal task_subtract_score) {
		setAttribute(TASK_SUBTRACT_SCORE, task_subtract_score);
	}

	/**
	 * 获取完成期限(日期)
	 * @return
	 */
	public String getTask_deadline_date() {
		return getAttribute(TASK_DEADLINE_DATE);
	}

	/**
	 * 设置完成期限(日期)
	 * @param task_deadline_date
	 */
	public void setTask_deadline_date(String task_deadline_date) {
		setAttribute(TASK_DEADLINE_DATE, task_deadline_date);
	}

	/**
	 * 获取审阅状态（0不合格；1合格，2未审阅）
	 * @return
	 */
	public String getCheck_state() {
		return getAttribute(CHECK_STATE);
	}

	/**
	 * 设置审阅状态（0不合格；1合格，2未审阅）
	 * @param check_state
	 */
	public void setCheck_state(String check_state) {
		setAttribute(CHECK_STATE, check_state);
	}

	/**
	 * 获取任务类型（1.核查任务，2.巡逻任务）
	 * @return
	 */
	public Integer getTask_type() {
		return getAttribute(TASK_TYPE);
	}

	/**
	 * 设置任务类型（1.核查任务，2.巡逻任务）
	 * @param task_type
	 */
	public void setTask_type(Integer task_type) {
		setAttribute(TASK_TYPE, task_type);
	}

	/**
	 * 获取任务核查结果
	 * @return
	 */
	public String getTask_inspectresult() {
		return getAttribute(TASK_INSPECTRESULT);
	}

	/**
	 * 设置任务核查结果
	 * @param task_inspectresult
	 */
	public void setTask_inspectresult(String task_inspectresult) {
		setAttribute(TASK_INSPECTRESULT, task_inspectresult);
	}

	/**
	 * 获取任务编码
	 * @return
	 */
	public String getTask_code() {
		return getAttribute(TASK_CODE);
	}

	/**
	 * 设置任务编码
	 * @param task_code
	 */
	public void setTask_code(String task_code) {
		setAttribute(TASK_CODE, task_code);
	}

	/**
	 * 获取专业
	 * @return
	 */
	public String getSpecialty() {
		return getAttribute(SPECIALTY);
	}

	/**
	 * 设置专业
	 * @param specialty
	 */
	public void setSpecialty(String specialty) {
		setAttribute(SPECIALTY, specialty);
	}

	/**
	 * 获取任务整改开始时间
	 * @return
	 */
	public String getTask_rectify_starttime() {
		return getAttribute(TASK_RECTIFY_STARTTIME);
	}

	/**
	 * 设置任务整改开始时间
	 * @param task_rectify_starttime
	 */
	public void setTask_rectify_starttime(String task_rectify_starttime) {
		setAttribute(TASK_RECTIFY_STARTTIME, task_rectify_starttime);
	}

	/**
	 * 获取任务整改完成时间
	 * @return
	 */
	public String getTask_rectify_finishtime() {
		return getAttribute(TASK_RECTIFY_FINISHTIME);
	}

	/**
	 * 设置任务整改完成时间
	 * @param task_rectify_finishtime
	 */
	public void setTask_rectify_finishtime(String task_rectify_finishtime) {
		setAttribute(TASK_RECTIFY_FINISHTIME, task_rectify_finishtime);
	}

	/**
	 * 获取整改确认时间
	 * @return
	 */
	public String getTask_qualified_time() {
		return getAttribute(TASK_QUALIFIED_TIME);
	}

	/**
	 * 设置整改确认时间
	 * @param task_qualified_time
	 */
	public void setTask_qualified_time(String task_qualified_time) {
		setAttribute(TASK_QUALIFIED_TIME, task_qualified_time);
	}

	/**
	 * 获取任务整改是否超期
	 * @return
	 */
	public String getTask_iscq() {
		return getAttribute(TASK_ISCQ);
	}

	/**
	 * 设置任务整改是否超期
	 * @param task_iscq
	 */
	public void setTask_iscq(String task_iscq) {
		setAttribute(TASK_ISCQ, task_iscq);
	}

	/**
	 * 获取任务状态(10待办，20待整改，30已办，40正常过期，50休假关闭，60手动关闭)
	 * @return
	 */
	public String getTask_state() {
		return getAttribute(TASK_STATE);
	}

	/**
	 * 设置任务状态(10待办，20待整改，30已办，40正常过期，50休假关闭，60手动关闭)
	 * @param task_state
	 */
	public void setTask_state(String task_state) {
		setAttribute(TASK_STATE, task_state);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取修改人
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置修改人
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

	/**
	 * 获取修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取是否有效
	 * @return
	 */
	public String getIs_valid() {
		return getAttribute(IS_VALID);
	}

	/**
	 * 设置是否有效
	 * @param is_valid
	 */
	public void setIs_valid(String is_valid) {
		setAttribute(IS_VALID, is_valid);
	}

	/**
	 * 获取任务频次NAME
	 * @return
	 */
	public String getTask_pc_name() {
		return getAttribute(TASK_PC_NAME);
	}

	/**
	 * 设置任务频次NAME
	 * @param task_pc_name
	 */
	public void setTask_pc_name(String task_pc_name) {
		setAttribute(TASK_PC_NAME, task_pc_name);
	}

	/**
	 * 获取纬度
	 * @return
	 */
	public String getRecord_finish_lat() {
		return getAttribute(RECORD_FINISH_LAT);
	}

	/**
	 * 设置纬度
	 * @param record_finish_lat
	 */
	public void setRecord_finish_lat(String record_finish_lat) {
		setAttribute(RECORD_FINISH_LAT, record_finish_lat);
	}

	/**
	 * 获取经度
	 * @return
	 */
	public String getRecord_finish_lon() {
		return getAttribute(RECORD_FINISH_LON);
	}

	/**
	 * 设置经度
	 * @param record_finish_lon
	 */
	public void setRecord_finish_lon(String record_finish_lon) {
		setAttribute(RECORD_FINISH_LON, record_finish_lon);
	}

	/**
	 * 获取任务执行地点
	 * @return
	 */
	public String getTask_execute_site() {
		return getAttribute(TASK_EXECUTE_SITE);
	}

	/**
	 * 设置任务执行地点
	 * @param task_execute_site
	 */
	public void setTask_execute_site(String task_execute_site) {
		setAttribute(TASK_EXECUTE_SITE, task_execute_site);
	}

	/**
	 * 获取任务整改截止日期
	 * @return
	 */
	public String getTask_rectify_deadline_time() {
		return getAttribute(TASK_RECTIFY_DEADLINE_TIME);
	}

	/**
	 * 设置任务整改截止日期
	 * @param task_rectify_deadline_time
	 */
	public void setTask_rectify_deadline_time(String task_rectify_deadline_time) {
		setAttribute(TASK_RECTIFY_DEADLINE_TIME, task_rectify_deadline_time);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取是否签到
	 * @return
	 */
	public String getIs_sign() {
		return getAttribute(IS_SIGN);
	}

	/**
	 * 设置是否签到
	 * @param is_sign
	 */
	public void setIs_sign(String is_sign) {
		setAttribute(IS_SIGN, is_sign);
	}

	/**
	 * 获取审阅内容
	 * @return
	 */
	public String getCheck_content() {
		return getAttribute(CHECK_CONTENT);
	}

	/**
	 * 设置审阅内容
	 * @param check_content
	 */
	public void setCheck_content(String check_content) {
		setAttribute(CHECK_CONTENT, check_content);
	}

	/**
	 * 获取审阅人
	 * @return
	 */
	public String getCheck_user_pk() {
		return getAttribute(CHECK_USER_PK);
	}

	/**
	 * 设置审阅人
	 * @param check_user_pk
	 */
	public void setCheck_user_pk(String check_user_pk) {
		setAttribute(CHECK_USER_PK, check_user_pk);
	}

	/**
	 * 获取审阅时间
	 * @return
	 */
	public String getCheck_time() {
		return getAttribute(CHECK_TIME);
	}

	/**
	 * 设置审阅时间
	 * @param check_time
	 */
	public void setCheck_time(String check_time) {
		setAttribute(CHECK_TIME, check_time);
	}

	/**
	 * 获取是否整改
	 * @return
	 */
	public String getIs_rectify() {
		return getAttribute(IS_RECTIFY);
	}

	/**
	 * 设置是否整改
	 * @param is_rectify
	 */
	public void setIs_rectify(String is_rectify) {
		setAttribute(IS_RECTIFY, is_rectify);
	}

}
