/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.performance.sign.vo;

/**
 * 休假备案Vo
 * 
 * @author yuting.wang
 * @version since Shareworx platform 2.0
 */
public class YJWYSignModelVo{
	
	private String area_id;//区域ID
	
	private String project_id;//项目ID
	
	private String sign_area_id;//签到区域ID
	
	private String sign_project_id;//签到项目ID
	
	private String user_id;//人员ID
	
	private String station_id;//岗位ID
	
	private String fk_department;//部门ID
	
	private String state;//动作
	
	private String start_date;
	
	private String end_date;
	
	private String start_time;
	
	private String end_time;
	
	private int limit;
	
	private int start;
	
	public String getArea_id() {
		return area_id;
	}
	public void setArea_id(String area_id) {
		this.area_id = area_id;
	}
	public String getProject_id() {
		return project_id;
	}
	public void setProject_id(String project_id) {
		this.project_id = project_id;
	}
	public String getUser_id() {
		return user_id;
	}
	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public int getLimit() {
		return limit;
	}
	public void setLimit(int limit) {
		this.limit = limit;
	}
	public int getStart() {
		return start;
	}
	public void setStart(int start) {
		this.start = start;
	}
	public String getStation_id() {
		return station_id;
	}
	public void setStation_id(String station_id) {
		this.station_id = station_id;
	}
	
	public String getStart_date() {
		return start_date;
	}
	public void setStart_date(String start_date) {
		this.start_date = start_date;
	}
	public String getEnd_date() {
		return end_date;
	}
	public void setEnd_date(String end_date) {
		this.end_date = end_date;
	}
	public String getStart_time() {
		return start_time;
	}
	public void setStart_time(String start_time) {
		this.start_time = start_time;
	}
	public String getEnd_time() {
		return end_time;
	}
	public void setEnd_time(String end_time) {
		this.end_time = end_time;
	}
	public String getFk_department() {
		return fk_department;
	}
	public void setFk_department(String fk_department) {
		this.fk_department = fk_department;
	}
	public String getSign_area_id() {
		return sign_area_id;
	}
	public void setSign_area_id(String sign_area_id) {
		this.sign_area_id = sign_area_id;
	}
	public String getSign_project_id() {
		return sign_project_id;
	}
	public void setSign_project_id(String sign_project_id) {
		this.sign_project_id = sign_project_id;
	}
	
	

}
