/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.pub.test.plms.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 测试plms实体类
 * 
 * @author zhi.zhang
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class PlmsModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_plms";
	
	/** 主键 */
	public final static String PK_PLMS = "pk_plms";	

	public PlmsModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_PLMS;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_PLMS:
			return "pk_plms";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_plms() {
		return getAttribute(PK_PLMS);
	}

	/**
	 * 设置主键
	 * @param pk_plms
	 */
	public void setPk_plms(String pk_plms) {
		setAttribute(PK_PLMS, pk_plms);
	}

}
