/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.problem.details.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 报事主类实体类
 * 
 * @author zhi.zhang
 * @version since Shareworx platform 2.0
 */
public class YJWYProblemDetailsModel extends DomainModel {

	private static final long serialVersionUID = 1L;
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_problem_details";
	
	/** 报事主键ID */
	public final static String PK_DETAILS_ID = "pk_details_id";	
	/** 报事详情编码 */
	public final static String DETAILS_NUMBER = "details_number";	
	/** 关联项目ID */
	public final static String FK_PROJECT_ID = "fk_project_id";	
	/** 详情 */
	public final static String DETAILS_CONTENT = "details_content";	
	/** 客户姓名 */
	public final static String CUSTOMER_NAME = "customer_name";	
	/** 客户电话 */
	public final static String CUSTOMER_NUMBER = "customer_number";	
	/** 报事分类ID */
	public final static String FK_CLASS_ID = "fk_class_id";	
	/** 报事名称 */
	public final static String CLASS_NAME = "class_name";	
	/** 问题来源 */
	public final static String QUESTION_SOURCE = "question_source";	
	/** 楼址ID */
	public final static String FK_HOUSE_ADDRESS_ID = "fk_house_address_id";	
	/** 详细地址 */
	public final static String DETAILED_ADDRESS = "detailed_address";	
	/** 跟进人ID */
	public final static String FK_DUTY_USER_ID = "fk_duty_user_id";	
	/** 跟进人姓名 */
	public final static String DUTY_USER_NAME = "duty_user_name";	
	/** 工单ID */
	public final static String FK_DETAILS_ID = "fk_details_id";	
	/** 状态（ 1未处理，2处理中，3处理完成，4已回访，5已关闭） */
	public final static String STATE = "state";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人ID */
	public final static String CREATE_USER_ID = "create_user_id";	
	/** 创建人姓名 */
	public final static String CREATE_USER_NAME = "create_user_name";	
	/** 最后修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 最后修改人ID */
	public final static String UPDATE_USER_ID = "update_user_id";	
	/** 最后修改人姓名 */
	public final static String UPDATE_USER_NAME = "update_user_name";	
	/** 是否维修 */
	public final static String WHETHER_REPAIR = "whether_repair";	
	/** 完成之间 */
	public final static String COMPLETE_TIME = "complete_time";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 亿街区报事分类ID存储 */
	public final static String SERVICE_ID = "service_id";	
	/** 亿街区报事类型（1：报事报修， 2：表彰， 3：投诉） */
	public final static String RECORD_TYPE = "record_type";	
	/** 亿街区评价详情 */
	public final static String YJQ_REMARKS = "yjq_remarks";	
	/** 亿街区评价等级 */
	public final static String YJQ_LEVEL = "yjq_level";	
	/** 亿街区评价状态（0：未评价；1：已评价） */
	public final static String YJQ_EVALUATE = "yjq_evaluate";	
	/** 亿街区取消状态(0:未取消；1：已取消) */
	public final static String YJQ_CANCEL = "yjq_cancel";	
	/** 亿彩区判重ID */
	public final static String YCQ_WORKTASKID = "ycq_worktaskid";	
	/** 亿彩区业主id */
	public final static String YCQ_YEZHUID = "ycq_yezhuid";	
	/** 维修机房 */
	public final static String FK_REPAIR_EQUIPMENT_ROOM = "fk_repair_equipment_room";	
	/** 维修设备 */
	public final static String FK_REPAIR_EQUIPMENT = "fk_repair_equipment";	

	public YJWYProblemDetailsModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_DETAILS_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_DETAILS_ID:
			return "pk_details_id";
		case DETAILS_NUMBER:
			return "details_number";
		case FK_PROJECT_ID:
			return "fk_project_id";
		case DETAILS_CONTENT:
			return "details_content";
		case CUSTOMER_NAME:
			return "customer_name";
		case CUSTOMER_NUMBER:
			return "customer_number";
		case FK_CLASS_ID:
			return "fk_class_id";
		case CLASS_NAME:
			return "class_name";
		case QUESTION_SOURCE:
			return "question_source";
		case FK_HOUSE_ADDRESS_ID:
			return "fk_house_address_id";
		case DETAILED_ADDRESS:
			return "detailed_address";
		case FK_DUTY_USER_ID:
			return "fk_duty_user_id";
		case DUTY_USER_NAME:
			return "duty_user_name";
		case FK_DETAILS_ID:
			return "fk_details_id";
		case STATE:
			return "state";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER_ID:
			return "create_user_id";
		case CREATE_USER_NAME:
			return "create_user_name";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER_ID:
			return "update_user_id";
		case UPDATE_USER_NAME:
			return "update_user_name";
		case WHETHER_REPAIR:
			return "whether_repair";
		case COMPLETE_TIME:
			return "complete_time";
		case PK_CROP:
			return "pk_crop";
		case SERVICE_ID:
			return "service_id";
		case RECORD_TYPE:
			return "record_type";
		case YJQ_REMARKS:
			return "yjq_remarks";
		case YJQ_LEVEL:
			return "yjq_level";
		case YJQ_EVALUATE:
			return "yjq_evaluate";
		case YJQ_CANCEL:
			return "yjq_cancel";
		case YCQ_WORKTASKID:
			return "ycq_worktaskid_";
		case YCQ_YEZHUID:
			return "ycq_yezhuid_";
		case FK_REPAIR_EQUIPMENT_ROOM:
			return "fk_repair_equipment_room";
		case FK_REPAIR_EQUIPMENT:
			return "fk_repair_equipment";
		}
		return null;
	}

	/**
	 * 获取报事主键ID
	 * @return
	 */
	public String getPk_details_id() {
		return getAttribute(PK_DETAILS_ID);
	}

	/**
	 * 设置报事主键ID
	 * @param pk_details_id
	 */
	public void setPk_details_id(String pk_details_id) {
		setAttribute(PK_DETAILS_ID, pk_details_id);
	}

	/**
	 * 获取报事详情编码
	 * @return
	 */
	public String getDetails_number() {
		return getAttribute(DETAILS_NUMBER);
	}

	/**
	 * 设置报事详情编码
	 * @param details_number
	 */
	public void setDetails_number(String details_number) {
		setAttribute(DETAILS_NUMBER, details_number);
	}

	/**
	 * 获取关联项目ID
	 * @return
	 */
	public String getFk_project_id() {
		return getAttribute(FK_PROJECT_ID);
	}

	/**
	 * 设置关联项目ID
	 * @param fk_project_id
	 */
	public void setFk_project_id(String fk_project_id) {
		setAttribute(FK_PROJECT_ID, fk_project_id);
	}

	/**
	 * 获取详情
	 * @return
	 */
	public String getDetails_content() {
		return getAttribute(DETAILS_CONTENT);
	}

	/**
	 * 设置详情
	 * @param details_content
	 */
	public void setDetails_content(String details_content) {
		setAttribute(DETAILS_CONTENT, details_content);
	}

	/**
	 * 获取客户姓名
	 * @return
	 */
	public String getCustomer_name() {
		return getAttribute(CUSTOMER_NAME);
	}

	/**
	 * 设置客户姓名
	 * @param customer_name
	 */
	public void setCustomer_name(String customer_name) {
		setAttribute(CUSTOMER_NAME, customer_name);
	}

	/**
	 * 获取客户电话
	 * @return
	 */
	public String getCustomer_number() {
		return getAttribute(CUSTOMER_NUMBER);
	}

	/**
	 * 设置客户电话
	 * @param customer_number
	 */
	public void setCustomer_number(String customer_number) {
		setAttribute(CUSTOMER_NUMBER, customer_number);
	}

	/**
	 * 获取报事分类ID
	 * @return
	 */
	public String getFk_class_id() {
		return getAttribute(FK_CLASS_ID);
	}

	/**
	 * 设置报事分类ID
	 * @param fk_class_id
	 */
	public void setFk_class_id(String fk_class_id) {
		setAttribute(FK_CLASS_ID, fk_class_id);
	}

	/**
	 * 获取报事名称
	 * @return
	 */
	public String getClass_name() {
		return getAttribute(CLASS_NAME);
	}

	/**
	 * 设置报事名称
	 * @param class_name
	 */
	public void setClass_name(String class_name) {
		setAttribute(CLASS_NAME, class_name);
	}

	/**
	 * 获取问题来源
	 * @return
	 */
	public String getQuestion_source() {
		return getAttribute(QUESTION_SOURCE);
	}

	/**
	 * 设置问题来源
	 * @param question_source
	 */
	public void setQuestion_source(String question_source) {
		setAttribute(QUESTION_SOURCE, question_source);
	}

	/**
	 * 获取楼址ID
	 * @return
	 */
	public String getFk_house_address_id() {
		return getAttribute(FK_HOUSE_ADDRESS_ID);
	}

	/**
	 * 设置楼址ID
	 * @param fk_house_address_id
	 */
	public void setFk_house_address_id(String fk_house_address_id) {
		setAttribute(FK_HOUSE_ADDRESS_ID, fk_house_address_id);
	}

	/**
	 * 获取详细地址
	 * @return
	 */
	public String getDetailed_address() {
		return getAttribute(DETAILED_ADDRESS);
	}

	/**
	 * 设置详细地址
	 * @param detailed_address
	 */
	public void setDetailed_address(String detailed_address) {
		setAttribute(DETAILED_ADDRESS, detailed_address);
	}

	/**
	 * 获取跟进人ID
	 * @return
	 */
	public String getFk_duty_user_id() {
		return getAttribute(FK_DUTY_USER_ID);
	}

	/**
	 * 设置跟进人ID
	 * @param fk_duty_user_id
	 */
	public void setFk_duty_user_id(String fk_duty_user_id) {
		setAttribute(FK_DUTY_USER_ID, fk_duty_user_id);
	}

	/**
	 * 获取跟进人姓名
	 * @return
	 */
	public String getDuty_user_name() {
		return getAttribute(DUTY_USER_NAME);
	}

	/**
	 * 设置跟进人姓名
	 * @param duty_user_name
	 */
	public void setDuty_user_name(String duty_user_name) {
		setAttribute(DUTY_USER_NAME, duty_user_name);
	}

	/**
	 * 获取工单ID
	 * @return
	 */
	public String getFk_details_id() {
		return getAttribute(FK_DETAILS_ID);
	}

	/**
	 * 设置工单ID
	 * @param fk_details_id
	 */
	public void setFk_details_id(String fk_details_id) {
		setAttribute(FK_DETAILS_ID, fk_details_id);
	}

	/**
	 * 获取状态（ 1未处理，2处理中，3处理完成，4已回访，5已关闭）
	 * @return
	 */
	public Integer getState() {
		return getAttribute(STATE);
	}

	/**
	 * 设置状态（ 1未处理，2处理中，3处理完成，4已回访，5已关闭）
	 * @param state
	 */
	public void setState(Integer state) {
		setAttribute(STATE, state);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人ID
	 * @return
	 */
	public String getCreate_user_id() {
		return getAttribute(CREATE_USER_ID);
	}

	/**
	 * 设置创建人ID
	 * @param create_user_id
	 */
	public void setCreate_user_id(String create_user_id) {
		setAttribute(CREATE_USER_ID, create_user_id);
	}

	/**
	 * 获取创建人姓名
	 * @return
	 */
	public String getCreate_user_name() {
		return getAttribute(CREATE_USER_NAME);
	}

	/**
	 * 设置创建人姓名
	 * @param create_user_name
	 */
	public void setCreate_user_name(String create_user_name) {
		setAttribute(CREATE_USER_NAME, create_user_name);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取最后修改人ID
	 * @return
	 */
	public String getUpdate_user_id() {
		return getAttribute(UPDATE_USER_ID);
	}

	/**
	 * 设置最后修改人ID
	 * @param update_user_id
	 */
	public void setUpdate_user_id(String update_user_id) {
		setAttribute(UPDATE_USER_ID, update_user_id);
	}

	/**
	 * 获取最后修改人姓名
	 * @return
	 */
	public String getUpdate_user_name() {
		return getAttribute(UPDATE_USER_NAME);
	}

	/**
	 * 设置最后修改人姓名
	 * @param update_user_name
	 */
	public void setUpdate_user_name(String update_user_name) {
		setAttribute(UPDATE_USER_NAME, update_user_name);
	}

	/**
	 * 获取是否维修
	 * @return
	 */
	public Integer getWhether_repair() {
		return getAttribute(WHETHER_REPAIR);
	}

	/**
	 * 设置是否维修
	 * @param whether_repair
	 */
	public void setWhether_repair(Integer whether_repair) {
		setAttribute(WHETHER_REPAIR, whether_repair);
	}

	/**
	 * 获取完成之间
	 * @return
	 */
	public String getComplete_time() {
		return getAttribute(COMPLETE_TIME);
	}

	/**
	 * 设置完成之间
	 * @param complete_time
	 */
	public void setComplete_time(String complete_time) {
		setAttribute(COMPLETE_TIME, complete_time);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取亿街区报事分类ID存储
	 * @return
	 */
	public String getService_id() {
		return getAttribute(SERVICE_ID);
	}

	/**
	 * 设置亿街区报事分类ID存储
	 * @param service_id
	 */
	public void setService_id(String service_id) {
		setAttribute(SERVICE_ID, service_id);
	}

	/**
	 * 获取亿街区报事类型（1：报事报修， 2：表彰， 3：投诉）
	 * @return
	 */
	public String getRecord_type() {
		return getAttribute(RECORD_TYPE);
	}

	/**
	 * 设置亿街区报事类型（1：报事报修， 2：表彰， 3：投诉）
	 * @param record_type
	 */
	public void setRecord_type(String record_type) {
		setAttribute(RECORD_TYPE, record_type);
	}

	/**
	 * 获取亿街区评价详情
	 * @return
	 */
	public String getYjq_remarks() {
		return getAttribute(YJQ_REMARKS);
	}

	/**
	 * 设置亿街区评价详情
	 * @param yjq_remarks
	 */
	public void setYjq_remarks(String yjq_remarks) {
		setAttribute(YJQ_REMARKS, yjq_remarks);
	}

	/**
	 * 获取亿街区评价等级
	 * @return
	 */
	public String getYjq_level() {
		return getAttribute(YJQ_LEVEL);
	}

	/**
	 * 设置亿街区评价等级
	 * @param yjq_level
	 */
	public void setYjq_level(String yjq_level) {
		setAttribute(YJQ_LEVEL, yjq_level);
	}

	/**
	 * 获取亿街区评价状态（0：未评价；1：已评价）
	 * @return
	 */
	public Integer getYjq_evaluate() {
		return getAttribute(YJQ_EVALUATE);
	}

	/**
	 * 设置亿街区评价状态（0：未评价；1：已评价）
	 * @param yjq_evaluate
	 */
	public void setYjq_evaluate(Integer yjq_evaluate) {
		setAttribute(YJQ_EVALUATE, yjq_evaluate);
	}

	/**
	 * 获取亿街区取消状态(0:未取消；1：已取消)
	 * @return
	 */
	public Integer getYjq_cancel() {
		return getAttribute(YJQ_CANCEL);
	}

	/**
	 * 设置亿街区取消状态(0:未取消；1：已取消)
	 * @param yjq_cancel
	 */
	public void setYjq_cancel(Integer yjq_cancel) {
		setAttribute(YJQ_CANCEL, yjq_cancel);
	}

	/**
	 * 获取亿彩区判重ID
	 * @return
	 */
	public String getYcq_worktaskid() {
		return getAttribute(YCQ_WORKTASKID);
	}

	/**
	 * 设置亿彩区判重ID
	 * @param ycq_worktaskid
	 */
	public void setYcq_worktaskid(String ycq_worktaskid) {
		setAttribute(YCQ_WORKTASKID, ycq_worktaskid);
	}

	/**
	 * 获取亿彩区业主id
	 * @return
	 */
	public String getYcq_yezhuid() {
		return getAttribute(YCQ_YEZHUID);
	}

	/**
	 * 设置亿彩区业主id
	 * @param ycq_yezhuid
	 */
	public void setYcq_yezhuid(String ycq_yezhuid) {
		setAttribute(YCQ_YEZHUID, ycq_yezhuid);
	}

	/**
	 * 获取维修机房
	 * @return
	 */
	public String getFk_repair_equipment_room() {
		return getAttribute(FK_REPAIR_EQUIPMENT_ROOM);
	}

	/**
	 * 设置维修机房
	 * @param fk_repair_equipment_room
	 */
	public void setFk_repair_equipment_room(String fk_repair_equipment_room) {
		setAttribute(FK_REPAIR_EQUIPMENT_ROOM, fk_repair_equipment_room);
	}

	/**
	 * 获取维修设备
	 * @return
	 */
	public String getFk_repair_equipment() {
		return getAttribute(FK_REPAIR_EQUIPMENT);
	}

	/**
	 * 设置维修设备
	 * @param fk_repair_equipment
	 */
	public void setFk_repair_equipment(String fk_repair_equipment) {
		setAttribute(FK_REPAIR_EQUIPMENT, fk_repair_equipment);
	}

}
