/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.quality.proinspect.inspect.insprecord.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 核查与整改记录实体类
 * 
 * @author dms
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class InspectRecordModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_quality_inspectrecord";
	
	/** 记录ID */
	public final static String PK_RECORD = "pk_record";	
	/** 任务ID */
	public final static String FK_TASK = "fk_task";	
	/** 记录状态(0完成，1整改，2整改完成，3整改确认) */
	public final static String RECORD_STATUS = "record_status";	
	/** 扣分 */
	public final static String RECORD_SUBTRACT_SCORE = "record_subtract_score";	
	/** 跟进人 */
	public final static String FOLLOW_USER_PK = "follow_user_pk";	
	/** 问题类型ID */
	public final static String FK_PROBLEM_ID = "fk_problem_id";	
	/** 抽样描述 */
	public final static String RECORD_SAMPLE_DESC = "record_sample_desc";	
	/** 核查结论 */
	public final static String RECORD_INSPECT_RESULT = "record_inspect_result";	
	/** 手机类型（1.android,2.ios） */
	public final static String TASK_PHONETYPE = "task_phonetype";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间(记录提交时间) */
	public final static String CREATE_TIME = "create_time";	
	/** 更新人 */
	public final static String UPDATE_USER = "update_user";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public InspectRecordModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_RECORD;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_RECORD:
			return "pk_record";
		case FK_TASK:
			return "fk_task";
		case RECORD_STATUS:
			return "record_status";
		case RECORD_SUBTRACT_SCORE:
			return "record_subtract_score";
		case FOLLOW_USER_PK:
			return "follow_user_pk";
		case FK_PROBLEM_ID:
			return "fk_problem_id";
		case RECORD_SAMPLE_DESC:
			return "record_sample_desc";
		case RECORD_INSPECT_RESULT:
			return "record_inspect_result";
		case TASK_PHONETYPE:
			return "task_phonetype";
		case CREATE_USER:
			return "create_user";
		case CREATE_TIME:
			return "create_time";
		case UPDATE_USER:
			return "update_user";
		case UPDATE_TIME:
			return "update_time";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取记录ID
	 * @return
	 */
	public String getPk_record() {
		return getAttribute(PK_RECORD);
	}

	/**
	 * 设置记录ID
	 * @param pk_record
	 */
	public void setPk_record(String pk_record) {
		setAttribute(PK_RECORD, pk_record);
	}

	/**
	 * 获取任务ID
	 * @return
	 */
	public String getFk_task() {
		return getAttribute(FK_TASK);
	}

	/**
	 * 设置任务ID
	 * @param fk_task
	 */
	public void setFk_task(String fk_task) {
		setAttribute(FK_TASK, fk_task);
	}

	/**
	 * 获取记录状态(0完成，1整改，2整改完成，3整改确认)
	 * @return
	 */
	public String getRecord_status() {
		return getAttribute(RECORD_STATUS);
	}

	/**
	 * 设置记录状态(0完成，1整改，2整改完成，3整改确认)
	 * @param record_status
	 */
	public void setRecord_status(String record_status) {
		setAttribute(RECORD_STATUS, record_status);
	}

	/**
	 * 获取扣分
	 * @return
	 */
	public BigDecimal getRecord_subtract_score() {
		return getAttribute(RECORD_SUBTRACT_SCORE);
	}

	/**
	 * 设置扣分
	 * @param record_subtract_score
	 */
	public void setRecord_subtract_score(BigDecimal record_subtract_score) {
		setAttribute(RECORD_SUBTRACT_SCORE, record_subtract_score);
	}

	/**
	 * 获取跟进人
	 * @return
	 */
	public String getFollow_user_pk() {
		return getAttribute(FOLLOW_USER_PK);
	}

	/**
	 * 设置跟进人
	 * @param follow_user_pk
	 */
	public void setFollow_user_pk(String follow_user_pk) {
		setAttribute(FOLLOW_USER_PK, follow_user_pk);
	}

	/**
	 * 获取问题类型ID
	 * @return
	 */
	public String getFk_problem_id() {
		return getAttribute(FK_PROBLEM_ID);
	}

	/**
	 * 设置问题类型ID
	 * @param fk_problem_id
	 */
	public void setFk_problem_id(String fk_problem_id) {
		setAttribute(FK_PROBLEM_ID, fk_problem_id);
	}

	/**
	 * 获取抽样描述
	 * @return
	 */
	public String getRecord_sample_desc() {
		return getAttribute(RECORD_SAMPLE_DESC);
	}

	/**
	 * 设置抽样描述
	 * @param record_sample_desc
	 */
	public void setRecord_sample_desc(String record_sample_desc) {
		setAttribute(RECORD_SAMPLE_DESC, record_sample_desc);
	}

	/**
	 * 获取核查结论
	 * @return
	 */
	public String getRecord_inspect_result() {
		return getAttribute(RECORD_INSPECT_RESULT);
	}

	/**
	 * 设置核查结论
	 * @param record_inspect_result
	 */
	public void setRecord_inspect_result(String record_inspect_result) {
		setAttribute(RECORD_INSPECT_RESULT, record_inspect_result);
	}

	/**
	 * 获取手机类型（1.android,2.ios）
	 * @return
	 */
	public String getTask_phonetype() {
		return getAttribute(TASK_PHONETYPE);
	}

	/**
	 * 设置手机类型（1.android,2.ios）
	 * @param task_phonetype
	 */
	public void setTask_phonetype(String task_phonetype) {
		setAttribute(TASK_PHONETYPE, task_phonetype);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间(记录提交时间)
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间(记录提交时间)
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取更新人
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置更新人
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
