/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.system.crop.pre.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 企业信息预采集实体实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class PreCropModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_pre_crop";
	
	/** 主键 */
	public final static String PK_PRE_CROP = "pk_pre_crop";	
	/** 企业编码 */
	public final static String CODE = "code";	
	/** 企业名称 */
	public final static String NAME = "name";	
	/** 联系地址 */
	public final static String ADDRESS = "address";	
	/** 联系电话 */
	public final static String PHONE = "phone";	
	/** 邮政编码 */
	public final static String POST_CODE = "post_code";	
	/** 联系人 */
	public final static String CONTACT = "contact";	
	/** 邮箱 */
	public final static String EMAIL = "email";	
	/** 申请时间 */
	public final static String APPLY_TIME = "apply_time";	
	/** 审核时间 */
	public final static String CHECK_TIME = "check_time";	
	/** 审核人员 */
	public final static String CHECK_USER = "check_user";	
	/** 审核状态 */
	public final static String CHECK_STATE = "check_state";	
	/** 备注 */
	public final static String REMARK = "remark";	

	public PreCropModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_PRE_CROP;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_PRE_CROP:
			return "pk_pre_crop_";
		case CODE:
			return "code_";
		case NAME:
			return "name_";
		case ADDRESS:
			return "address_";
		case PHONE:
			return "phone_";
		case POST_CODE:
			return "post_code_";
		case CONTACT:
			return "contact_";
		case EMAIL:
			return "email_";
		case APPLY_TIME:
			return "apply_time_";
		case CHECK_TIME:
			return "check_time_";
		case CHECK_USER:
			return "check_user_";
		case CHECK_STATE:
			return "check_state_";
		case REMARK:
			return "remark_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_pre_crop() {
		return getAttribute(PK_PRE_CROP);
	}

	/**
	 * 设置主键
	 * @param pk_pre_crop
	 */
	public void setPk_pre_crop(String pk_pre_crop) {
		setAttribute(PK_PRE_CROP, pk_pre_crop);
	}

	/**
	 * 获取企业编码
	 * @return
	 */
	public String getCode() {
		return getAttribute(CODE);
	}

	/**
	 * 设置企业编码
	 * @param code
	 */
	public void setCode(String code) {
		setAttribute(CODE, code);
	}

	/**
	 * 获取企业名称
	 * @return
	 */
	public String getName() {
		return getAttribute(NAME);
	}

	/**
	 * 设置企业名称
	 * @param name
	 */
	public void setName(String name) {
		setAttribute(NAME, name);
	}

	/**
	 * 获取联系地址
	 * @return
	 */
	public String getAddress() {
		return getAttribute(ADDRESS);
	}

	/**
	 * 设置联系地址
	 * @param address
	 */
	public void setAddress(String address) {
		setAttribute(ADDRESS, address);
	}

	/**
	 * 获取联系电话
	 * @return
	 */
	public String getPhone() {
		return getAttribute(PHONE);
	}

	/**
	 * 设置联系电话
	 * @param phone
	 */
	public void setPhone(String phone) {
		setAttribute(PHONE, phone);
	}

	/**
	 * 获取邮政编码
	 * @return
	 */
	public String getPost_code() {
		return getAttribute(POST_CODE);
	}

	/**
	 * 设置邮政编码
	 * @param post_code
	 */
	public void setPost_code(String post_code) {
		setAttribute(POST_CODE, post_code);
	}

	/**
	 * 获取联系人
	 * @return
	 */
	public String getContact() {
		return getAttribute(CONTACT);
	}

	/**
	 * 设置联系人
	 * @param contact
	 */
	public void setContact(String contact) {
		setAttribute(CONTACT, contact);
	}

	/**
	 * 获取邮箱
	 * @return
	 */
	public String getEmail() {
		return getAttribute(EMAIL);
	}

	/**
	 * 设置邮箱
	 * @param email
	 */
	public void setEmail(String email) {
		setAttribute(EMAIL, email);
	}

	/**
	 * 获取申请时间
	 * @return
	 */
	public String getApply_time() {
		return getAttribute(APPLY_TIME);
	}

	/**
	 * 设置申请时间
	 * @param apply_time
	 */
	public void setApply_time(String apply_time) {
		setAttribute(APPLY_TIME, apply_time);
	}

	/**
	 * 获取审核时间
	 * @return
	 */
	public String getCheck_time() {
		return getAttribute(CHECK_TIME);
	}

	/**
	 * 设置审核时间
	 * @param check_time
	 */
	public void setCheck_time(String check_time) {
		setAttribute(CHECK_TIME, check_time);
	}

	/**
	 * 获取审核人员
	 * @return
	 */
	public String getCheck_user() {
		return getAttribute(CHECK_USER);
	}

	/**
	 * 设置审核人员
	 * @param check_user
	 */
	public void setCheck_user(String check_user) {
		setAttribute(CHECK_USER, check_user);
	}

	/**
	 * 获取审核状态
	 * @return
	 */
	public String getCheck_state() {
		return getAttribute(CHECK_STATE);
	}

	/**
	 * 设置审核状态
	 * @param check_state
	 */
	public void setCheck_state(String check_state) {
		setAttribute(CHECK_STATE, check_state);
	}

	/**
	 * 获取备注
	 * @return
	 */
	public String getRemark() {
		return getAttribute(REMARK);
	}

	/**
	 * 设置备注
	 * @param remark
	 */
	public void setRemark(String remark) {
		setAttribute(REMARK, remark);
	}

}
