/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.pub.feedback.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * app的意见反馈实体类
 * 
 * @author yuting.wang
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYFeedbackModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_pub_feedback";
	
	/** 意见反馈主键 */
	public final static String PK_FEEDBACK = "pk_feedback";	
	/** 反馈类型 */
	public final static String FEEDBACK_TYPE = "feedback_type";	
	/** 反馈系统 */
	public final static String FEEDBACK_SYSTEM = "feedback_system";	
	/** 反馈功能 */
	public final static String FEEDBACK_FUNCTION = "feedback_function";	
	/** 反馈人id */
	public final static String FK_FEECBACK_USER = "fk_feecback_user";	
	/** 联系电话 */
	public final static String FEEDBACK_PHONE = "feedback_phone";	
	/** 意见建议 */
	public final static String FEEDBACK_DESC = "feedback_desc";	
	/** 创建时间 */
	public final static String CREAT_TIME = "creat_time";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 更新人 */
	public final static String UPDATE_USER = "update_user";	

	public YJWYFeedbackModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_FEEDBACK;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_FEEDBACK:
			return "pk_feedback";
		case FEEDBACK_TYPE:
			return "feedback_type";
		case FEEDBACK_SYSTEM:
			return "feedback_system";
		case FEEDBACK_FUNCTION:
			return "feedback_function";
		case FK_FEECBACK_USER:
			return "fk_feecback_user";
		case FEEDBACK_PHONE:
			return "feedback_phone";
		case FEEDBACK_DESC:
			return "feedback_desc";
		case CREAT_TIME:
			return "creat_time";
		case CREATE_USER:
			return "create_user";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER:
			return "update_user";
		}
		return null;
	}

	/**
	 * 获取意见反馈主键
	 * @return
	 */
	public String getPk_feedback() {
		return getAttribute(PK_FEEDBACK);
	}

	/**
	 * 设置意见反馈主键
	 * @param pk_feedback
	 */
	public void setPk_feedback(String pk_feedback) {
		setAttribute(PK_FEEDBACK, pk_feedback);
	}

	/**
	 * 获取反馈类型
	 * @return
	 */
	public String getFeedback_type() {
		return getAttribute(FEEDBACK_TYPE);
	}

	/**
	 * 设置反馈类型
	 * @param feedback_type
	 */
	public void setFeedback_type(String feedback_type) {
		setAttribute(FEEDBACK_TYPE, feedback_type);
	}

	/**
	 * 获取反馈系统
	 * @return
	 */
	public String getFeedback_system() {
		return getAttribute(FEEDBACK_SYSTEM);
	}

	/**
	 * 设置反馈系统
	 * @param feedback_system
	 */
	public void setFeedback_system(String feedback_system) {
		setAttribute(FEEDBACK_SYSTEM, feedback_system);
	}

	/**
	 * 获取反馈功能
	 * @return
	 */
	public String getFeedback_function() {
		return getAttribute(FEEDBACK_FUNCTION);
	}

	/**
	 * 设置反馈功能
	 * @param feedback_function
	 */
	public void setFeedback_function(String feedback_function) {
		setAttribute(FEEDBACK_FUNCTION, feedback_function);
	}

	/**
	 * 获取反馈人id
	 * @return
	 */
	public String getFk_feecback_user() {
		return getAttribute(FK_FEECBACK_USER);
	}

	/**
	 * 设置反馈人id
	 * @param fk_feecback_user
	 */
	public void setFk_feecback_user(String fk_feecback_user) {
		setAttribute(FK_FEECBACK_USER, fk_feecback_user);
	}

	/**
	 * 获取联系电话
	 * @return
	 */
	public String getFeedback_phone() {
		return getAttribute(FEEDBACK_PHONE);
	}

	/**
	 * 设置联系电话
	 * @param feedback_phone
	 */
	public void setFeedback_phone(String feedback_phone) {
		setAttribute(FEEDBACK_PHONE, feedback_phone);
	}

	/**
	 * 获取意见建议
	 * @return
	 */
	public String getFeedback_desc() {
		return getAttribute(FEEDBACK_DESC);
	}

	/**
	 * 设置意见建议
	 * @param feedback_desc
	 */
	public void setFeedback_desc(String feedback_desc) {
		setAttribute(FEEDBACK_DESC, feedback_desc);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreat_time() {
		return getAttribute(CREAT_TIME);
	}

	/**
	 * 设置创建时间
	 * @param creat_time
	 */
	public void setCreat_time(String creat_time) {
		setAttribute(CREAT_TIME, creat_time);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取更新人
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置更新人
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

}
