/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.assistuser.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 工单协助人表实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskAssistUserRecordModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_assist_user_record";
	
	/** 主键ID */
	public final static String PK_RECORD_ID = "pk_record_id";	
	/** 工单ID */
	public final static String FK_DETAILS_ID = "fk_details_id";	
	/** 用户表ID */
	public final static String FK_USER_ID = "fk_user_id";	
	/** 工作百分比 */
	public final static String WORK_PROPORTION = "work_proportion";	
	/** 记录时间 */
	public final static String RECORD_TIME = "record_time";	
	/** 记录人ID */
	public final static String RECORD_USER_ID = "record_user_id";	

	public YJWYWorkTaskAssistUserRecordModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_RECORD_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_RECORD_ID:
			return "pk_record_id";
		case FK_DETAILS_ID:
			return "fk_details_id";
		case FK_USER_ID:
			return "fk_user_id";
		case WORK_PROPORTION:
			return "work_proportion";
		case RECORD_TIME:
			return "record_time";
		case RECORD_USER_ID:
			return "record_user_id";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_record_id() {
		return getAttribute(PK_RECORD_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_record_id
	 */
	public void setPk_record_id(String pk_record_id) {
		setAttribute(PK_RECORD_ID, pk_record_id);
	}

	/**
	 * 获取工单ID
	 * @return
	 */
	public String getFk_details_id() {
		return getAttribute(FK_DETAILS_ID);
	}

	/**
	 * 设置工单ID
	 * @param fk_details_id
	 */
	public void setFk_details_id(String fk_details_id) {
		setAttribute(FK_DETAILS_ID, fk_details_id);
	}

	/**
	 * 获取用户表ID
	 * @return
	 */
	public String getFk_user_id() {
		return getAttribute(FK_USER_ID);
	}

	/**
	 * 设置用户表ID
	 * @param fk_user_id
	 */
	public void setFk_user_id(String fk_user_id) {
		setAttribute(FK_USER_ID, fk_user_id);
	}

	/**
	 * 获取工作百分比
	 * @return
	 */
	public BigDecimal getWork_proportion() {
		return getAttribute(WORK_PROPORTION);
	}

	/**
	 * 设置工作百分比
	 * @param work_proportion
	 */
	public void setWork_proportion(BigDecimal work_proportion) {
		setAttribute(WORK_PROPORTION, work_proportion);
	}

	/**
	 * 获取记录时间
	 * @return
	 */
	public String getRecord_time() {
		return getAttribute(RECORD_TIME);
	}

	/**
	 * 设置记录时间
	 * @param record_time
	 */
	public void setRecord_time(String record_time) {
		setAttribute(RECORD_TIME, record_time);
	}

	/**
	 * 获取记录人ID
	 * @return
	 */
	public String getRecord_user_id() {
		return getAttribute(RECORD_USER_ID);
	}

	/**
	 * 设置记录人ID
	 * @param record_user_id
	 */
	public void setRecord_user_id(String record_user_id) {
		setAttribute(RECORD_USER_ID, record_user_id);
	}

}
