/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.fmdata.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 设备设施基本信息实体类
 * 
 * @author liping.dai
 * @version since Shareworx platform 2.0
 */
public class YJWYEqModel extends DomainModel {

	private static final long serialVersionUID = 1L;
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_fmdata_eq";
	
	/** 设备主键id */
	public final static String EQ_ID = "eq_id";	
	/** 长描述 */
	public final static String LONG_DESCRIPTION = "long_description";	
	/** 分类编码 */
	public final static String CSI_ID = "csi_id";	
	/** 设备编号 */
	public final static String FM_CODE = "fm_code";	
	/** 设备名称/描述 */
	public final static String NAME = "name";	
	/** 功率KW */
	public final static String POWER = "power";	
	/** 品牌 */
	public final static String BRAND = "brand";	
	/** 规格型号 */
	public final static String MODEL = "model";	
	/** 厂家 */
	public final static String FACTORY = "factory";	
	/** 使用部门 */
	public final static String USE_DEPT = "use_dept";	
	/** 维护部门 */
	public final static String SERVICE_DEPT = "service_dept";	
	/** 参数1 */
	public final static String PARAMETER1 = "parameter1";	
	/** 参数2 */
	public final static String PARAMETER2 = "parameter2";	
	/** 项目代码 */
	public final static String SITE_ID = "site_id";	
	/** 设备惯用名 */
	public final static String USE_NAME = "use_name";	
	/** 设备状态 */
	public final static String STATUS = "status";	
	/** 房间编号（位置编号） */
	public final static String RM_ID = "rm_id";	
	/** 更新时间 */
	public final static String DMS_UPDATE_TIME = "dms_update_time";	
	/** 是否有效 */
	public final static String FLAG = "flag";	
	/** 报废 */
	public final static String ACTIVE = "active";	
	/** 列表显示编码 */
	public final static String LIST_CODE = "list_code";	
	/** 惯用名称 */
	public final static String USUAL_NAME = "usual_name";	
	/** 设备描述 */
	public final static String EQ_DESCRIPTION = "eq_description";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** BIM关联编码 */
	public final static String EQ_CODE = "eq_code";	
	/** 设备所属系统ID */
	public final static String FK_EQ_SYS_ID = "fk_eq_sys_id";	
	/** 设备所属系统名称 */
	public final static String EQ_SYS_NAME = "eq_sys_name";	
	/** 设备系统ID树 */
	public final static String FK_SYS_ALL_IDS = "fk_sys_all_ids";	
	/** 创建人 */
	public final static String CREATE_BY = "create_by";	
	/** 创建时间 */
	public final static String CREATE_DATE = "create_date";	
	/** 最近修改人 */
	public final static String LAST_MODIFY_USER = "last_modify_user";	
	/** 最近修改时间 */
	public final static String LAST_MODIFY_TIME = "last_modify_time";	
	/** 是否有用 */
	public final static String DELETE_FLAG = "delete_flag";	
	/** 更新时间戳 */
	public final static String UPDATE_DATE = "update_date";	

	public YJWYEqModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return EQ_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case EQ_ID:
			return "eq_id";
		case LONG_DESCRIPTION:
			return "long_description";
		case CSI_ID:
			return "csi_id";
		case FM_CODE:
			return "fm_code";
		case NAME:
			return "name";
		case POWER:
			return "power";
		case BRAND:
			return "brand";
		case MODEL:
			return "model";
		case FACTORY:
			return "factory";
		case USE_DEPT:
			return "use_dept";
		case SERVICE_DEPT:
			return "service_dept";
		case PARAMETER1:
			return "parameter1";
		case PARAMETER2:
			return "parameter2";
		case SITE_ID:
			return "site_id";
		case USE_NAME:
			return "use_name";
		case STATUS:
			return "status";
		case RM_ID:
			return "rm_id";
		case DMS_UPDATE_TIME:
			return "dms_update_time";
		case FLAG:
			return "flag";
		case ACTIVE:
			return "active";
		case LIST_CODE:
			return "list_code";
		case USUAL_NAME:
			return "usual_name";
		case EQ_DESCRIPTION:
			return "eq_description";
		case PK_CROP:
			return "pk_crop";
		case EQ_CODE:
			return "eq_code_";
		case FK_EQ_SYS_ID:
			return "fk_eq_sys_id";
		case EQ_SYS_NAME:
			return "eq_sys_name";
		case FK_SYS_ALL_IDS:
			return "fk_sys_all_ids";
		case CREATE_BY:
			return "create_by";
		case CREATE_DATE:
			return "create_date";
		case LAST_MODIFY_USER:
			return "last_modify_user";
		case LAST_MODIFY_TIME:
			return "last_modify_time";
		case DELETE_FLAG:
			return "delete_flag";
		case UPDATE_DATE:
			return "update_date";
		}
		return null;
	}

	/**
	 * 获取设备主键id
	 * @return
	 */
	public String getEq_id() {
		return getAttribute(EQ_ID);
	}

	/**
	 * 设置设备主键id
	 * @param eq_id
	 */
	public void setEq_id(String eq_id) {
		setAttribute(EQ_ID, eq_id);
	}

	/**
	 * 获取长描述
	 * @return
	 */
	public String getLong_description() {
		return getAttribute(LONG_DESCRIPTION);
	}

	/**
	 * 设置长描述
	 * @param long_description
	 */
	public void setLong_description(String long_description) {
		setAttribute(LONG_DESCRIPTION, long_description);
	}

	/**
	 * 获取分类编码
	 * @return
	 */
	public String getCsi_id() {
		return getAttribute(CSI_ID);
	}

	/**
	 * 设置分类编码
	 * @param csi_id
	 */
	public void setCsi_id(String csi_id) {
		setAttribute(CSI_ID, csi_id);
	}

	/**
	 * 获取设备编号
	 * @return
	 */
	public String getFm_code() {
		return getAttribute(FM_CODE);
	}

	/**
	 * 设置设备编号
	 * @param fm_code
	 */
	public void setFm_code(String fm_code) {
		setAttribute(FM_CODE, fm_code);
	}

	/**
	 * 获取设备名称/描述
	 * @return
	 */
	public String getName() {
		return getAttribute(NAME);
	}

	/**
	 * 设置设备名称/描述
	 * @param name
	 */
	public void setName(String name) {
		setAttribute(NAME, name);
	}

	/**
	 * 获取功率KW
	 * @return
	 */
	public String getPower() {
		return getAttribute(POWER);
	}

	/**
	 * 设置功率KW
	 * @param power
	 */
	public void setPower(String power) {
		setAttribute(POWER, power);
	}

	/**
	 * 获取品牌
	 * @return
	 */
	public String getBrand() {
		return getAttribute(BRAND);
	}

	/**
	 * 设置品牌
	 * @param brand
	 */
	public void setBrand(String brand) {
		setAttribute(BRAND, brand);
	}

	/**
	 * 获取规格型号
	 * @return
	 */
	public String getModel() {
		return getAttribute(MODEL);
	}

	/**
	 * 设置规格型号
	 * @param model
	 */
	public void setModel(String model) {
		setAttribute(MODEL, model);
	}

	/**
	 * 获取厂家
	 * @return
	 */
	public String getFactory() {
		return getAttribute(FACTORY);
	}

	/**
	 * 设置厂家
	 * @param factory
	 */
	public void setFactory(String factory) {
		setAttribute(FACTORY, factory);
	}

	/**
	 * 获取使用部门
	 * @return
	 */
	public String getUse_dept() {
		return getAttribute(USE_DEPT);
	}

	/**
	 * 设置使用部门
	 * @param use_dept
	 */
	public void setUse_dept(String use_dept) {
		setAttribute(USE_DEPT, use_dept);
	}

	/**
	 * 获取维护部门
	 * @return
	 */
	public String getService_dept() {
		return getAttribute(SERVICE_DEPT);
	}

	/**
	 * 设置维护部门
	 * @param service_dept
	 */
	public void setService_dept(String service_dept) {
		setAttribute(SERVICE_DEPT, service_dept);
	}

	/**
	 * 获取参数1
	 * @return
	 */
	public String getParameter1() {
		return getAttribute(PARAMETER1);
	}

	/**
	 * 设置参数1
	 * @param parameter1
	 */
	public void setParameter1(String parameter1) {
		setAttribute(PARAMETER1, parameter1);
	}

	/**
	 * 获取参数2
	 * @return
	 */
	public String getParameter2() {
		return getAttribute(PARAMETER2);
	}

	/**
	 * 设置参数2
	 * @param parameter2
	 */
	public void setParameter2(String parameter2) {
		setAttribute(PARAMETER2, parameter2);
	}

	/**
	 * 获取项目代码
	 * @return
	 */
	public String getSite_id() {
		return getAttribute(SITE_ID);
	}

	/**
	 * 设置项目代码
	 * @param site_id
	 */
	public void setSite_id(String site_id) {
		setAttribute(SITE_ID, site_id);
	}

	/**
	 * 获取设备惯用名
	 * @return
	 */
	public String getUse_name() {
		return getAttribute(USE_NAME);
	}

	/**
	 * 设置设备惯用名
	 * @param use_name
	 */
	public void setUse_name(String use_name) {
		setAttribute(USE_NAME, use_name);
	}

	/**
	 * 获取设备状态
	 * @return
	 */
	public String getStatus() {
		return getAttribute(STATUS);
	}

	/**
	 * 设置设备状态
	 * @param status
	 */
	public void setStatus(String status) {
		setAttribute(STATUS, status);
	}

	/**
	 * 获取房间编号（位置编号）
	 * @return
	 */
	public String getRm_id() {
		return getAttribute(RM_ID);
	}

	/**
	 * 设置房间编号（位置编号）
	 * @param rm_id
	 */
	public void setRm_id(String rm_id) {
		setAttribute(RM_ID, rm_id);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getDms_update_time() {
		return getAttribute(DMS_UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param dms_update_time
	 */
	public void setDms_update_time(String dms_update_time) {
		setAttribute(DMS_UPDATE_TIME, dms_update_time);
	}

	/**
	 * 获取是否有效
	 * @return
	 */
	public Integer getFlag() {
		return getAttribute(FLAG);
	}

	/**
	 * 设置是否有效
	 * @param flag
	 */
	public void setFlag(Integer flag) {
		setAttribute(FLAG, flag);
	}

	/**
	 * 获取报废
	 * @return
	 */
	public Integer getActive() {
		return getAttribute(ACTIVE);
	}

	/**
	 * 设置报废
	 * @param active
	 */
	public void setActive(Integer active) {
		setAttribute(ACTIVE, active);
	}

	/**
	 * 获取列表显示编码
	 * @return
	 */
	public String getList_code() {
		return getAttribute(LIST_CODE);
	}

	/**
	 * 设置列表显示编码
	 * @param list_code
	 */
	public void setList_code(String list_code) {
		setAttribute(LIST_CODE, list_code);
	}

	/**
	 * 获取惯用名称
	 * @return
	 */
	public String getUsual_name() {
		return getAttribute(USUAL_NAME);
	}

	/**
	 * 设置惯用名称
	 * @param usual_name
	 */
	public void setUsual_name(String usual_name) {
		setAttribute(USUAL_NAME, usual_name);
	}

	/**
	 * 获取设备描述
	 * @return
	 */
	public String getEq_description() {
		return getAttribute(EQ_DESCRIPTION);
	}

	/**
	 * 设置设备描述
	 * @param eq_description
	 */
	public void setEq_description(String eq_description) {
		setAttribute(EQ_DESCRIPTION, eq_description);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取BIM关联编码
	 * @return
	 */
	public String getEq_code() {
		return getAttribute(EQ_CODE);
	}

	/**
	 * 设置BIM关联编码
	 * @param eq_code
	 */
	public void setEq_code(String eq_code) {
		setAttribute(EQ_CODE, eq_code);
	}

	/**
	 * 获取设备所属系统ID
	 * @return
	 */
	public String getFk_eq_sys_id() {
		return getAttribute(FK_EQ_SYS_ID);
	}

	/**
	 * 设置设备所属系统ID
	 * @param fk_eq_sys_id
	 */
	public void setFk_eq_sys_id(String fk_eq_sys_id) {
		setAttribute(FK_EQ_SYS_ID, fk_eq_sys_id);
	}

	/**
	 * 获取设备所属系统名称
	 * @return
	 */
	public String getEq_sys_name() {
		return getAttribute(EQ_SYS_NAME);
	}

	/**
	 * 设置设备所属系统名称
	 * @param eq_sys_name
	 */
	public void setEq_sys_name(String eq_sys_name) {
		setAttribute(EQ_SYS_NAME, eq_sys_name);
	}

	/**
	 * 获取设备系统ID树
	 * @return
	 */
	public String getFk_sys_all_ids() {
		return getAttribute(FK_SYS_ALL_IDS);
	}

	/**
	 * 设置设备系统ID树
	 * @param fk_sys_all_ids
	 */
	public void setFk_sys_all_ids(String fk_sys_all_ids) {
		setAttribute(FK_SYS_ALL_IDS, fk_sys_all_ids);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_by() {
		return getAttribute(CREATE_BY);
	}

	/**
	 * 设置创建人
	 * @param create_by
	 */
	public void setCreate_by(String create_by) {
		setAttribute(CREATE_BY, create_by);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_date() {
		return getAttribute(CREATE_DATE);
	}

	/**
	 * 设置创建时间
	 * @param create_date
	 */
	public void setCreate_date(String create_date) {
		setAttribute(CREATE_DATE, create_date);
	}

	/**
	 * 获取最近修改人
	 * @return
	 */
	public String getLast_modify_user() {
		return getAttribute(LAST_MODIFY_USER);
	}

	/**
	 * 设置最近修改人
	 * @param last_modify_user
	 */
	public void setLast_modify_user(String last_modify_user) {
		setAttribute(LAST_MODIFY_USER, last_modify_user);
	}

	/**
	 * 获取最近修改时间
	 * @return
	 */
	public String getLast_modify_time() {
		return getAttribute(LAST_MODIFY_TIME);
	}

	/**
	 * 设置最近修改时间
	 * @param last_modify_time
	 */
	public void setLast_modify_time(String last_modify_time) {
		setAttribute(LAST_MODIFY_TIME, last_modify_time);
	}

	/**
	 * 获取是否有用
	 * @return
	 */
	public Integer getDelete_flag() {
		return getAttribute(DELETE_FLAG);
	}

	/**
	 * 设置是否有用
	 * @param delete_flag
	 */
	public void setDelete_flag(Integer delete_flag) {
		setAttribute(DELETE_FLAG, delete_flag);
	}

	/**
	 * 获取更新时间戳
	 * @return
	 */
	public String getUpdate_date() {
		return getAttribute(UPDATE_DATE);
	}

	/**
	 * 设置更新时间戳
	 * @param update_date
	 */
	public void setUpdate_date(String update_date) {
		setAttribute(UPDATE_DATE, update_date);
	}

}
