/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.fmdata.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 工艺程序主表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYPmpModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_fmdata_pmp";
	
	/** 程序id */
	public final static String PMP_ID = "pmp_id";	
	/** 程序名称 */
	public final static String DESCRIPTION = "description";	
	/** 作业类型 */
	public final static String BUS_TYPE = "bus_type";	
	/** 设备/设施 */
	public final static String PMP_TYPE = "pmp_type";	
	/** 有效标识 */
	public final static String FLAG = "flag";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYPmpModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PMP_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PMP_ID:
			return "pmp_id";
		case DESCRIPTION:
			return "description";
		case BUS_TYPE:
			return "bus_type";
		case PMP_TYPE:
			return "pmp_type";
		case FLAG:
			return "flag";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取程序id
	 * @return
	 */
	public Integer getPmp_id() {
		return getAttribute(PMP_ID);
	}

	/**
	 * 设置程序id
	 * @param pmp_id
	 */
	public void setPmp_id(Integer pmp_id) {
		setAttribute(PMP_ID, pmp_id);
	}

	/**
	 * 获取程序名称
	 * @return
	 */
	public String getDescription() {
		return getAttribute(DESCRIPTION);
	}

	/**
	 * 设置程序名称
	 * @param description
	 */
	public void setDescription(String description) {
		setAttribute(DESCRIPTION, description);
	}

	/**
	 * 获取作业类型
	 * @return
	 */
	public String getBus_type() {
		return getAttribute(BUS_TYPE);
	}

	/**
	 * 设置作业类型
	 * @param bus_type
	 */
	public void setBus_type(String bus_type) {
		setAttribute(BUS_TYPE, bus_type);
	}

	/**
	 * 获取设备/设施
	 * @return
	 */
	public String getPmp_type() {
		return getAttribute(PMP_TYPE);
	}

	/**
	 * 设置设备/设施
	 * @param pmp_type
	 */
	public void setPmp_type(String pmp_type) {
		setAttribute(PMP_TYPE, pmp_type);
	}

	/**
	 * 获取有效标识
	 * @return
	 */
	public Integer getFlag() {
		return getAttribute(FLAG);
	}

	/**
	 * 设置有效标识
	 * @param flag
	 */
	public void setFlag(Integer flag) {
		setAttribute(FLAG, flag);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
