/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.patrol.task.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 巡检维保任务表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYTaskModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_patrol_task";
	
	/** 主键任务id */
	public final static String TASK_ID = "task_id";	
	/** 计划id */
	public final static String PLAN_ID = "plan_id";	
	/** 计划名称 */
	public final static String PLAN_NAME = "plan_name";	
	/** 巡检/维保人（执行人） */
	public final static String EXECUTOR_ID = "executor_id";	
	/** 开始时间（任务有效期） */
	public final static String BEGIN_TIME = "begin_time";	
	/** 结束时间（任务有效期） */
	public final static String END_TIME = "end_time";	
	/** 完成时间（任务完成） */
	public final static String FINISH_TIME = "finish_time";	
	/** 任务状态0：未完成；1：已完成；2：已过期；3：转发；4：保养中；5：销单；6：未派单 */
	public final static String TASK_STATE = "task_state";	
	/** 任务类型0：巡检；1： 维保 */
	public final static String TASK_TYPE = "task_type";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人id */
	public final static String CREATE_USER = "create_user";	
	/** 修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 修改人id */
	public final static String UPDATE_USER = "update_user";	
	/** 巡检/维保结果0：异常；1：正常；2：空 */
	public final static String TASK_RESULT = "task_result";	
	/** 处理情况0：派单；1：正常 */
	public final static String TASK_DEALT = "task_dealt";	
	/** 任务备注 */
	public final static String TASK_DESC = "task_desc";	

	public YJWYTaskModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return TASK_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case TASK_ID:
			return "task_id";
		case PLAN_ID:
			return "plan_id";
		case PLAN_NAME:
			return "plan_name";
		case EXECUTOR_ID:
			return "executor_id";
		case BEGIN_TIME:
			return "begin_time";
		case END_TIME:
			return "end_time";
		case FINISH_TIME:
			return "finish_time";
		case TASK_STATE:
			return "task_state";
		case TASK_TYPE:
			return "task_type";
		case PK_CROP:
			return "pk_crop";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER:
			return "create_user";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER:
			return "update_user";
		case TASK_RESULT:
			return "task_result";
		case TASK_DEALT:
			return "task_dealt";
		case TASK_DESC:
			return "task_desc";
		}
		return null;
	}

	/**
	 * 获取主键任务id
	 * @return
	 */
	public String getTask_id() {
		return getAttribute(TASK_ID);
	}

	/**
	 * 设置主键任务id
	 * @param task_id
	 */
	public void setTask_id(String task_id) {
		setAttribute(TASK_ID, task_id);
	}

	/**
	 * 获取计划id
	 * @return
	 */
	public String getPlan_id() {
		return getAttribute(PLAN_ID);
	}

	/**
	 * 设置计划id
	 * @param plan_id
	 */
	public void setPlan_id(String plan_id) {
		setAttribute(PLAN_ID, plan_id);
	}

	/**
	 * 获取计划名称
	 * @return
	 */
	public String getPlan_name() {
		return getAttribute(PLAN_NAME);
	}

	/**
	 * 设置计划名称
	 * @param plan_name
	 */
	public void setPlan_name(String plan_name) {
		setAttribute(PLAN_NAME, plan_name);
	}

	/**
	 * 获取巡检/维保人（执行人）
	 * @return
	 */
	public String getExecutor_id() {
		return getAttribute(EXECUTOR_ID);
	}

	/**
	 * 设置巡检/维保人（执行人）
	 * @param executor_id
	 */
	public void setExecutor_id(String executor_id) {
		setAttribute(EXECUTOR_ID, executor_id);
	}

	/**
	 * 获取开始时间（任务有效期）
	 * @return
	 */
	public String getBegin_time() {
		return getAttribute(BEGIN_TIME);
	}

	/**
	 * 设置开始时间（任务有效期）
	 * @param begin_time
	 */
	public void setBegin_time(String begin_time) {
		setAttribute(BEGIN_TIME, begin_time);
	}

	/**
	 * 获取结束时间（任务有效期）
	 * @return
	 */
	public String getEnd_time() {
		return getAttribute(END_TIME);
	}

	/**
	 * 设置结束时间（任务有效期）
	 * @param end_time
	 */
	public void setEnd_time(String end_time) {
		setAttribute(END_TIME, end_time);
	}

	/**
	 * 获取完成时间（任务完成）
	 * @return
	 */
	public String getFinish_time() {
		return getAttribute(FINISH_TIME);
	}

	/**
	 * 设置完成时间（任务完成）
	 * @param finish_time
	 */
	public void setFinish_time(String finish_time) {
		setAttribute(FINISH_TIME, finish_time);
	}

	/**
	 * 获取任务状态0：未完成；1：已完成；2：已过期；3：转发；4：保养中；5：销单；6：未派单
	 * @return
	 */
	public Integer getTask_state() {
		return getAttribute(TASK_STATE);
	}

	/**
	 * 设置任务状态0：未完成；1：已完成；2：已过期；3：转发；4：保养中；5：销单；6：未派单
	 * @param task_state
	 */
	public void setTask_state(Integer task_state) {
		setAttribute(TASK_STATE, task_state);
	}

	/**
	 * 获取任务类型0：巡检；1： 维保
	 * @return
	 */
	public Integer getTask_type() {
		return getAttribute(TASK_TYPE);
	}

	/**
	 * 设置任务类型0：巡检；1： 维保
	 * @param task_type
	 */
	public void setTask_type(Integer task_type) {
		setAttribute(TASK_TYPE, task_type);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人id
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人id
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取修改人id
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置修改人id
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

	/**
	 * 获取巡检/维保结果0：异常；1：正常；2：空
	 * @return
	 */
	public Integer getTask_result() {
		return getAttribute(TASK_RESULT);
	}

	/**
	 * 设置巡检/维保结果0：异常；1：正常；2：空
	 * @param task_result
	 */
	public void setTask_result(Integer task_result) {
		setAttribute(TASK_RESULT, task_result);
	}

	/**
	 * 获取处理情况0：派单；1：正常
	 * @return
	 */
	public Integer getTask_dealt() {
		return getAttribute(TASK_DEALT);
	}

	/**
	 * 设置处理情况0：派单；1：正常
	 * @param task_dealt
	 */
	public void setTask_dealt(Integer task_dealt) {
		setAttribute(TASK_DEALT, task_dealt);
	}

	/**
	 * 获取任务备注
	 * @return
	 */
	public String getTask_desc() {
		return getAttribute(TASK_DESC);
	}

	/**
	 * 设置任务备注
	 * @param task_desc
	 */
	public void setTask_desc(String task_desc) {
		setAttribute(TASK_DESC, task_desc);
	}

}
