/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.quality.proinspect.inspect.probtype.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 问题类型实体类
 * 
 * @author dms
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class ProblemTypeModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_quality_problemtype";
	
	/** 主键ID */
	public final static String PK_PROBLEM = "pk_problem";	
	/** 问题类型NAME */
	public final static String PROBLEM_NAME = "problem_name";	
	/** 问题整改天数 */
	public final static String PROBLEM_RECTIFY_DAYS = "problem_rectify_days";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 更新人 */
	public final static String UPDATE_USER = "update_user";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 是否有效的 */
	public final static String IS_VALID = "is_valid";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public ProblemTypeModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_PROBLEM;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_PROBLEM:
			return "pk_problem";
		case PROBLEM_NAME:
			return "problem_name";
		case PROBLEM_RECTIFY_DAYS:
			return "problem_rectify_days";
		case CREATE_USER:
			return "create_user";
		case CREATE_TIME:
			return "create_time";
		case UPDATE_USER:
			return "update_user";
		case UPDATE_TIME:
			return "update_time";
		case IS_VALID:
			return "is_valid";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_problem() {
		return getAttribute(PK_PROBLEM);
	}

	/**
	 * 设置主键ID
	 * @param pk_problem
	 */
	public void setPk_problem(String pk_problem) {
		setAttribute(PK_PROBLEM, pk_problem);
	}

	/**
	 * 获取问题类型NAME
	 * @return
	 */
	public String getProblem_name() {
		return getAttribute(PROBLEM_NAME);
	}

	/**
	 * 设置问题类型NAME
	 * @param problem_name
	 */
	public void setProblem_name(String problem_name) {
		setAttribute(PROBLEM_NAME, problem_name);
	}

	/**
	 * 获取问题整改天数
	 * @return
	 */
	public Integer getProblem_rectify_days() {
		return getAttribute(PROBLEM_RECTIFY_DAYS);
	}

	/**
	 * 设置问题整改天数
	 * @param problem_rectify_days
	 */
	public void setProblem_rectify_days(Integer problem_rectify_days) {
		setAttribute(PROBLEM_RECTIFY_DAYS, problem_rectify_days);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取更新人
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置更新人
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取是否有效的
	 * @return
	 */
	public String getIs_valid() {
		return getAttribute(IS_VALID);
	}

	/**
	 * 设置是否有效的
	 * @param is_valid
	 */
	public void setIs_valid(String is_valid) {
		setAttribute(IS_VALID, is_valid);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
