/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.saas.payment.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 缴费实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class PaymentModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_saas_payment";
	
	/** 主键 */
	public final static String PK_PAYMENT = "pk_payment";	
	/** 企业主键 */
	public final static String PK_CROP = "pk_crop";	
	/** 缴费日期 */
	public final static String PAYMENT_DATE = "payment_date";	
	/** 缴费金额 */
	public final static String PAYMENT_AMOUNT = "payment_amount";	
	/** 经办人 */
	public final static String PK_USER = "pk_user";	
	/** 备注 */
	public final static String REMARK = "remark";	

	public PaymentModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_PAYMENT;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_PAYMENT:
			return "pk_payment_";
		case PK_CROP:
			return "pk_crop_";
		case PAYMENT_DATE:
			return "payment_date_";
		case PAYMENT_AMOUNT:
			return "payment_amount_";
		case PK_USER:
			return "pk_user_";
		case REMARK:
			return "remark_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_payment() {
		return getAttribute(PK_PAYMENT);
	}

	/**
	 * 设置主键
	 * @param pk_payment
	 */
	public void setPk_payment(String pk_payment) {
		setAttribute(PK_PAYMENT, pk_payment);
	}

	/**
	 * 获取企业主键
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置企业主键
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取缴费日期
	 * @return
	 */
	public String getPayment_date() {
		return getAttribute(PAYMENT_DATE);
	}

	/**
	 * 设置缴费日期
	 * @param payment_date
	 */
	public void setPayment_date(String payment_date) {
		setAttribute(PAYMENT_DATE, payment_date);
	}

	/**
	 * 获取缴费金额
	 * @return
	 */
	public BigDecimal getPayment_amount() {
		return getAttribute(PAYMENT_AMOUNT);
	}

	/**
	 * 设置缴费金额
	 * @param payment_amount
	 */
	public void setPayment_amount(BigDecimal payment_amount) {
		setAttribute(PAYMENT_AMOUNT, payment_amount);
	}

	/**
	 * 获取经办人
	 * @return
	 */
	public String getPk_user() {
		return getAttribute(PK_USER);
	}

	/**
	 * 设置经办人
	 * @param pk_user
	 */
	public void setPk_user(String pk_user) {
		setAttribute(PK_USER, pk_user);
	}

	/**
	 * 获取备注
	 * @return
	 */
	public String getRemark() {
		return getAttribute(REMARK);
	}

	/**
	 * 设置备注
	 * @param remark
	 */
	public void setRemark(String remark) {
		setAttribute(REMARK, remark);
	}

}
