/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.details.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 工单详情表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskDetailsModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_details";
	
	/** 主键ID */
	public final static String PK_DETAILS_ID = "pk_details_id";	
	/** 项目ID */
	public final static String FK_PROJECT_ID = "fk_project_id";	
	/** 维修单号 */
	public final static String DATAILS_CODE = "datails_code";	
	/** 工单状态 */
	public final static String TASK_STATE = "task_state";	
	/** 服务类型 */
	public final static String SERVICE_TYPE = "service_type";	
	/** 维修种类ID */
	public final static String REPAIR_CLASS_ID = "repair_class_id";	
	/** 工单来源 */
	public final static String WORKTASK_TYPE = "worktask_type";	
	/** 关联楼址 */
	public final static String FK_REPAIR_ADDRESS = "fk_repair_address";	
	/** 维修地点（弃用） */
	public final static String REPAIR_PLACE = "repair_place";	
	/** 详细地址 */
	public final static String REPAIR_DETAILS = "repair_details";	
	/** 维修设备 */
	public final static String FK_REPAIR_EQUIPMENT = "fk_repair_equipment";	
	/** 报修人 */
	public final static String REPAIR_USER = "repair_user";	
	/** 联系电话 */
	public final static String CONTACT_NUMBER = "contact_number";	
	/** 维修内容 */
	public final static String REPAIR_CONTENT = "repair_content";	
	/** 跟进人ID */
	public final static String DUTY_USER_ID = "duty_user_id";	
	/** 预约时间 */
	public final static String BOOKINGS_TIME = "bookings_time";	
	/** 维修人ID */
	public final static String REPAIR_USER_ID = "repair_user_id";	
	/** 协助人ID */
	public final static String HLOP_USER_ID = "hlop_user_id";	
	/** 额定工时 */
	public final static String RATION_DURATION = "ration_duration";	
	/** 实际工时 */
	public final static String FINISHED_DURATION = "finished_duration";	
	/** 派单类型 */
	public final static String DISPATCH_TYPE = "dispatch_type";	
	/** 接单时间 */
	public final static String ORDERS_TIME = "orders_time";	
	/** 派单时间 */
	public final static String DISPATCH_TIME = "dispatch_time";	
	/** 完成时间 */
	public final static String FINISH_TIME = "finish_time";	
	/** 取消时间 */
	public final static String CANCEL_TIME = "cancel_time";	
	/** 工作数量 */
	public final static String WORK_NUMBER = "work_number";	
	/** 材料费用 */
	public final static String MATERIAL_COST = "material_cost";	
	/** 人工费用 */
	public final static String ARTIFICIAL_COST = "artificial_cost";	
	/** 总费用 */
	public final static String COUNT_COST = "count_cost";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人ID */
	public final static String CREATE_USER_ID = "create_user_id";	
	/** 创建人姓名 */
	public final static String CREATE_USER_NAME = "create_user_name";	
	/** 最后修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 最后修改人ID */
	public final static String UPDATE_USER_ID = "update_user_id";	
	/** 最后修改人姓名 */
	public final static String UPDATE_USER_NAME = "update_user_name";	
	/** 维修机房 */
	public final static String FK_REPAIR_EQUIPMENT_ROOM = "fk_repair_equipment_room";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 反馈详情 */
	public final static String FEEDBACK_CONTENT = "feedback_content";	
	/** 评价满意度 */
	public final static String EVALUATE = "evaluate";	
	/** 辅助字段 */
	public final static String CLASSIDS = "classids";	
	/** EBA报警id */
	public final static String EBA_REPORT_ID = "eba_report_id";	

	public YJWYWorkTaskDetailsModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_DETAILS_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_DETAILS_ID:
			return "pk_details_id";
		case FK_PROJECT_ID:
			return "fk_project_id";
		case DATAILS_CODE:
			return "datails_code";
		case TASK_STATE:
			return "task_state";
		case SERVICE_TYPE:
			return "service_type";
		case REPAIR_CLASS_ID:
			return "repair_class_id";
		case WORKTASK_TYPE:
			return "worktask_type";
		case FK_REPAIR_ADDRESS:
			return "fk_repair_address";
		case REPAIR_PLACE:
			return "repair_place";
		case REPAIR_DETAILS:
			return "repair_details";
		case FK_REPAIR_EQUIPMENT:
			return "fk_repair_equipment";
		case REPAIR_USER:
			return "repair_user";
		case CONTACT_NUMBER:
			return "contact_number";
		case REPAIR_CONTENT:
			return "repair_content";
		case DUTY_USER_ID:
			return "duty_user_id";
		case BOOKINGS_TIME:
			return "bookings_time";
		case REPAIR_USER_ID:
			return "repair_user_id";
		case HLOP_USER_ID:
			return "hlop_user_id";
		case RATION_DURATION:
			return "ration_duration";
		case FINISHED_DURATION:
			return "finished_duration";
		case DISPATCH_TYPE:
			return "dispatch_type";
		case ORDERS_TIME:
			return "orders_time";
		case DISPATCH_TIME:
			return "dispatch_time";
		case FINISH_TIME:
			return "finish_time";
		case CANCEL_TIME:
			return "cancel_time";
		case WORK_NUMBER:
			return "work_number";
		case MATERIAL_COST:
			return "material_cost";
		case ARTIFICIAL_COST:
			return "artificial_cost";
		case COUNT_COST:
			return "count_cost";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER_ID:
			return "create_user_id";
		case CREATE_USER_NAME:
			return "create_user_name";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER_ID:
			return "update_user_id";
		case UPDATE_USER_NAME:
			return "update_user_name";
		case FK_REPAIR_EQUIPMENT_ROOM:
			return "fk_repair_equipment_room";
		case PK_CROP:
			return "pk_crop";
		case FEEDBACK_CONTENT:
			return "feedback_content";
		case EVALUATE:
			return "evaluate";
		case CLASSIDS:
			return "classids";
		case EBA_REPORT_ID:
			return "eba_report_id";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_details_id() {
		return getAttribute(PK_DETAILS_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_details_id
	 */
	public void setPk_details_id(String pk_details_id) {
		setAttribute(PK_DETAILS_ID, pk_details_id);
	}

	/**
	 * 获取项目ID
	 * @return
	 */
	public String getFk_project_id() {
		return getAttribute(FK_PROJECT_ID);
	}

	/**
	 * 设置项目ID
	 * @param fk_project_id
	 */
	public void setFk_project_id(String fk_project_id) {
		setAttribute(FK_PROJECT_ID, fk_project_id);
	}

	/**
	 * 获取维修单号
	 * @return
	 */
	public String getDatails_code() {
		return getAttribute(DATAILS_CODE);
	}

	/**
	 * 设置维修单号
	 * @param datails_code
	 */
	public void setDatails_code(String datails_code) {
		setAttribute(DATAILS_CODE, datails_code);
	}

	/**
	 * 获取工单状态
	 * @return
	 */
	public Integer getTask_state() {
		return getAttribute(TASK_STATE);
	}

	/**
	 * 设置工单状态
	 * @param task_state
	 */
	public void setTask_state(Integer task_state) {
		setAttribute(TASK_STATE, task_state);
	}

	/**
	 * 获取服务类型
	 * @return
	 */
	public String getService_type() {
		return getAttribute(SERVICE_TYPE);
	}

	/**
	 * 设置服务类型
	 * @param service_type
	 */
	public void setService_type(String service_type) {
		setAttribute(SERVICE_TYPE, service_type);
	}

	/**
	 * 获取维修种类ID
	 * @return
	 */
	public String getRepair_class_id() {
		return getAttribute(REPAIR_CLASS_ID);
	}

	/**
	 * 设置维修种类ID
	 * @param repair_class_id
	 */
	public void setRepair_class_id(String repair_class_id) {
		setAttribute(REPAIR_CLASS_ID, repair_class_id);
	}

	/**
	 * 获取工单来源
	 * @return
	 */
	public String getWorktask_type() {
		return getAttribute(WORKTASK_TYPE);
	}

	/**
	 * 设置工单来源
	 * @param worktask_type
	 */
	public void setWorktask_type(String worktask_type) {
		setAttribute(WORKTASK_TYPE, worktask_type);
	}

	/**
	 * 获取关联楼址
	 * @return
	 */
	public String getFk_repair_address() {
		return getAttribute(FK_REPAIR_ADDRESS);
	}

	/**
	 * 设置关联楼址
	 * @param fk_repair_address
	 */
	public void setFk_repair_address(String fk_repair_address) {
		setAttribute(FK_REPAIR_ADDRESS, fk_repair_address);
	}

	/**
	 * 获取维修地点（弃用）
	 * @return
	 */
	public String getRepair_place() {
		return getAttribute(REPAIR_PLACE);
	}

	/**
	 * 设置维修地点（弃用）
	 * @param repair_place
	 */
	public void setRepair_place(String repair_place) {
		setAttribute(REPAIR_PLACE, repair_place);
	}

	/**
	 * 获取详细地址
	 * @return
	 */
	public String getRepair_details() {
		return getAttribute(REPAIR_DETAILS);
	}

	/**
	 * 设置详细地址
	 * @param repair_details
	 */
	public void setRepair_details(String repair_details) {
		setAttribute(REPAIR_DETAILS, repair_details);
	}

	/**
	 * 获取维修设备
	 * @return
	 */
	public String getFk_repair_equipment() {
		return getAttribute(FK_REPAIR_EQUIPMENT);
	}

	/**
	 * 设置维修设备
	 * @param fk_repair_equipment
	 */
	public void setFk_repair_equipment(String fk_repair_equipment) {
		setAttribute(FK_REPAIR_EQUIPMENT, fk_repair_equipment);
	}

	/**
	 * 获取报修人
	 * @return
	 */
	public String getRepair_user() {
		return getAttribute(REPAIR_USER);
	}

	/**
	 * 设置报修人
	 * @param repair_user
	 */
	public void setRepair_user(String repair_user) {
		setAttribute(REPAIR_USER, repair_user);
	}

	/**
	 * 获取联系电话
	 * @return
	 */
	public String getContact_number() {
		return getAttribute(CONTACT_NUMBER);
	}

	/**
	 * 设置联系电话
	 * @param contact_number
	 */
	public void setContact_number(String contact_number) {
		setAttribute(CONTACT_NUMBER, contact_number);
	}

	/**
	 * 获取维修内容
	 * @return
	 */
	public String getRepair_content() {
		return getAttribute(REPAIR_CONTENT);
	}

	/**
	 * 设置维修内容
	 * @param repair_content
	 */
	public void setRepair_content(String repair_content) {
		setAttribute(REPAIR_CONTENT, repair_content);
	}

	/**
	 * 获取跟进人ID
	 * @return
	 */
	public String getDuty_user_id() {
		return getAttribute(DUTY_USER_ID);
	}

	/**
	 * 设置跟进人ID
	 * @param duty_user_id
	 */
	public void setDuty_user_id(String duty_user_id) {
		setAttribute(DUTY_USER_ID, duty_user_id);
	}

	/**
	 * 获取预约时间
	 * @return
	 */
	public String getBookings_time() {
		return getAttribute(BOOKINGS_TIME);
	}

	/**
	 * 设置预约时间
	 * @param bookings_time
	 */
	public void setBookings_time(String bookings_time) {
		setAttribute(BOOKINGS_TIME, bookings_time);
	}

	/**
	 * 获取维修人ID
	 * @return
	 */
	public String getRepair_user_id() {
		return getAttribute(REPAIR_USER_ID);
	}

	/**
	 * 设置维修人ID
	 * @param repair_user_id
	 */
	public void setRepair_user_id(String repair_user_id) {
		setAttribute(REPAIR_USER_ID, repair_user_id);
	}

	/**
	 * 获取协助人ID
	 * @return
	 */
	public String getHlop_user_id() {
		return getAttribute(HLOP_USER_ID);
	}

	/**
	 * 设置协助人ID
	 * @param hlop_user_id
	 */
	public void setHlop_user_id(String hlop_user_id) {
		setAttribute(HLOP_USER_ID, hlop_user_id);
	}

	/**
	 * 获取额定工时
	 * @return
	 */
	public String getRation_duration() {
		return getAttribute(RATION_DURATION);
	}

	/**
	 * 设置额定工时
	 * @param ration_duration
	 */
	public void setRation_duration(String ration_duration) {
		setAttribute(RATION_DURATION, ration_duration);
	}

	/**
	 * 获取实际工时
	 * @return
	 */
	public String getFinished_duration() {
		return getAttribute(FINISHED_DURATION);
	}

	/**
	 * 设置实际工时
	 * @param finished_duration
	 */
	public void setFinished_duration(String finished_duration) {
		setAttribute(FINISHED_DURATION, finished_duration);
	}

	/**
	 * 获取派单类型
	 * @return
	 */
	public Integer getDispatch_type() {
		return getAttribute(DISPATCH_TYPE);
	}

	/**
	 * 设置派单类型
	 * @param dispatch_type
	 */
	public void setDispatch_type(Integer dispatch_type) {
		setAttribute(DISPATCH_TYPE, dispatch_type);
	}

	/**
	 * 获取接单时间
	 * @return
	 */
	public String getOrders_time() {
		return getAttribute(ORDERS_TIME);
	}

	/**
	 * 设置接单时间
	 * @param orders_time
	 */
	public void setOrders_time(String orders_time) {
		setAttribute(ORDERS_TIME, orders_time);
	}

	/**
	 * 获取派单时间
	 * @return
	 */
	public String getDispatch_time() {
		return getAttribute(DISPATCH_TIME);
	}

	/**
	 * 设置派单时间
	 * @param dispatch_time
	 */
	public void setDispatch_time(String dispatch_time) {
		setAttribute(DISPATCH_TIME, dispatch_time);
	}

	/**
	 * 获取完成时间
	 * @return
	 */
	public String getFinish_time() {
		return getAttribute(FINISH_TIME);
	}

	/**
	 * 设置完成时间
	 * @param finish_time
	 */
	public void setFinish_time(String finish_time) {
		setAttribute(FINISH_TIME, finish_time);
	}

	/**
	 * 获取取消时间
	 * @return
	 */
	public String getCancel_time() {
		return getAttribute(CANCEL_TIME);
	}

	/**
	 * 设置取消时间
	 * @param cancel_time
	 */
	public void setCancel_time(String cancel_time) {
		setAttribute(CANCEL_TIME, cancel_time);
	}

	/**
	 * 获取工作数量
	 * @return
	 */
	public Integer getWork_number() {
		return getAttribute(WORK_NUMBER);
	}

	/**
	 * 设置工作数量
	 * @param work_number
	 */
	public void setWork_number(Integer work_number) {
		setAttribute(WORK_NUMBER, work_number);
	}

	/**
	 * 获取材料费用
	 * @return
	 */
	public BigDecimal getMaterial_cost() {
		return getAttribute(MATERIAL_COST);
	}

	/**
	 * 设置材料费用
	 * @param material_cost
	 */
	public void setMaterial_cost(BigDecimal material_cost) {
		setAttribute(MATERIAL_COST, material_cost);
	}

	/**
	 * 获取人工费用
	 * @return
	 */
	public BigDecimal getArtificial_cost() {
		return getAttribute(ARTIFICIAL_COST);
	}

	/**
	 * 设置人工费用
	 * @param artificial_cost
	 */
	public void setArtificial_cost(BigDecimal artificial_cost) {
		setAttribute(ARTIFICIAL_COST, artificial_cost);
	}

	/**
	 * 获取总费用
	 * @return
	 */
	public BigDecimal getCount_cost() {
		return getAttribute(COUNT_COST);
	}

	/**
	 * 设置总费用
	 * @param count_cost
	 */
	public void setCount_cost(BigDecimal count_cost) {
		setAttribute(COUNT_COST, count_cost);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人ID
	 * @return
	 */
	public String getCreate_user_id() {
		return getAttribute(CREATE_USER_ID);
	}

	/**
	 * 设置创建人ID
	 * @param create_user_id
	 */
	public void setCreate_user_id(String create_user_id) {
		setAttribute(CREATE_USER_ID, create_user_id);
	}

	/**
	 * 获取创建人姓名
	 * @return
	 */
	public String getCreate_user_name() {
		return getAttribute(CREATE_USER_NAME);
	}

	/**
	 * 设置创建人姓名
	 * @param create_user_name
	 */
	public void setCreate_user_name(String create_user_name) {
		setAttribute(CREATE_USER_NAME, create_user_name);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取最后修改人ID
	 * @return
	 */
	public String getUpdate_user_id() {
		return getAttribute(UPDATE_USER_ID);
	}

	/**
	 * 设置最后修改人ID
	 * @param update_user_id
	 */
	public void setUpdate_user_id(String update_user_id) {
		setAttribute(UPDATE_USER_ID, update_user_id);
	}

	/**
	 * 获取最后修改人姓名
	 * @return
	 */
	public String getUpdate_user_name() {
		return getAttribute(UPDATE_USER_NAME);
	}

	/**
	 * 设置最后修改人姓名
	 * @param update_user_name
	 */
	public void setUpdate_user_name(String update_user_name) {
		setAttribute(UPDATE_USER_NAME, update_user_name);
	}

	/**
	 * 获取维修机房
	 * @return
	 */
	public String getFk_repair_equipment_room() {
		return getAttribute(FK_REPAIR_EQUIPMENT_ROOM);
	}

	/**
	 * 设置维修机房
	 * @param fk_repair_equipment_room
	 */
	public void setFk_repair_equipment_room(String fk_repair_equipment_room) {
		setAttribute(FK_REPAIR_EQUIPMENT_ROOM, fk_repair_equipment_room);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取反馈详情
	 * @return
	 */
	public String getFeedback_content() {
		return getAttribute(FEEDBACK_CONTENT);
	}

	/**
	 * 设置反馈详情
	 * @param feedback_content
	 */
	public void setFeedback_content(String feedback_content) {
		setAttribute(FEEDBACK_CONTENT, feedback_content);
	}

	/**
	 * 获取评价满意度
	 * @return
	 */
	public String getEvaluate() {
		return getAttribute(EVALUATE);
	}

	/**
	 * 设置评价满意度
	 * @param evaluate
	 */
	public void setEvaluate(String evaluate) {
		setAttribute(EVALUATE, evaluate);
	}

	/**
	 * 获取辅助字段
	 * @return
	 */
	public String getClassids() {
		return getAttribute(CLASSIDS);
	}

	/**
	 * 设置辅助字段
	 * @param classids
	 */
	public void setClassids(String classids) {
		setAttribute(CLASSIDS, classids);
	}

	/**
	 * 获取EBA报警id
	 * @return
	 */
	public String getEba_report_id() {
		return getAttribute(EBA_REPORT_ID);
	}

	/**
	 * 设置EBA报警id
	 * @param eba_report_id
	 */
	public void setEba_report_id(String eba_report_id) {
		setAttribute(EBA_REPORT_ID, eba_report_id);
	}

}
