/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.timer.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 定时任务执行记录实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYTimerModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_device_timer";
	
	/** 主键执行id */
	public final static String TIMER_ID = "timer_id";	
	/** 执行类名 */
	public final static String CLASS_NAME = "class_name";	
	/** 执行方法名 */
	public final static String METHOD_NAME = "method_name";	
	/** 执行时间 */
	public final static String EXECUTE_TIME = "execute_time";	

	public YJWYTimerModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return TIMER_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case TIMER_ID:
			return "timer_id";
		case CLASS_NAME:
			return "class_name";
		case METHOD_NAME:
			return "method_name";
		case EXECUTE_TIME:
			return "execute_time";
		}
		return null;
	}

	/**
	 * 获取主键执行id
	 * @return
	 */
	public String getTimer_id() {
		return getAttribute(TIMER_ID);
	}

	/**
	 * 设置主键执行id
	 * @param timer_id
	 */
	public void setTimer_id(String timer_id) {
		setAttribute(TIMER_ID, timer_id);
	}

	/**
	 * 获取执行类名
	 * @return
	 */
	public String getClass_name() {
		return getAttribute(CLASS_NAME);
	}

	/**
	 * 设置执行类名
	 * @param class_name
	 */
	public void setClass_name(String class_name) {
		setAttribute(CLASS_NAME, class_name);
	}

	/**
	 * 获取执行方法名
	 * @return
	 */
	public String getMethod_name() {
		return getAttribute(METHOD_NAME);
	}

	/**
	 * 设置执行方法名
	 * @param method_name
	 */
	public void setMethod_name(String method_name) {
		setAttribute(METHOD_NAME, method_name);
	}

	/**
	 * 获取执行时间
	 * @return
	 */
	public String getExecute_time() {
		return getAttribute(EXECUTE_TIME);
	}

	/**
	 * 设置执行时间
	 * @param execute_time
	 */
	public void setExecute_time(String execute_time) {
		setAttribute(EXECUTE_TIME, execute_time);
	}

}
