/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.patrol.plan.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 计划设备中间表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYPlanEqModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_patrol_plan_eq";
	
	/** 计划id */
	public final static String PLAN_ID = "plan_id";	
	/** 设备设施id */
	public final static String EQ_ID = "eq_id";	
	/** 房间位置id */
	public final static String RM_ID = "rm_id";	
	/** 设备分类id */
	public final static String CSI_ID = "csi_id";	
	/** 工艺主表id */
	public final static String PMP_ID = "pmp_id";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYPlanEqModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PLAN_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PLAN_ID:
			return "plan_id";
		case EQ_ID:
			return "eq_id";
		case RM_ID:
			return "rm_id";
		case CSI_ID:
			return "csi_id";
		case PMP_ID:
			return "pmp_id";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取计划id
	 * @return
	 */
	public String getPlan_id() {
		return getAttribute(PLAN_ID);
	}

	/**
	 * 设置计划id
	 * @param plan_id
	 */
	public void setPlan_id(String plan_id) {
		setAttribute(PLAN_ID, plan_id);
	}

	/**
	 * 获取设备设施id
	 * @return
	 */
	public String getEq_id() {
		return getAttribute(EQ_ID);
	}

	/**
	 * 设置设备设施id
	 * @param eq_id
	 */
	public void setEq_id(String eq_id) {
		setAttribute(EQ_ID, eq_id);
	}

	/**
	 * 获取房间位置id
	 * @return
	 */
	public String getRm_id() {
		return getAttribute(RM_ID);
	}

	/**
	 * 设置房间位置id
	 * @param rm_id
	 */
	public void setRm_id(String rm_id) {
		setAttribute(RM_ID, rm_id);
	}

	/**
	 * 获取设备分类id
	 * @return
	 */
	public String getCsi_id() {
		return getAttribute(CSI_ID);
	}

	/**
	 * 设置设备分类id
	 * @param csi_id
	 */
	public void setCsi_id(String csi_id) {
		setAttribute(CSI_ID, csi_id);
	}

	/**
	 * 获取工艺主表id
	 * @return
	 */
	public String getPmp_id() {
		return getAttribute(PMP_ID);
	}

	/**
	 * 设置工艺主表id
	 * @param pmp_id
	 */
	public void setPmp_id(String pmp_id) {
		setAttribute(PMP_ID, pmp_id);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
