/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.usermobile.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 用户与设备关系表实体类
 * 
 * @author yuting.wang
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYUserMobileModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_usermoible";
	
	/** 主键 */
	public final static String PK_USERMOBILE = "pk_usermobile";	
	/** 用户id */
	public final static String FK_USER = "fk_user";	
	/** 设备号 */
	public final static String MOBILE_ID = "mobile_id";	
	/** 公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 平台（Android,IOS） */
	public final static String MOBILE_PLATFORM = "mobile_platform";	

	public YJWYUserMobileModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_USERMOBILE;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_USERMOBILE:
			return "pk_usermobile";
		case FK_USER:
			return "fk_user";
		case MOBILE_ID:
			return "mobile_id";
		case PK_CROP:
			return "pk_crop";
		case MOBILE_PLATFORM:
			return "mobile_platform";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_usermobile() {
		return getAttribute(PK_USERMOBILE);
	}

	/**
	 * 设置主键
	 * @param pk_usermobile
	 */
	public void setPk_usermobile(String pk_usermobile) {
		setAttribute(PK_USERMOBILE, pk_usermobile);
	}

	/**
	 * 获取用户id
	 * @return
	 */
	public String getFk_user() {
		return getAttribute(FK_USER);
	}

	/**
	 * 设置用户id
	 * @param fk_user
	 */
	public void setFk_user(String fk_user) {
		setAttribute(FK_USER, fk_user);
	}

	/**
	 * 获取设备号
	 * @return
	 */
	public String getMobile_id() {
		return getAttribute(MOBILE_ID);
	}

	/**
	 * 设置设备号
	 * @param mobile_id
	 */
	public void setMobile_id(String mobile_id) {
		setAttribute(MOBILE_ID, mobile_id);
	}

	/**
	 * 获取公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取平台（Android,IOS）
	 * @return
	 */
	public String getMobile_platform() {
		return getAttribute(MOBILE_PLATFORM);
	}

	/**
	 * 设置平台（Android,IOS）
	 * @param mobile_platform
	 */
	public void setMobile_platform(String mobile_platform) {
		setAttribute(MOBILE_PLATFORM, mobile_platform);
	}

}
