/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.sonclass.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 工单维修种类记录表实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskSonClassRecordModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_son_class_record";
	
	/** 主键ID */
	public final static String PK_RECORD_ID = "pk_record_id";	
	/** 工单ID */
	public final static String FK_DETAILS_ID = "fk_details_id";	
	/** 维修种类ID */
	public final static String FK_CLASS_ID = "fk_class_id";	
	/** 工作数量 */
	public final static String NUMBER = "number";	
	/** 记录时间 */
	public final static String RECORD_TIME = "record_time";	
	/** 记录人ID */
	public final static String RECORD_USER_ID = "record_user_id";	
	/** 二级分类ID */
	public final static String FK_TWO_LEVELCLASS_ID = "fk_two_levelclass_id";	

	public YJWYWorkTaskSonClassRecordModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_RECORD_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_RECORD_ID:
			return "pk_record_id";
		case FK_DETAILS_ID:
			return "fk_details_id";
		case FK_CLASS_ID:
			return "fk_class_id";
		case NUMBER:
			return "number";
		case RECORD_TIME:
			return "record_time";
		case RECORD_USER_ID:
			return "record_user_id";
		case FK_TWO_LEVELCLASS_ID:
			return "fk_two_levelclass_id";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_record_id() {
		return getAttribute(PK_RECORD_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_record_id
	 */
	public void setPk_record_id(String pk_record_id) {
		setAttribute(PK_RECORD_ID, pk_record_id);
	}

	/**
	 * 获取工单ID
	 * @return
	 */
	public String getFk_details_id() {
		return getAttribute(FK_DETAILS_ID);
	}

	/**
	 * 设置工单ID
	 * @param fk_details_id
	 */
	public void setFk_details_id(String fk_details_id) {
		setAttribute(FK_DETAILS_ID, fk_details_id);
	}

	/**
	 * 获取维修种类ID
	 * @return
	 */
	public String getFk_class_id() {
		return getAttribute(FK_CLASS_ID);
	}

	/**
	 * 设置维修种类ID
	 * @param fk_class_id
	 */
	public void setFk_class_id(String fk_class_id) {
		setAttribute(FK_CLASS_ID, fk_class_id);
	}

	/**
	 * 获取工作数量
	 * @return
	 */
	public Integer getNumber() {
		return getAttribute(NUMBER);
	}

	/**
	 * 设置工作数量
	 * @param number
	 */
	public void setNumber(Integer number) {
		setAttribute(NUMBER, number);
	}

	/**
	 * 获取记录时间
	 * @return
	 */
	public String getRecord_time() {
		return getAttribute(RECORD_TIME);
	}

	/**
	 * 设置记录时间
	 * @param record_time
	 */
	public void setRecord_time(String record_time) {
		setAttribute(RECORD_TIME, record_time);
	}

	/**
	 * 获取记录人ID
	 * @return
	 */
	public String getRecord_user_id() {
		return getAttribute(RECORD_USER_ID);
	}

	/**
	 * 设置记录人ID
	 * @param record_user_id
	 */
	public void setRecord_user_id(String record_user_id) {
		setAttribute(RECORD_USER_ID, record_user_id);
	}

	/**
	 * 获取二级分类ID
	 * @return
	 */
	public String getFk_two_levelclass_id() {
		return getAttribute(FK_TWO_LEVELCLASS_ID);
	}

	/**
	 * 设置二级分类ID
	 * @param fk_two_levelclass_id
	 */
	public void setFk_two_levelclass_id(String fk_two_levelclass_id) {
		setAttribute(FK_TWO_LEVELCLASS_ID, fk_two_levelclass_id);
	}

}
