/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.user.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 系统用户实体类
 * 
 * @author yuting.wang
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYUserModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_user";
	
	/** 主键 */
	public final static String PK_USER = "pk_user";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 工号 */
	public final static String EM_CODE = "em_code";	
	/** 用户姓名 */
	public final static String USER_NAME = "user_name";	
	/** 用户账号 */
	public final static String USER_CODE = "user_code";	
	/** 用户密码 */
	public final static String PASSWORD = "password";	
	/** 邮箱 */
	public final static String EMAIL = "email";	
	/** 电话 */
	public final static String PHONE = "phone";	
	/** 系统预置 */
	public final static String IS_PRE = "is_pre";	
	/** 启用 */
	public final static String IS_ABLE = "is_able";	
	/** 用户头像 */
	public final static String HEADER_IMG = "header_img";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 最后修改人 */
	public final static String LAST_MODIFY_USER = "last_modify_user";	
	/** 最后修改时间 */
	public final static String LAST_MODIFY_TIME = "last_modify_time";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 选中标识 */
	public final static String SELECTED = "selected";	
	/** 删除标志1.已删除，0.未删除 */
	public final static String DELETE_FLAG = "delete_flag";	
	/** 是否签到（1：已签到；2：已签退） */
	public final static String IS_SIGN = "is_sign";	

	public YJWYUserModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_USER;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_USER:
			return "pk_user_";
		case PK_CROP:
			return "pk_crop_";
		case EM_CODE:
			return "em_code_";
		case USER_NAME:
			return "user_name_";
		case USER_CODE:
			return "user_code_";
		case PASSWORD:
			return "password_";
		case EMAIL:
			return "email_";
		case PHONE:
			return "phone_";
		case IS_PRE:
			return "is_pre_";
		case IS_ABLE:
			return "is_able_";
		case HEADER_IMG:
			return "header_img_";
		case CREATE_USER:
			return "create_user_";
		case CREATE_TIME:
			return "create_time_";
		case LAST_MODIFY_USER:
			return "last_modify_user_";
		case LAST_MODIFY_TIME:
			return "last_modify_time_";
		case UPDATE_TIME:
			return "update_time_";
		case SELECTED:
			return "selected_";
		case DELETE_FLAG:
			return "delete_flag_";
		case IS_SIGN:
			return "is_sign_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_user() {
		return getAttribute(PK_USER);
	}

	/**
	 * 设置主键
	 * @param pk_user
	 */
	public void setPk_user(String pk_user) {
		setAttribute(PK_USER, pk_user);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取工号
	 * @return
	 */
	public String getEm_code() {
		return getAttribute(EM_CODE);
	}

	/**
	 * 设置工号
	 * @param em_code
	 */
	public void setEm_code(String em_code) {
		setAttribute(EM_CODE, em_code);
	}

	/**
	 * 获取用户姓名
	 * @return
	 */
	public String getUser_name() {
		return getAttribute(USER_NAME);
	}

	/**
	 * 设置用户姓名
	 * @param user_name
	 */
	public void setUser_name(String user_name) {
		setAttribute(USER_NAME, user_name);
	}

	/**
	 * 获取用户账号
	 * @return
	 */
	public String getUser_code() {
		return getAttribute(USER_CODE);
	}

	/**
	 * 设置用户账号
	 * @param user_code
	 */
	public void setUser_code(String user_code) {
		setAttribute(USER_CODE, user_code);
	}

	/**
	 * 获取用户密码
	 * @return
	 */
	public String getPassword() {
		return getAttribute(PASSWORD);
	}

	/**
	 * 设置用户密码
	 * @param password
	 */
	public void setPassword(String password) {
		setAttribute(PASSWORD, password);
	}

	/**
	 * 获取邮箱
	 * @return
	 */
	public String getEmail() {
		return getAttribute(EMAIL);
	}

	/**
	 * 设置邮箱
	 * @param email
	 */
	public void setEmail(String email) {
		setAttribute(EMAIL, email);
	}

	/**
	 * 获取电话
	 * @return
	 */
	public String getPhone() {
		return getAttribute(PHONE);
	}

	/**
	 * 设置电话
	 * @param phone
	 */
	public void setPhone(String phone) {
		setAttribute(PHONE, phone);
	}

	/**
	 * 获取系统预置
	 * @return
	 */
	public Boolean getIs_pre() {
		return getAttribute(IS_PRE);
	}

	/**
	 * 设置系统预置
	 * @param is_pre
	 */
	public void setIs_pre(Boolean is_pre) {
		setAttribute(IS_PRE, is_pre);
	}

	/**
	 * 获取启用
	 * @return
	 */
	public Boolean getIs_able() {
		return getAttribute(IS_ABLE);
	}

	/**
	 * 设置启用
	 * @param is_able
	 */
	public void setIs_able(Boolean is_able) {
		setAttribute(IS_ABLE, is_able);
	}

	/**
	 * 获取用户头像
	 * @return
	 */
	public String getHeader_img() {
		return getAttribute(HEADER_IMG);
	}

	/**
	 * 设置用户头像
	 * @param header_img
	 */
	public void setHeader_img(String header_img) {
		setAttribute(HEADER_IMG, header_img);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取最后修改人
	 * @return
	 */
	public String getLast_modify_user() {
		return getAttribute(LAST_MODIFY_USER);
	}

	/**
	 * 设置最后修改人
	 * @param last_modify_user
	 */
	public void setLast_modify_user(String last_modify_user) {
		setAttribute(LAST_MODIFY_USER, last_modify_user);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getLast_modify_time() {
		return getAttribute(LAST_MODIFY_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param last_modify_time
	 */
	public void setLast_modify_time(String last_modify_time) {
		setAttribute(LAST_MODIFY_TIME, last_modify_time);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取选中标识
	 * @return
	 */
	public Boolean getSelected() {
		return getAttribute(SELECTED);
	}

	/**
	 * 设置选中标识
	 * @param selected
	 */
	public void setSelected(Boolean selected) {
		setAttribute(SELECTED, selected);
	}

	/**
	 * 获取删除标志1.已删除，0.未删除
	 * @return
	 */
	public String getDelete_flag() {
		return getAttribute(DELETE_FLAG);
	}

	/**
	 * 设置删除标志1.已删除，0.未删除
	 * @param delete_flag
	 */
	public void setDelete_flag(String delete_flag) {
		setAttribute(DELETE_FLAG, delete_flag);
	}

	/**
	 * 获取是否签到（1：已签到；2：已签退）
	 * @return
	 */
	public String getIs_sign() {
		return getAttribute(IS_SIGN);
	}

	/**
	 * 设置是否签到（1：已签到；2：已签退）
	 * @param is_sign
	 */
	public void setIs_sign(String is_sign) {
		setAttribute(IS_SIGN, is_sign);
	}

}
