/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.siteproject.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * FM与YJWY项目关联表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYSiteProjectModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_fmdata_site_project";
	
	/** FM项目id */
	public final static String SITE_ID = "site_id";	
	/** YJWY项目id */
	public final static String PK_PROJECT = "pk_project";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYSiteProjectModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return SITE_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case SITE_ID:
			return "site_id";
		case PK_PROJECT:
			return "pk_project";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取FM项目id
	 * @return
	 */
	public String getSite_id() {
		return getAttribute(SITE_ID);
	}

	/**
	 * 设置FM项目id
	 * @param site_id
	 */
	public void setSite_id(String site_id) {
		setAttribute(SITE_ID, site_id);
	}

	/**
	 * 获取YJWY项目id
	 * @return
	 */
	public String getPk_project() {
		return getAttribute(PK_PROJECT);
	}

	/**
	 * 设置YJWY项目id
	 * @param pk_project
	 */
	public void setPk_project(String pk_project) {
		setAttribute(PK_PROJECT, pk_project);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
