/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.areadetails.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 片区详情实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskAreaDetailsModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_area_details";
	
	/** 主键ID */
	public final static String PK_AREA_ID = "pk_area_id";	
	/** 片区名称 */
	public final static String AREA_NAME = "area_name";	
	/** 区域ID */
	public final static String FK_REGION_ID = "fk_region_id";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人ID */
	public final static String CREATE_USER_ID = "create_user_id";	
	/** 最后修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 最后修改人ID */
	public final static String UPDATE_USER_ID = "update_user_id";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYWorkTaskAreaDetailsModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_AREA_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_AREA_ID:
			return "pk_area_id";
		case AREA_NAME:
			return "area_name";
		case FK_REGION_ID:
			return "fk_region_id";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER_ID:
			return "create_user_id";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER_ID:
			return "update_user_id";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_area_id() {
		return getAttribute(PK_AREA_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_area_id
	 */
	public void setPk_area_id(String pk_area_id) {
		setAttribute(PK_AREA_ID, pk_area_id);
	}

	/**
	 * 获取片区名称
	 * @return
	 */
	public String getArea_name() {
		return getAttribute(AREA_NAME);
	}

	/**
	 * 设置片区名称
	 * @param area_name
	 */
	public void setArea_name(String area_name) {
		setAttribute(AREA_NAME, area_name);
	}

	/**
	 * 获取区域ID
	 * @return
	 */
	public String getFk_region_id() {
		return getAttribute(FK_REGION_ID);
	}

	/**
	 * 设置区域ID
	 * @param fk_region_id
	 */
	public void setFk_region_id(String fk_region_id) {
		setAttribute(FK_REGION_ID, fk_region_id);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人ID
	 * @return
	 */
	public String getCreate_user_id() {
		return getAttribute(CREATE_USER_ID);
	}

	/**
	 * 设置创建人ID
	 * @param create_user_id
	 */
	public void setCreate_user_id(String create_user_id) {
		setAttribute(CREATE_USER_ID, create_user_id);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取最后修改人ID
	 * @return
	 */
	public String getUpdate_user_id() {
		return getAttribute(UPDATE_USER_ID);
	}

	/**
	 * 设置最后修改人ID
	 * @param update_user_id
	 */
	public void setUpdate_user_id(String update_user_id) {
		setAttribute(UPDATE_USER_ID, update_user_id);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
