/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.areauser.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 片区与人员关系表实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskAreaUserNexusModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_area_user_nexus";
	
	/** 主键ID */
	public final static String PK_NEXUS_ID = "pk_nexus_id";	
	/** 用户表ID */
	public final static String USER_ID = "user_id";	
	/** 片区维修人员ID */
	public final static String PERSONNEL_ID = "personnel_id";	
	/** 片区ID */
	public final static String AREA_ID = "area_id";	
	/** 用户类型 */
	public final static String USER_TYPE = "user_type";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人ID */
	public final static String CREATE_USER_ID = "create_user_id";	

	public YJWYWorkTaskAreaUserNexusModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_NEXUS_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_NEXUS_ID:
			return "pk_nexus_id";
		case USER_ID:
			return "user_id";
		case PERSONNEL_ID:
			return "personnel_id";
		case AREA_ID:
			return "area_id";
		case USER_TYPE:
			return "user_type";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER_ID:
			return "create_user_id";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_nexus_id() {
		return getAttribute(PK_NEXUS_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_nexus_id
	 */
	public void setPk_nexus_id(String pk_nexus_id) {
		setAttribute(PK_NEXUS_ID, pk_nexus_id);
	}

	/**
	 * 获取用户表ID
	 * @return
	 */
	public String getUser_id() {
		return getAttribute(USER_ID);
	}

	/**
	 * 设置用户表ID
	 * @param user_id
	 */
	public void setUser_id(String user_id) {
		setAttribute(USER_ID, user_id);
	}

	/**
	 * 获取片区维修人员ID
	 * @return
	 */
	public String getPersonnel_id() {
		return getAttribute(PERSONNEL_ID);
	}

	/**
	 * 设置片区维修人员ID
	 * @param personnel_id
	 */
	public void setPersonnel_id(String personnel_id) {
		setAttribute(PERSONNEL_ID, personnel_id);
	}

	/**
	 * 获取片区ID
	 * @return
	 */
	public String getArea_id() {
		return getAttribute(AREA_ID);
	}

	/**
	 * 设置片区ID
	 * @param area_id
	 */
	public void setArea_id(String area_id) {
		setAttribute(AREA_ID, area_id);
	}

	/**
	 * 获取用户类型
	 * @return
	 */
	public String getUser_type() {
		return getAttribute(USER_TYPE);
	}

	/**
	 * 设置用户类型
	 * @param user_type
	 */
	public void setUser_type(String user_type) {
		setAttribute(USER_TYPE, user_type);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人ID
	 * @return
	 */
	public String getCreate_user_id() {
		return getAttribute(CREATE_USER_ID);
	}

	/**
	 * 设置创建人ID
	 * @param create_user_id
	 */
	public void setCreate_user_id(String create_user_id) {
		setAttribute(CREATE_USER_ID, create_user_id);
	}

}
