/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.performance.leave.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 休假备案实体类
 * 
 * @author lingwei.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYLeaveModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_performance_leave";
	
	/** 主键ID */
	public final static String PK_LEAVE = "pk_leave";	
	/** 提交人 */
	public final static String LV_SUBMITTER = "lv_submitter";	
	/** 外键(项目) */
	public final static String FK_PROJECT = "fk_project";	
	/** 外键(岗位) */
	public final static String FK_JOB = "fk_job";	
	/** 外键(休假类型) */
	public final static String FK_TYPE = "fk_type";	
	/** 提交时间 */
	public final static String LV_COMMITTIME = "lv_commitTime";	
	/** 确认时间 */
	public final static String LV_CONFIRMTIME = "lv_confirmTime";	
	/** 开始时间 */
	public final static String LV_STARTTIME = "lv_startTime";	
	/** 结束时间 */
	public final static String LV_ENDTIME = "lv_endTime";	
	/** 休假天数 */
	public final static String LV_DAYS = "lv_days";	
	/** 休假详情 */
	public final static String LV_DETAILS = "lv_details";	
	/** 审批人 */
	public final static String LV_APPROVAL = "lv_approval";	
	/** 操作  0待审批，1审批通过，2审批拒绝，3已撤销 */
	public final static String LV_OPERATION = "lv_operation";	
	/** 审批详情 */
	public final static String LV_APPROVALDESC = "lv_approvalDesc";	
	/** 创建人 */
	public final static String CREATE_USER = "create_user";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 更新人 */
	public final static String UPDATE_USER = "update_user";	
	/** 更新时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 外键(区域) */
	public final static String FK_REGION = "fk_region";	
	/** 外键(人员组) */
	public final static String FK_PEOPLE = "fk_people";	
	/** 外键(公司) */
	public final static String PK_CROP = "pk_crop";	

	public YJWYLeaveModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_LEAVE;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_LEAVE:
			return "pk_leave_";
		case LV_SUBMITTER:
			return "lv_submitter_";
		case FK_PROJECT:
			return "fk_project_";
		case FK_JOB:
			return "fk_job_";
		case FK_TYPE:
			return "fk_type_";
		case LV_COMMITTIME:
			return "lv_commitTime_";
		case LV_CONFIRMTIME:
			return "lv_confirmTime_";
		case LV_STARTTIME:
			return "lv_startTime_";
		case LV_ENDTIME:
			return "lv_endTime_";
		case LV_DAYS:
			return "lv_days_";
		case LV_DETAILS:
			return "lv_details_";
		case LV_APPROVAL:
			return "lv_approval_";
		case LV_OPERATION:
			return "lv_operation_";
		case LV_APPROVALDESC:
			return "lv_approvalDesc_";
		case CREATE_USER:
			return "create_user_";
		case CREATE_TIME:
			return "create_time_";
		case UPDATE_USER:
			return "update_user_";
		case UPDATE_TIME:
			return "update_time_";
		case FK_REGION:
			return "fk_region_";
		case FK_PEOPLE:
			return "fk_people_";
		case PK_CROP:
			return "pk_crop_";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_leave() {
		return getAttribute(PK_LEAVE);
	}

	/**
	 * 设置主键ID
	 * @param pk_leave
	 */
	public void setPk_leave(String pk_leave) {
		setAttribute(PK_LEAVE, pk_leave);
	}

	/**
	 * 获取提交人
	 * @return
	 */
	public String getLv_submitter() {
		return getAttribute(LV_SUBMITTER);
	}

	/**
	 * 设置提交人
	 * @param lv_submitter
	 */
	public void setLv_submitter(String lv_submitter) {
		setAttribute(LV_SUBMITTER, lv_submitter);
	}

	/**
	 * 获取外键(项目)
	 * @return
	 */
	public String getFk_project() {
		return getAttribute(FK_PROJECT);
	}

	/**
	 * 设置外键(项目)
	 * @param fk_project
	 */
	public void setFk_project(String fk_project) {
		setAttribute(FK_PROJECT, fk_project);
	}

	/**
	 * 获取外键(岗位)
	 * @return
	 */
	public String getFk_job() {
		return getAttribute(FK_JOB);
	}

	/**
	 * 设置外键(岗位)
	 * @param fk_job
	 */
	public void setFk_job(String fk_job) {
		setAttribute(FK_JOB, fk_job);
	}

	/**
	 * 获取外键(休假类型)
	 * @return
	 */
	public String getFk_type() {
		return getAttribute(FK_TYPE);
	}

	/**
	 * 设置外键(休假类型)
	 * @param fk_type
	 */
	public void setFk_type(String fk_type) {
		setAttribute(FK_TYPE, fk_type);
	}

	/**
	 * 获取提交时间
	 * @return
	 */
	public String getLv_commitTime() {
		return getAttribute(LV_COMMITTIME);
	}

	/**
	 * 设置提交时间
	 * @param lv_commitTime
	 */
	public void setLv_commitTime(String lv_commitTime) {
		setAttribute(LV_COMMITTIME, lv_commitTime);
	}

	/**
	 * 获取确认时间
	 * @return
	 */
	public String getLv_confirmTime() {
		return getAttribute(LV_CONFIRMTIME);
	}

	/**
	 * 设置确认时间
	 * @param lv_confirmTime
	 */
	public void setLv_confirmTime(String lv_confirmTime) {
		setAttribute(LV_CONFIRMTIME, lv_confirmTime);
	}

	/**
	 * 获取开始时间
	 * @return
	 */
	public String getLv_startTime() {
		return getAttribute(LV_STARTTIME);
	}

	/**
	 * 设置开始时间
	 * @param lv_startTime
	 */
	public void setLv_startTime(String lv_startTime) {
		setAttribute(LV_STARTTIME, lv_startTime);
	}

	/**
	 * 获取结束时间
	 * @return
	 */
	public String getLv_endTime() {
		return getAttribute(LV_ENDTIME);
	}

	/**
	 * 设置结束时间
	 * @param lv_endTime
	 */
	public void setLv_endTime(String lv_endTime) {
		setAttribute(LV_ENDTIME, lv_endTime);
	}

	/**
	 * 获取休假天数
	 * @return
	 */
	public String getLv_days() {
		return getAttribute(LV_DAYS);
	}

	/**
	 * 设置休假天数
	 * @param lv_days
	 */
	public void setLv_days(String lv_days) {
		setAttribute(LV_DAYS, lv_days);
	}

	/**
	 * 获取休假详情
	 * @return
	 */
	public String getLv_details() {
		return getAttribute(LV_DETAILS);
	}

	/**
	 * 设置休假详情
	 * @param lv_details
	 */
	public void setLv_details(String lv_details) {
		setAttribute(LV_DETAILS, lv_details);
	}

	/**
	 * 获取审批人
	 * @return
	 */
	public String getLv_approval() {
		return getAttribute(LV_APPROVAL);
	}

	/**
	 * 设置审批人
	 * @param lv_approval
	 */
	public void setLv_approval(String lv_approval) {
		setAttribute(LV_APPROVAL, lv_approval);
	}

	/**
	 * 获取操作  0待审批，1审批通过，2审批拒绝，3已撤销
	 * @return
	 */
	public String getLv_operation() {
		return getAttribute(LV_OPERATION);
	}

	/**
	 * 设置操作  0待审批，1审批通过，2审批拒绝，3已撤销
	 * @param lv_operation
	 */
	public void setLv_operation(String lv_operation) {
		setAttribute(LV_OPERATION, lv_operation);
	}

	/**
	 * 获取审批详情
	 * @return
	 */
	public String getLv_approvalDesc() {
		return getAttribute(LV_APPROVALDESC);
	}

	/**
	 * 设置审批详情
	 * @param lv_approvalDesc
	 */
	public void setLv_approvalDesc(String lv_approvalDesc) {
		setAttribute(LV_APPROVALDESC, lv_approvalDesc);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取更新人
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置更新人
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

	/**
	 * 获取更新时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置更新时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取外键(区域)
	 * @return
	 */
	public String getFk_region() {
		return getAttribute(FK_REGION);
	}

	/**
	 * 设置外键(区域)
	 * @param fk_region
	 */
	public void setFk_region(String fk_region) {
		setAttribute(FK_REGION, fk_region);
	}

	/**
	 * 获取外键(人员组)
	 * @return
	 */
	public String getFk_people() {
		return getAttribute(FK_PEOPLE);
	}

	/**
	 * 设置外键(人员组)
	 * @param fk_people
	 */
	public void setFk_people(String fk_people) {
		setAttribute(FK_PEOPLE, fk_people);
	}

	/**
	 * 获取外键(公司)
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置外键(公司)
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
