/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.fmdata_eq.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 设备所属系统实体类
 * 
 * @author zhi.zhang
 * @version since Shareworx platform 2.0
 */
public class YJWYEqSysModel extends DomainModel {

	private static final long serialVersionUID = 1L;
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_device_fmdata_eq_sys";
	
	/** 主键 */
	public final static String EQ_SYS_ID = "eq_sys_id";	
	/** 系统名称 */
	public final static String NAME = "name";	
	/** 排序号 */
	public final static String SORT_NO = "sort_no";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 父类ID */
	public final static String PARENT_ID = "parent_id";	
	/** 0--未删除，1--删除 */
	public final static String DELETE_FLAG = "delete_flag";	
	/** 系统编码 */
	public final static String CODE = "code";	
	/** 创建人 */
	public final static String PK_USER = "pk_user";	
	/** 描述 */
	public final static String DESCRIPTION = "description";	
	/** 所属系统 */
	public final static String BELONG_SYS = "belong_sys";	
	/** 创建人姓名 */
	public final static String USER_NAME = "user_name";	
	/** 系统BIM */
	public final static String EQ_CLASS = "eq_class";	
	/** 本身以及父类ID的集合 */
	public final static String ALL_IDS = "all_ids";	
	/** 关联设备数,未用到 */
	public final static String EQ_COUNT = "eq_count";	
	/** 公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYEqSysModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return EQ_SYS_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case EQ_SYS_ID:
			return "eq_sys_id";
		case NAME:
			return "name";
		case SORT_NO:
			return "sort_no";
		case CREATE_TIME:
			return "create_time";
		case PARENT_ID:
			return "parent_id";
		case DELETE_FLAG:
			return "delete_flag";
		case CODE:
			return "code";
		case PK_USER:
			return "pk_user";
		case DESCRIPTION:
			return "description";
		case BELONG_SYS:
			return "belong_sys";
		case USER_NAME:
			return "user_name";
		case EQ_CLASS:
			return "eq_class";
		case ALL_IDS:
			return "all_ids";
		case EQ_COUNT:
			return "eq_count";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getEq_sys_id() {
		return getAttribute(EQ_SYS_ID);
	}

	/**
	 * 设置主键
	 * @param eq_sys_id
	 */
	public void setEq_sys_id(String eq_sys_id) {
		setAttribute(EQ_SYS_ID, eq_sys_id);
	}

	/**
	 * 获取系统名称
	 * @return
	 */
	public String getName() {
		return getAttribute(NAME);
	}

	/**
	 * 设置系统名称
	 * @param name
	 */
	public void setName(String name) {
		setAttribute(NAME, name);
	}

	/**
	 * 获取排序号
	 * @return
	 */
	public Integer getSort_no() {
		return getAttribute(SORT_NO);
	}

	/**
	 * 设置排序号
	 * @param sort_no
	 */
	public void setSort_no(Integer sort_no) {
		setAttribute(SORT_NO, sort_no);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取父类ID
	 * @return
	 */
	public String getParent_id() {
		return getAttribute(PARENT_ID);
	}

	/**
	 * 设置父类ID
	 * @param parent_id
	 */
	public void setParent_id(String parent_id) {
		setAttribute(PARENT_ID, parent_id);
	}

	/**
	 * 获取0--未删除，1--删除
	 * @return
	 */
	public String getDelete_flag() {
		return getAttribute(DELETE_FLAG);
	}

	/**
	 * 设置0--未删除，1--删除
	 * @param delete_flag
	 */
	public void setDelete_flag(String delete_flag) {
		setAttribute(DELETE_FLAG, delete_flag);
	}

	/**
	 * 获取系统编码
	 * @return
	 */
	public String getCode() {
		return getAttribute(CODE);
	}

	/**
	 * 设置系统编码
	 * @param code
	 */
	public void setCode(String code) {
		setAttribute(CODE, code);
	}

	/**
	 * 获取创建人
	 * @return
	 */
	public String getPk_user() {
		return getAttribute(PK_USER);
	}

	/**
	 * 设置创建人
	 * @param pk_user
	 */
	public void setPk_user(String pk_user) {
		setAttribute(PK_USER, pk_user);
	}

	/**
	 * 获取描述
	 * @return
	 */
	public String getDescription() {
		return getAttribute(DESCRIPTION);
	}

	/**
	 * 设置描述
	 * @param description
	 */
	public void setDescription(String description) {
		setAttribute(DESCRIPTION, description);
	}

	/**
	 * 获取所属系统
	 * @return
	 */
	public String getBelong_sys() {
		return getAttribute(BELONG_SYS);
	}

	/**
	 * 设置所属系统
	 * @param belong_sys
	 */
	public void setBelong_sys(String belong_sys) {
		setAttribute(BELONG_SYS, belong_sys);
	}

	/**
	 * 获取创建人姓名
	 * @return
	 */
	public String getUser_name() {
		return getAttribute(USER_NAME);
	}

	/**
	 * 设置创建人姓名
	 * @param user_name
	 */
	public void setUser_name(String user_name) {
		setAttribute(USER_NAME, user_name);
	}

	/**
	 * 获取系统BIM
	 * @return
	 */
	public String getEq_class() {
		return getAttribute(EQ_CLASS);
	}

	/**
	 * 设置系统BIM
	 * @param eq_class
	 */
	public void setEq_class(String eq_class) {
		setAttribute(EQ_CLASS, eq_class);
	}

	/**
	 * 获取本身以及父类ID的集合
	 * @return
	 */
	public String getAll_ids() {
		return getAttribute(ALL_IDS);
	}

	/**
	 * 设置本身以及父类ID的集合
	 * @param all_ids
	 */
	public void setAll_ids(String all_ids) {
		setAttribute(ALL_IDS, all_ids);
	}

	/**
	 * 获取关联设备数,未用到
	 * @return
	 */
	public String getEq_count() {
		return getAttribute(EQ_COUNT);
	}

	/**
	 * 设置关联设备数,未用到
	 * @param eq_count
	 */
	public void setEq_count(String eq_count) {
		setAttribute(EQ_COUNT, eq_count);
	}

	/**
	 * 获取公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
