/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.basic.executor.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 分组和人员关系表实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYGroupUserModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_executor_group_user";
	
	/** 分组id */
	public final static String PK_GROUP = "pk_group";	
	/** 人员id */
	public final static String PK_USER = "pk_user";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public YJWYGroupUserModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_GROUP;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_GROUP:
			return "pk_group";
		case PK_USER:
			return "pk_user";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取分组id
	 * @return
	 */
	public String getPk_group() {
		return getAttribute(PK_GROUP);
	}

	/**
	 * 设置分组id
	 * @param pk_group
	 */
	public void setPk_group(String pk_group) {
		setAttribute(PK_GROUP, pk_group);
	}

	/**
	 * 获取人员id
	 * @return
	 */
	public String getPk_user() {
		return getAttribute(PK_USER);
	}

	/**
	 * 设置人员id
	 * @param pk_user
	 */
	public void setPk_user(String pk_user) {
		setAttribute(PK_USER, pk_user);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
