/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.device.patrol.plan.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 巡检维保计划实体类
 * 
 * @author jin.li
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYPlanModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_patrol_plan";
	
	/** 计划id */
	public final static String PLAN_ID = "plan_id";	
	/** 计划名称 */
	public final static String PLAN_NAME = "plan_name";	
	/** 区域id */
	public final static String PK_AREA = "pk_area";	
	/** 项目id */
	public final static String PK_PROJECT = "pk_project";	
	/** 开始时间 */
	public final static String START_TIME = "start_time";	
	/** 结束时间 */
	public final static String END_TIME = "end_time";	
	/** 人员组id */
	public final static String GROUP_ID = "group_id";	
	/** 频次 */
	public final static String FREQUENCY = "frequency";	
	/** 计划类型；0：巡检；1： 维保 */
	public final static String PLAN_TYPE = "plan_type";	
	/** 是否启用；0：禁用；1：启用 */
	public final static String IS_ENABLE = "is_enable";	
	/** 下次任务生成时间 */
	public final static String NEXT_TIME = "next_time";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人id */
	public final static String CREATE_USER = "create_user";	
	/** 修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 修改人id */
	public final static String UPDATE_USER = "update_user";	
	/** 所有分类 */
	public final static String CSIS = "csis";	
	/** 所有设备 */
	public final static String EQS = "eqs";	
	/** 所有机房 */
	public final static String ROOMS = "rooms";	
	/** 频次数量 */
	public final static String FREQUENCY_NUM = "frequency_num";	
	/** 频次单位 */
	public final static String FREQUENCY_UNIT = "frequency_unit";	

	public YJWYPlanModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PLAN_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PLAN_ID:
			return "plan_id";
		case PLAN_NAME:
			return "plan_name";
		case PK_AREA:
			return "pk_area";
		case PK_PROJECT:
			return "pk_project";
		case START_TIME:
			return "start_time";
		case END_TIME:
			return "end_time";
		case GROUP_ID:
			return "group_id";
		case FREQUENCY:
			return "frequency";
		case PLAN_TYPE:
			return "plan_type";
		case IS_ENABLE:
			return "is_enable";
		case NEXT_TIME:
			return "next_time";
		case PK_CROP:
			return "pk_crop";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER:
			return "create_user";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER:
			return "update_user";
		case CSIS:
			return "csis_";
		case EQS:
			return "eqs_";
		case ROOMS:
			return "rooms_";
		case FREQUENCY_NUM:
			return "frequency_num_";
		case FREQUENCY_UNIT:
			return "frequency_unit_";
		}
		return null;
	}

	/**
	 * 获取计划id
	 * @return
	 */
	public String getPlan_id() {
		return getAttribute(PLAN_ID);
	}

	/**
	 * 设置计划id
	 * @param plan_id
	 */
	public void setPlan_id(String plan_id) {
		setAttribute(PLAN_ID, plan_id);
	}

	/**
	 * 获取计划名称
	 * @return
	 */
	public String getPlan_name() {
		return getAttribute(PLAN_NAME);
	}

	/**
	 * 设置计划名称
	 * @param plan_name
	 */
	public void setPlan_name(String plan_name) {
		setAttribute(PLAN_NAME, plan_name);
	}

	/**
	 * 获取区域id
	 * @return
	 */
	public String getPk_area() {
		return getAttribute(PK_AREA);
	}

	/**
	 * 设置区域id
	 * @param pk_area
	 */
	public void setPk_area(String pk_area) {
		setAttribute(PK_AREA, pk_area);
	}

	/**
	 * 获取项目id
	 * @return
	 */
	public String getPk_project() {
		return getAttribute(PK_PROJECT);
	}

	/**
	 * 设置项目id
	 * @param pk_project
	 */
	public void setPk_project(String pk_project) {
		setAttribute(PK_PROJECT, pk_project);
	}

	/**
	 * 获取开始时间
	 * @return
	 */
	public String getStart_time() {
		return getAttribute(START_TIME);
	}

	/**
	 * 设置开始时间
	 * @param start_time
	 */
	public void setStart_time(String start_time) {
		setAttribute(START_TIME, start_time);
	}

	/**
	 * 获取结束时间
	 * @return
	 */
	public String getEnd_time() {
		return getAttribute(END_TIME);
	}

	/**
	 * 设置结束时间
	 * @param end_time
	 */
	public void setEnd_time(String end_time) {
		setAttribute(END_TIME, end_time);
	}

	/**
	 * 获取人员组id
	 * @return
	 */
	public String getGroup_id() {
		return getAttribute(GROUP_ID);
	}

	/**
	 * 设置人员组id
	 * @param group_id
	 */
	public void setGroup_id(String group_id) {
		setAttribute(GROUP_ID, group_id);
	}

	/**
	 * 获取频次
	 * @return
	 */
	public String getFrequency() {
		return getAttribute(FREQUENCY);
	}

	/**
	 * 设置频次
	 * @param frequency
	 */
	public void setFrequency(String frequency) {
		setAttribute(FREQUENCY, frequency);
	}

	/**
	 * 获取计划类型；0：巡检；1： 维保
	 * @return
	 */
	public Integer getPlan_type() {
		return getAttribute(PLAN_TYPE);
	}

	/**
	 * 设置计划类型；0：巡检；1： 维保
	 * @param plan_type
	 */
	public void setPlan_type(Integer plan_type) {
		setAttribute(PLAN_TYPE, plan_type);
	}

	/**
	 * 获取是否启用；0：禁用；1：启用
	 * @return
	 */
	public Integer getIs_enable() {
		return getAttribute(IS_ENABLE);
	}

	/**
	 * 设置是否启用；0：禁用；1：启用
	 * @param is_enable
	 */
	public void setIs_enable(Integer is_enable) {
		setAttribute(IS_ENABLE, is_enable);
	}

	/**
	 * 获取下次任务生成时间
	 * @return
	 */
	public String getNext_time() {
		return getAttribute(NEXT_TIME);
	}

	/**
	 * 设置下次任务生成时间
	 * @param next_time
	 */
	public void setNext_time(String next_time) {
		setAttribute(NEXT_TIME, next_time);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人id
	 * @return
	 */
	public String getCreate_user() {
		return getAttribute(CREATE_USER);
	}

	/**
	 * 设置创建人id
	 * @param create_user
	 */
	public void setCreate_user(String create_user) {
		setAttribute(CREATE_USER, create_user);
	}

	/**
	 * 获取修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取修改人id
	 * @return
	 */
	public String getUpdate_user() {
		return getAttribute(UPDATE_USER);
	}

	/**
	 * 设置修改人id
	 * @param update_user
	 */
	public void setUpdate_user(String update_user) {
		setAttribute(UPDATE_USER, update_user);
	}

	/**
	 * 获取所有分类
	 * @return
	 */
	public String getCsis() {
		return getAttribute(CSIS);
	}

	/**
	 * 设置所有分类
	 * @param csis
	 */
	public void setCsis(String csis) {
		setAttribute(CSIS, csis);
	}

	/**
	 * 获取所有设备
	 * @return
	 */
	public String getEqs() {
		return getAttribute(EQS);
	}

	/**
	 * 设置所有设备
	 * @param eqs
	 */
	public void setEqs(String eqs) {
		setAttribute(EQS, eqs);
	}

	/**
	 * 获取所有机房
	 * @return
	 */
	public String getRooms() {
		return getAttribute(ROOMS);
	}

	/**
	 * 设置所有机房
	 * @param rooms
	 */
	public void setRooms(String rooms) {
		setAttribute(ROOMS, rooms);
	}

	/**
	 * 获取频次数量
	 * @return
	 */
	public String getFrequency_num() {
		return getAttribute(FREQUENCY_NUM);
	}

	/**
	 * 设置频次数量
	 * @param frequency_num
	 */
	public void setFrequency_num(String frequency_num) {
		setAttribute(FREQUENCY_NUM, frequency_num);
	}

	/**
	 * 获取频次单位
	 * @return
	 */
	public String getFrequency_unit() {
		return getAttribute(FREQUENCY_UNIT);
	}

	/**
	 * 设置频次单位
	 * @param frequency_unit
	 */
	public void setFrequency_unit(String frequency_unit) {
		setAttribute(FREQUENCY_UNIT, frequency_unit);
	}

}
