/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.problem.classadmin.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 报事分类管理实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class ProblemClassModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_problem_class";
	
	/** 主键ID */
	public final static String PK_CLASS_ID = "pk_class_id";	
	/** 分类名称 */
	public final static String CLASS_NAME = "class_name";	
	/** 是否支持下维修单 1：支持；2：不支持 */
	public final static String WHETHER_REPAIR = "whether_repair";	
	/** 是否回访 1：回访；2：不回访 */
	public final static String WHETHER_VISIT = "whether_visit";	
	/** 项目属性 */
	public final static String PROJECT_ATTRIBUTE = "project_attribute";	
	/** 处理时限 */
	public final static String TIME_LIMIT = "time_limit";	
	/** 排序 */
	public final static String SORT = "sort";	
	/** 所属上级（pk_class_id） */
	public final static String PARENT_ID = "parent_id";	
	/** 是否根目录 1：是；2：不是 */
	public final static String ROOT = "root";	
	/** 是否可用  1：是；2：不是 */
	public final static String STATE = "state";	
	/** 创建时间 */
	public final static String CREATE_TIME = "create_time";	
	/** 创建人ID */
	public final static String CREATE_USER_ID = "create_user_id";	
	/** 最后修改时间 */
	public final static String UPDATE_TIME = "update_time";	
	/** 最后修改人ID */
	public final static String UPDATE_USER_ID = "update_user_id";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	
	/** 分来编码 */
	public final static String CLASS_CODE = "class_code";	

	//非实例化字段
	
	/** 是否支持下维修单导入辅助字段 */
	public final static String IMPORT_WHETHER_REPAIR = "import_whether_repair";	
	/** 是否回访导入辅助字段  */
	public final static String IMPORT_WHETHER_VISIT = "import_whether_visit";	
	/** 处理时限导入辅助字段  */
	public final static String IMPORT_TIME_LIMIT = "import_time_limit";	
	/** 排序导入辅助字段  */
	public final static String IMPORT_SORT = "import_sort";	
	
	public ProblemClassModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_CLASS_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_CLASS_ID:
			return "pk_class_id";
		case CLASS_NAME:
			return "class_name";
		case WHETHER_REPAIR:
			return "whether_repair";
		case WHETHER_VISIT:
			return "whether_visit";
		case PROJECT_ATTRIBUTE:
			return "project_attribute";
		case TIME_LIMIT:
			return "time_limit";
		case SORT:
			return "sort";
		case PARENT_ID:
			return "parent_id";
		case ROOT:
			return "root";
		case STATE:
			return "state";
		case CREATE_TIME:
			return "create_time";
		case CREATE_USER_ID:
			return "create_user_id";
		case UPDATE_TIME:
			return "update_time";
		case UPDATE_USER_ID:
			return "update_user_id";
		case PK_CROP:
			return "pk_crop";
		case CLASS_CODE:
			return "class_code";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_class_id() {
		return getAttribute(PK_CLASS_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_class_id
	 */
	public void setPk_class_id(String pk_class_id) {
		setAttribute(PK_CLASS_ID, pk_class_id);
	}

	/**
	 * 获取分类名称
	 * @return
	 */
	public String getClass_name() {
		return getAttribute(CLASS_NAME);
	}

	/**
	 * 设置分类名称
	 * @param class_name
	 */
	public void setClass_name(String class_name) {
		setAttribute(CLASS_NAME, class_name);
	}

	/**
	 * 获取是否支持下维修单 1：支持；2：不支持
	 * @return
	 */
	public Integer getWhether_repair() {
		return getAttribute(WHETHER_REPAIR);
	}

	/**
	 * 设置是否支持下维修单 1：支持；2：不支持
	 * @param whether_repair
	 */
	public void setWhether_repair(Integer whether_repair) {
		setAttribute(WHETHER_REPAIR, whether_repair);
	}

	/**
	 * 获取是否回访 1：回访；2：不回访
	 * @return
	 */
	public Integer getWhether_visit() {
		return getAttribute(WHETHER_VISIT);
	}

	/**
	 * 设置是否回访 1：回访；2：不回访
	 * @param whether_visit
	 */
	public void setWhether_visit(Integer whether_visit) {
		setAttribute(WHETHER_VISIT, whether_visit);
	}

	/**
	 * 获取项目属性
	 * @return
	 */
	public String getProject_attribute() {
		return getAttribute(PROJECT_ATTRIBUTE);
	}

	/**
	 * 设置项目属性
	 * @param project_attribute
	 */
	public void setProject_attribute(String project_attribute) {
		setAttribute(PROJECT_ATTRIBUTE, project_attribute);
	}

	/**
	 * 获取处理时限
	 * @return
	 */
	public Integer getTime_limit() {
		return getAttribute(TIME_LIMIT);
	}

	/**
	 * 设置处理时限
	 * @param time_limit
	 */
	public void setTime_limit(Integer time_limit) {
		setAttribute(TIME_LIMIT, time_limit);
	}

	/**
	 * 获取排序
	 * @return
	 */
	public Integer getSort() {
		return getAttribute(SORT);
	}

	/**
	 * 设置排序
	 * @param sort
	 */
	public void setSort(Integer sort) {
		setAttribute(SORT, sort);
	}

	/**
	 * 获取所属上级（pk_class_id）
	 * @return
	 */
	public String getParent_id() {
		return getAttribute(PARENT_ID);
	}

	/**
	 * 设置所属上级（pk_class_id）
	 * @param parent_id
	 */
	public void setParent_id(String parent_id) {
		setAttribute(PARENT_ID, parent_id);
	}

	/**
	 * 获取是否根目录 1：是；2：不是
	 * @return
	 */
	public Integer getRoot() {
		return getAttribute(ROOT);
	}

	/**
	 * 设置是否根目录 1：是；2：不是
	 * @param root
	 */
	public void setRoot(Integer root) {
		setAttribute(ROOT, root);
	}

	/**
	 * 获取是否可用  1：是；2：不是
	 * @return
	 */
	public Integer getState() {
		return getAttribute(STATE);
	}

	/**
	 * 设置是否可用  1：是；2：不是
	 * @param state
	 */
	public void setState(Integer state) {
		setAttribute(STATE, state);
	}

	/**
	 * 获取创建时间
	 * @return
	 */
	public String getCreate_time() {
		return getAttribute(CREATE_TIME);
	}

	/**
	 * 设置创建时间
	 * @param create_time
	 */
	public void setCreate_time(String create_time) {
		setAttribute(CREATE_TIME, create_time);
	}

	/**
	 * 获取创建人ID
	 * @return
	 */
	public String getCreate_user_id() {
		return getAttribute(CREATE_USER_ID);
	}

	/**
	 * 设置创建人ID
	 * @param create_user_id
	 */
	public void setCreate_user_id(String create_user_id) {
		setAttribute(CREATE_USER_ID, create_user_id);
	}

	/**
	 * 获取最后修改时间
	 * @return
	 */
	public String getUpdate_time() {
		return getAttribute(UPDATE_TIME);
	}

	/**
	 * 设置最后修改时间
	 * @param update_time
	 */
	public void setUpdate_time(String update_time) {
		setAttribute(UPDATE_TIME, update_time);
	}

	/**
	 * 获取最后修改人ID
	 * @return
	 */
	public String getUpdate_user_id() {
		return getAttribute(UPDATE_USER_ID);
	}

	/**
	 * 设置最后修改人ID
	 * @param update_user_id
	 */
	public void setUpdate_user_id(String update_user_id) {
		setAttribute(UPDATE_USER_ID, update_user_id);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取分来编码
	 * @return
	 */
	public String getClass_code() {
		return getAttribute(CLASS_CODE);
	}

	/**
	 * 设置分来编码
	 * @param class_code
	 */
	public void setClass_code(String class_code) {
		setAttribute(CLASS_CODE, class_code);
	}
	public String getImportWhetherRepair() {
		return getAttribute(IMPORT_WHETHER_REPAIR);
	}
	public void setImportWhetherRepair(String import_whether_repair) {
		setAttribute(IMPORT_WHETHER_REPAIR, import_whether_repair);
	}

	public String getImportWhetherVisit() {
		return getAttribute(IMPORT_WHETHER_VISIT);
	}

	public void setImportWhetherVisit(String import_whether_visit) {
		setAttribute(IMPORT_WHETHER_VISIT, import_whether_visit);
	}
	
	public String getImportTimeLimit() {
		return getAttribute(IMPORT_TIME_LIMIT);
	}
	
	public void setImportTimeLimit(String import_time_limit) {
		setAttribute(IMPORT_TIME_LIMIT, import_time_limit);
	}

	public String getImportSort() {
		return getAttribute(IMPORT_SORT);
	}

	public void setImportSort(String import_sort) {
		setAttribute(IMPORT_SORT, import_sort);
	}
}
