/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.worktask.record.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 工单记录表实体类
 * 
 * @author zhangjing.cheng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYWorkTaskDetailsRecordModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_worktask_details_record";
	
	/** 主键ID */
	public final static String PK_RECORD_ID = "pk_record_id";	
	/** 详情表ID */
	public final static String FK_DETAILS_ID = "fk_details_id";	
	/** 操作表示符 */
	public final static String OPERATION_EXPRESS = "operation_express";	
	/** 任务状态 */
	public final static String TASK_STATE = "task_state";	
	/** 操作时间 */
	public final static String OPERATION_TIME = "operation_time";	
	/** 操作人ID */
	public final static String OPERATION_USER_ID = "operation_user_id";	
	/** 操作人姓名 */
	public final static String OPERATION_USER_NAME = "operation_user_name";	
	/** 操作备注 */
	public final static String OPERATION_REMARKS = "operation_remarks";	
	/** 工时 */
	public final static String TASK_TIME = "task_time";	
	/** 费用 */
	public final static String TASK_COST = "task_cost";	
	/** 满意度 */
	public final static String SATISFACTION_DEGREE = "satisfaction_degree";	
	/** 拒单原因（字典Code） */
	public final static String REFUSE_REASON = "refuse_reason";	

	public YJWYWorkTaskDetailsRecordModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_RECORD_ID;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_RECORD_ID:
			return "pk_record_id";
		case FK_DETAILS_ID:
			return "fk_details_id";
		case OPERATION_EXPRESS:
			return "operation_express";
		case TASK_STATE:
			return "task_state";
		case OPERATION_TIME:
			return "operation_time";
		case OPERATION_USER_ID:
			return "operation_user_id";
		case OPERATION_USER_NAME:
			return "operation_user_name";
		case OPERATION_REMARKS:
			return "operation_remarks";
		case TASK_TIME:
			return "task_time";
		case TASK_COST:
			return "task_cost";
		case SATISFACTION_DEGREE:
			return "satisfaction_degree";
		case REFUSE_REASON:
			return "refuse_reason";
		}
		return null;
	}

	/**
	 * 获取主键ID
	 * @return
	 */
	public String getPk_record_id() {
		return getAttribute(PK_RECORD_ID);
	}

	/**
	 * 设置主键ID
	 * @param pk_record_id
	 */
	public void setPk_record_id(String pk_record_id) {
		setAttribute(PK_RECORD_ID, pk_record_id);
	}

	/**
	 * 获取详情表ID
	 * @return
	 */
	public String getFk_details_id() {
		return getAttribute(FK_DETAILS_ID);
	}

	/**
	 * 设置详情表ID
	 * @param fk_details_id
	 */
	public void setFk_details_id(String fk_details_id) {
		setAttribute(FK_DETAILS_ID, fk_details_id);
	}

	/**
	 * 获取操作表示符
	 * @return
	 */
	public String getOperation_express() {
		return getAttribute(OPERATION_EXPRESS);
	}

	/**
	 * 设置操作表示符
	 * @param operation_express
	 */
	public void setOperation_express(String operation_express) {
		setAttribute(OPERATION_EXPRESS, operation_express);
	}

	/**
	 * 获取任务状态
	 * @return
	 */
	public Integer getTask_state() {
		return getAttribute(TASK_STATE);
	}

	/**
	 * 设置任务状态
	 * @param task_state
	 */
	public void setTask_state(Integer task_state) {
		setAttribute(TASK_STATE, task_state);
	}

	/**
	 * 获取操作时间
	 * @return
	 */
	public String getOperation_time() {
		return getAttribute(OPERATION_TIME);
	}

	/**
	 * 设置操作时间
	 * @param operation_time
	 */
	public void setOperation_time(String operation_time) {
		setAttribute(OPERATION_TIME, operation_time);
	}

	/**
	 * 获取操作人ID
	 * @return
	 */
	public String getOperation_user_id() {
		return getAttribute(OPERATION_USER_ID);
	}

	/**
	 * 设置操作人ID
	 * @param operation_user_id
	 */
	public void setOperation_user_id(String operation_user_id) {
		setAttribute(OPERATION_USER_ID, operation_user_id);
	}

	/**
	 * 获取操作人姓名
	 * @return
	 */
	public String getOperation_user_name() {
		return getAttribute(OPERATION_USER_NAME);
	}

	/**
	 * 设置操作人姓名
	 * @param operation_user_name
	 */
	public void setOperation_user_name(String operation_user_name) {
		setAttribute(OPERATION_USER_NAME, operation_user_name);
	}

	/**
	 * 获取操作备注
	 * @return
	 */
	public String getOperation_remarks() {
		return getAttribute(OPERATION_REMARKS);
	}

	/**
	 * 设置操作备注
	 * @param operation_remarks
	 */
	public void setOperation_remarks(String operation_remarks) {
		setAttribute(OPERATION_REMARKS, operation_remarks);
	}

	/**
	 * 获取工时
	 * @return
	 */
	public Integer getTask_time() {
		return getAttribute(TASK_TIME);
	}

	/**
	 * 设置工时
	 * @param task_time
	 */
	public void setTask_time(Integer task_time) {
		setAttribute(TASK_TIME, task_time);
	}

	/**
	 * 获取费用
	 * @return
	 */
	public BigDecimal getTask_cost() {
		return getAttribute(TASK_COST);
	}

	/**
	 * 设置费用
	 * @param task_cost
	 */
	public void setTask_cost(BigDecimal task_cost) {
		setAttribute(TASK_COST, task_cost);
	}

	/**
	 * 获取满意度
	 * @return
	 */
	public String getSatisfaction_degree() {
		return getAttribute(SATISFACTION_DEGREE);
	}

	/**
	 * 设置满意度
	 * @param satisfaction_degree
	 */
	public void setSatisfaction_degree(String satisfaction_degree) {
		setAttribute(SATISFACTION_DEGREE, satisfaction_degree);
	}

	/**
	 * 获取拒单原因（字典Code）
	 * @return
	 */
	public String getRefuse_reason() {
		return getAttribute(REFUSE_REASON);
	}

	/**
	 * 设置拒单原因（字典Code）
	 * @param refuse_reason
	 */
	public void setRefuse_reason(String refuse_reason) {
		setAttribute(REFUSE_REASON, refuse_reason);
	}

}
