/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.problem.classadmin.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 测试用的实体类
 * 
 * @author jiangwei.peng
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class yjwyjwtest_csModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwyjwtest_cs";
	
	/** 主键 */
	public final static String PK_TEST = "pk_test";	
	/** 名称 */
	public final static String NAME = "name";	
	/** 代码 */
	public final static String CODE = "code";	

	public yjwyjwtest_csModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_TEST;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_TEST:
			return "pk_test_";
		case NAME:
			return "name_";
		case CODE:
			return "code_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_test() {
		return getAttribute(PK_TEST);
	}

	/**
	 * 设置主键
	 * @param pk_test
	 */
	public void setPk_test(String pk_test) {
		setAttribute(PK_TEST, pk_test);
	}

	/**
	 * 获取名称
	 * @return
	 */
	public String getName() {
		return getAttribute(NAME);
	}

	/**
	 * 设置名称
	 * @param name
	 */
	public void setName(String name) {
		setAttribute(NAME, name);
	}

	/**
	 * 获取代码
	 * @return
	 */
	public String getCode() {
		return getAttribute(CODE);
	}

	/**
	 * 设置代码
	 * @param code
	 */
	public void setCode(String code) {
		setAttribute(CODE, code);
	}

}
