/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.baseinfo.resources.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 基础属性表实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class YJWYBaseAttributeModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_base_attribute";
	
	/** 主键id */
	public final static String PK_ATTRIBUTE = "pk_attribute";	
	/** 属性名称 */
	public final static String ATTRIBUTE_CODE = "attribute_code";	
	/** 标示列 */
	public final static String ATTRIBUTE_MARK = "attribute_mark";	

	public YJWYBaseAttributeModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_ATTRIBUTE;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_ATTRIBUTE:
			return "pk_attribute";
		case ATTRIBUTE_CODE:
			return "attribute_code_";
		case ATTRIBUTE_MARK:
			return "attribute_mark";
		}
		return null;
	}

	/**
	 * 获取主键id
	 * @return
	 */
	public String getPk_attribute() {
		return getAttribute(PK_ATTRIBUTE);
	}

	/**
	 * 设置主键id
	 * @param pk_attribute
	 */
	public void setPk_attribute(String pk_attribute) {
		setAttribute(PK_ATTRIBUTE, pk_attribute);
	}

	/**
	 * 获取属性名称
	 * @return
	 */
	public String getAttribute_code() {
		return getAttribute(ATTRIBUTE_CODE);
	}

	/**
	 * 设置属性名称
	 * @param attribute_code
	 */
	public void setAttribute_code(String attribute_code) {
		setAttribute(ATTRIBUTE_CODE, attribute_code);
	}

	/**
	 * 获取标示列
	 * @return
	 */
	public String getAttribute_mark() {
		return getAttribute(ATTRIBUTE_MARK);
	}

	/**
	 * 设置标示列
	 * @param attribute_mark
	 */
	public void setAttribute_mark(String attribute_mark) {
		setAttribute(ATTRIBUTE_MARK, attribute_mark);
	}

}
