/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.quality.proinspect.inspect.stanedition.model;

import com.shareworx.platform.persist.DomainModel;

/**
 * 版本与岗位中间表实体类
 * 
 * @author dms
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class EditionStationModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_quality_edition_station";
	
	/** 岗位主键 */
	public final static String PK_STATION = "pk_station";	
	/** 版本主键 */
	public final static String PK_EDITION = "pk_edition";	
	/** 所属公司 */
	public final static String PK_CROP = "pk_crop";	

	public EditionStationModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_STATION;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_STATION:
			return "pk_station";
		case PK_EDITION:
			return "pk_edition";
		case PK_CROP:
			return "pk_crop";
		}
		return null;
	}

	/**
	 * 获取岗位主键
	 * @return
	 */
	public String getPk_station() {
		return getAttribute(PK_STATION);
	}

	/**
	 * 设置岗位主键
	 * @param pk_station
	 */
	public void setPk_station(String pk_station) {
		setAttribute(PK_STATION, pk_station);
	}

	/**
	 * 获取版本主键
	 * @return
	 */
	public String getPk_edition() {
		return getAttribute(PK_EDITION);
	}

	/**
	 * 设置版本主键
	 * @param pk_edition
	 */
	public void setPk_edition(String pk_edition) {
		setAttribute(PK_EDITION, pk_edition);
	}

	/**
	 * 获取所属公司
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置所属公司
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

}
