/*
 * Copyright DMS Jiazht. All rights reserved.
 * 
 * The code was generated by tools.
 * if you want to modify it, regenerate is Deprecated.
 * if you want to regenerate the code strongly, please backup the code first.
 */
package com.shareworx.ezfm.system.crop.model;

import com.shareworx.platform.persist.DomainModel;
import java.math.BigDecimal;

/**
 * 企业管理实体类
 * 
 * @author Administrator
 * @version since Shareworx platform 2.0
 */
@SuppressWarnings("serial")
public class CropModel extends DomainModel {
	
	/**
	 * 元数据名称
	 */
	public final static String META_ID = "yjwy_crop";
	
	/** 主键 */
	public final static String PK_CROP = "pk_crop";	
	/** 企业编码 */
	public final static String CROP_CODE = "crop_code";	
	/** 企业名称 */
	public final static String CROP_NAME = "crop_name";	
	/** 联系地址 */
	public final static String CROP_ADDRESS = "crop_address";	
	/** 联系电话 */
	public final static String CROP_PHONE = "crop_phone";	
	/** 邮政编码 */
	public final static String POSTCODE = "postcode";	
	/** 联系人 */
	public final static String CROP_CONTACT = "crop_contact";	
	/** 计费基数 */
	public final static String CROP_CHARGEBASE = "crop_chargebase";	
	/** 邮箱 */
	public final static String CROP_EMAIL = "crop_email";	
	/** 截止时间 */
	public final static String CROP_DEADLINE = "crop_deadline";	
	/** 授权数量 */
	public final static String AUTHORIZE_COUNT = "authorize_count";	
	/** 当前数量 */
	public final static String AUTHORIZE_CURRENT = "authorize_current";	
	/** 剩余数量 */
	public final static String AUTHORIZE_SURPLUS = "authorize_surplus";	

	public CropModel() {
		super(META_ID);
	}
	
	/**
	 * 获取元数据名称
	 */
	@Override
	public String getMetaName() {
		return META_ID;
	}
	
	/**
	 * 获取实体主键
	 */
	public String getPrimaryKey() {
		return PK_CROP;
	}
	
	/**
	 * 获取映射表字段
	 * @param key
	 * @return
	 */
	public String getColumn(String key) {
		switch (key) {
		case PK_CROP:
			return "pk_crop_";
		case CROP_CODE:
			return "crop_code_";
		case CROP_NAME:
			return "crop_name_";
		case CROP_ADDRESS:
			return "crop_address_";
		case CROP_PHONE:
			return "crop_phone_";
		case POSTCODE:
			return "postcode_";
		case CROP_CONTACT:
			return "crop_contact_";
		case CROP_CHARGEBASE:
			return "crop_chargebase_";
		case CROP_EMAIL:
			return "crop_email_";
		case CROP_DEADLINE:
			return "crop_deadline_";
		case AUTHORIZE_COUNT:
			return "authorize_count_";
		case AUTHORIZE_CURRENT:
			return "authorize_current_";
		case AUTHORIZE_SURPLUS:
			return "authorize_surplus_";
		}
		return null;
	}

	/**
	 * 获取主键
	 * @return
	 */
	public String getPk_crop() {
		return getAttribute(PK_CROP);
	}

	/**
	 * 设置主键
	 * @param pk_crop
	 */
	public void setPk_crop(String pk_crop) {
		setAttribute(PK_CROP, pk_crop);
	}

	/**
	 * 获取企业编码
	 * @return
	 */
	public String getCrop_code() {
		return getAttribute(CROP_CODE);
	}

	/**
	 * 设置企业编码
	 * @param crop_code
	 */
	public void setCrop_code(String crop_code) {
		setAttribute(CROP_CODE, crop_code);
	}

	/**
	 * 获取企业名称
	 * @return
	 */
	public String getCrop_name() {
		return getAttribute(CROP_NAME);
	}

	/**
	 * 设置企业名称
	 * @param crop_name
	 */
	public void setCrop_name(String crop_name) {
		setAttribute(CROP_NAME, crop_name);
	}

	/**
	 * 获取联系地址
	 * @return
	 */
	public String getCrop_address() {
		return getAttribute(CROP_ADDRESS);
	}

	/**
	 * 设置联系地址
	 * @param crop_address
	 */
	public void setCrop_address(String crop_address) {
		setAttribute(CROP_ADDRESS, crop_address);
	}

	/**
	 * 获取联系电话
	 * @return
	 */
	public String getCrop_phone() {
		return getAttribute(CROP_PHONE);
	}

	/**
	 * 设置联系电话
	 * @param crop_phone
	 */
	public void setCrop_phone(String crop_phone) {
		setAttribute(CROP_PHONE, crop_phone);
	}

	/**
	 * 获取邮政编码
	 * @return
	 */
	public String getPostcode() {
		return getAttribute(POSTCODE);
	}

	/**
	 * 设置邮政编码
	 * @param postcode
	 */
	public void setPostcode(String postcode) {
		setAttribute(POSTCODE, postcode);
	}

	/**
	 * 获取联系人
	 * @return
	 */
	public String getCrop_contact() {
		return getAttribute(CROP_CONTACT);
	}

	/**
	 * 设置联系人
	 * @param crop_contact
	 */
	public void setCrop_contact(String crop_contact) {
		setAttribute(CROP_CONTACT, crop_contact);
	}

	/**
	 * 获取计费基数
	 * @return
	 */
	public BigDecimal getCrop_chargebase() {
		return getAttribute(CROP_CHARGEBASE);
	}

	/**
	 * 设置计费基数
	 * @param crop_chargebase
	 */
	public void setCrop_chargebase(BigDecimal crop_chargebase) {
		setAttribute(CROP_CHARGEBASE, crop_chargebase);
	}

	/**
	 * 获取邮箱
	 * @return
	 */
	public String getCrop_email() {
		return getAttribute(CROP_EMAIL);
	}

	/**
	 * 设置邮箱
	 * @param crop_email
	 */
	public void setCrop_email(String crop_email) {
		setAttribute(CROP_EMAIL, crop_email);
	}

	/**
	 * 获取截止时间
	 * @return
	 */
	public String getCrop_deadline() {
		return getAttribute(CROP_DEADLINE);
	}

	/**
	 * 设置截止时间
	 * @param crop_deadline
	 */
	public void setCrop_deadline(String crop_deadline) {
		setAttribute(CROP_DEADLINE, crop_deadline);
	}

	/**
	 * 获取授权数量
	 * @return
	 */
	public Integer getAuthorize_count() {
		return getAttribute(AUTHORIZE_COUNT);
	}

	/**
	 * 设置授权数量
	 * @param authorize_count
	 */
	public void setAuthorize_count(Integer authorize_count) {
		setAttribute(AUTHORIZE_COUNT, authorize_count);
	}

	/**
	 * 获取当前数量
	 * @return
	 */
	public Integer getAuthorize_current() {
		return getAttribute(AUTHORIZE_CURRENT);
	}

	/**
	 * 设置当前数量
	 * @param authorize_current
	 */
	public void setAuthorize_current(Integer authorize_current) {
		setAttribute(AUTHORIZE_CURRENT, authorize_current);
	}

	/**
	 * 获取剩余数量
	 * @return
	 */
	public Integer getAuthorize_surplus() {
		return getAttribute(AUTHORIZE_SURPLUS);
	}

	/**
	 * 设置剩余数量
	 * @param authorize_surplus
	 */
	public void setAuthorize_surplus(Integer authorize_surplus) {
		setAttribute(AUTHORIZE_SURPLUS, authorize_surplus);
	}

}
